[SUBMITTED 20200529] cpuidle/firmware: qcom: fix smcc dependencies
Selecting QCOM_SCM for compile-tests is broken when the smcc firmware
is not provided:

drivers/firmware/qcom_scm-smc.o: in function `scm_smc_call':
qcom_scm-smc.c:(.text+0x110): undefined reference to `__arm_smccc_smc'
drivers/firmware/qcom_scm-legacy.o: in function `scm_legacy_call':
qcom_scm-smc.c:(.text+0x1bc): undefined reference to `__arm_smccc_smc'

Add a Kconfig dependency for the QCOM_SCM to make it easier to catch
this, and fix the dependency for the newly added ARM_QCOM_SPM_CPUIDLE
symbol that triggered it this time.

Fixes: a871be6b8eee ("cpuidle: Convert Qualcomm SPM driver to a generic CPUidle driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
As the bug is currently only present in the cpuidle tree, can we
merge it through that?