[v2] tracing: events_hist: avoid using excessive stack space
In some configurations, clang produces a warning about an overly large
amount of stack space used in hist_trigger_print_key():

kernel/trace/trace_events_hist.c:4594:13: error: stack frame size of 1248 bytes in function 'hist_trigger_print_key' [-Werror,-Wframe-larger-than=]
static void hist_trigger_print_key(struct seq_file *m,

Mark the 'str' variable as 'static' to move it off the stack,
and check for the event_mutex being held to ensure this can
be done without possible races.

Suggested-by: Steven Rostedt <rostedt@goodmis.org>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
v2: use static allocation of the temporary buffer instead of
    moving it to a more local scope, as Steven suggested