Kbuild: don't build with clang -Oz for ARMv7-M
clang-8 fails to optimize out calls to __aeabi_ldivmod() for
64-bit division that are normally not emitted in any other
configuration, e.g.:

kernel/events/core.o: In function `perf_adjust_period':
mm/page-writeback.o: In function `balance_dirty_pages_ratelimited':
net/bridge/br_sysfs_br.o: In function `brforward_read':
drivers/usb/gadget/udc/atmel_usba_udc.o: In function `regs_dbg_open':
drivers/iio/imu/inv_mpu6050/inv_mpu_ring.o: In function `inv_mpu6050_read_fifo':
...: undefined reference to `__aeabi_ldivmod'

Add a special case for this so we don't offer that configuration
any more.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>