wil6210: remove obsolete msm platform code
The wil6210 driver has a glue layer for the Qualcomm MSM platform
code, which apparently could never build and is unlikely to
ever be able to in the future, as the MSM platform is being phased
out in favor of the new QCOM platform, and the driver relies
on out-of-tree infrastructure. Trying to build it currently
results in this error:

drivers/net/wireless/ath/wil6210/wil_platform_msm.c:19:27: fatal error: linux/msm-bus.h: No such file or directory

Removing the driver fixes the build and makes it possible to
build an allmodconfig kernel for MSM.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>

Conflicts:
	drivers/net/wireless/ath/wil6210/Makefile