drm: bridge: ps8622 depends on gpiolib
../drivers/gpu/drm/bridge/ps8622.c: In function 'ps8622_pre_enable':
../drivers/gpu/drm/bridge/ps8622.c:368:2: error: implicit declaration of function 'gpiod_set_value' [-Werror=implicit-function-declaration]
  gpiod_set_value(ps8622->gpio_rst, 0);
  ^
../drivers/gpu/drm/bridge/ps8622.c: In function 'ps8622_probe':
../drivers/gpu/drm/bridge/ps8622.c:584:2: error: implicit declaration of function 'devm_gpiod_get' [-Werror=implicit-function-declaration]
  ps8622->gpio_slp = devm_gpiod_get(dev, "sleep");
  ^

Signed-off-by: Arnd Bergmann <arnd@arndb.de>