[SUBMITTED 20190322] soc: mtk-pmic-wrap: fix uninitialized variable use
clang correctly points out that we print an uninitialized
variable if the PWRAP_DEW_WRITE_TEST write or read fails:

drivers/soc/mediatek/mtk-pmic-wrap.c:1358:6: error: variable 'rdata' is used uninitialized whenever '||' condition is
      true [-Werror,-Wsometimes-uninitialized]
        if (pwrap_write(wrp, wrp->slave->dew_regs[PWRAP_DEW_WRITE_TEST],
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/soc/mediatek/mtk-pmic-wrap.c:1363:39: note: uninitialized use occurs here
                dev_err(wrp->dev, "rdata=0x%04X\n", rdata);
                                                    ^~~~~
include/linux/device.h:1485:32: note: expanded from macro 'dev_err'
        _dev_err(dev, dev_fmt(fmt), ##__VA_ARGS__)
                                      ^~~~~~~~~~~
drivers/soc/mediatek/mtk-pmic-wrap.c:1358:6: note: remove the '||' if its condition is always false
        if (pwrap_write(wrp, wrp->slave->dew_regs[PWRAP_DEW_WRITE_TEST],
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/soc/mediatek/mtk-pmic-wrap.c:1284:11: note: initialize the variable 'rdata' to silence this warning
        u32 rdata;
                 ^
                  = 0

Set the variable to zero before probing the register.

Fixes: 1f022d84bd19 ("soc: mediatek: Add PMIC wrapper for MT8135 and MT8173 SoCs")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>