wan: ixp4xx_hss: avoid macro namespace conflict
Compile-testing on x86 found a namespace clash:

drivers/net/wan/ixp4xx_hss.c:46:9: error: 'FRAME_SIZE' macro redefined [-Werror,-Wmacro-redefined]
 define FRAME_SIZE              256 /* doesn't matter at this point */
        ^
arch/x86/include/uapi/asm/ptrace-abi.h:24:9: note: previous definition is here
 define FRAME_SIZE 17
        ^

Rename FRAME_SIZE and related macros in the hss driver to avoid this.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>