[SUBMITTED 20250620] platform/x86/amd_isp4: prevent built-in configuration
Checking the module owner of the device only works when modules are
enabled, and the device is created from a module:

drivers/platform/x86/amd/amd_isp4.c:154:28: error: incomplete definition of type 'struct module'

Building the driver as a loadable module avoids the build failure,
though this should probably be fixed in a different way that still
works if the device was created from built-in code.

Fixes: 90b85567e457 ("platform/x86: Add AMD ISP platform config for OV05C10")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202506150313.UHoIoVhR-lkp@intel.com/
Signed-off-by: Arnd Bergmann <arnd@arndb.de>