[SUBMITTED 20200107] input: appletouch: shut up -Wmaybe-uninitialized warning
Building with -O3 introduces a false-positive warning in this file:

In file included from include/linux/compiler_types.h:68,
                 from <command-line>:
drivers/input/mouse/appletouch.c: In function 'atp_complete_geyser_3_4':
include/linux/compiler-gcc.h:71:45: error: 'x_z' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 #define __UNIQUE_ID(prefix) __PASTE(__PASTE(__UNIQUE_ID_, prefix), __COUNTER__)
                                             ^~~~~~~~~~~~
drivers/input/mouse/appletouch.c:657:12: note: 'x_z' was declared here
  int x, y, x_z, y_z, x_f, y_f;
            ^~~
In file included from include/linux/compiler_types.h:68,
                 from <command-line>:
drivers/input/mouse/appletouch.c: In function 'atp_complete_geyser_1_2':
include/linux/compiler-gcc.h:71:45: error: 'x_z' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 #define __UNIQUE_ID(prefix) __PASTE(__PASTE(__UNIQUE_ID_, prefix), __COUNTER__)
                                             ^~~~~~~~~~~~
drivers/input/mouse/appletouch.c:517:12: note: 'x_z' was declared here
  int x, y, x_z, y_z, x_f, y_f;
            ^~~

The variables are not actually used here since the only usage
happens when both 'x' and 'y' are non-zero, but this is something
that gcc fails to track.

Fixes: mmtom ("init/Kconfig: enable -O3 for all arches")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>