[SUBMITTED 20190920] mbox: qcom: avoid unused-variable warning
Without CONFIG_OF, there is no reference to the apcs_clk_match_table[]
array, causing a harmless warning:

drivers/mailbox/qcom-apcs-ipc-mailbox.c:57:28: error: unused variable 'apcs_clk_match_table' [-Werror,-Wunused-variable]
        const struct of_device_id apcs_clk_match_table[] = {

Move the variable out of the variable scope and mark it 'static'
to avoid the warning (static const variables get silently dropped
by the compiler), and avoid the on-stack copy at the same time.

Fixes: 78c86458a440 ("mbox: qcom: add APCS child device for QCS404")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>