spi: sirf: add reset controller dependency
The sirf spi driver only builds correctly if the reset controller
framework is available, otherwise we get an error:

drivers/spi/spi-sirf.c: In function 'spi_sirfsoc_probe':
drivers/spi/spi-sirf.c:651:2: error: implicit declaration of function 'device_reset' [-Werror=implicit-function-declaration]

The adds a dependency in Kconfig to prevent it from being selected
if the resets are not available.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes:  8509c55fcb51 ("spi: sirf: reset SPI controller in init stage")