[SUBMITTED 20240213] quota: avoid printing an uninitialized blk number
The error path of find_tree_dqentry() now prints a variable that is
never initialized:

fs/quota/quota_tree.c:674:8: error: variable 'blk' is uninitialized when used here [-Werror,-Wuninitialized]
                            blk);
                            ^~~
include/linux/quotaops.h:34:41: note: expanded from macro 'quota_error'
        __quota_error((sb), __func__, fmt , ## args)
                                               ^~~~

Move the calculation of the block number slightly up to make it
show a sensible number.

Fixes: 223bfb57631b ("quota: Detect loops in quota tree")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>