[SUBMITTED 20180404] phy: mapphone-mdm6600: add gpiolib dependency
Without gpiolib, the gpiod_get_array_value_cansleep() is an empty stub,
so gcc notices that the resulting array is never initialized:

drivers/phy/motorola/phy-mapphone-mdm6600.c: In function 'phy_mdm6600_status':
drivers/phy/motorola/phy-mapphone-mdm6600.c:188:16: error: 'values[0]' is used uninitialized in this function [-Werror=uninitialized]
   val |= values[i] << i;
          ~~~~~~^~~
drivers/phy/motorola/phy-mapphone-mdm6600.c:188:16: error: 'values[1]' is used uninitialized in this function [-Werror=uninitialized]
drivers/phy/motorola/phy-mapphone-mdm6600.c:188:16: error: 'values[2]' is used uninitialized in this function [-Werror=uninitialized]
cc1: all warnings being treated as errors

With gpiolib enabled, this can't happen and we don't get the warning, so
let's just add a Kconfig dependency for it.

Fixes: 5d1ebbda0318 ("phy: mapphone-mdm6600: Add USB PHY driver for MDM6600 on Droid 4")
Cc: Tony Lindgren <tony@atomide.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>