ARM: fix semihosting build failure
After debugging was enabled for the decompressor, we get this
build failure when CONFIG_DEBUG_SEMIHOSTING is set:

include/generated/autoconf.h:1920:33: fatal error: mach/debug-macro.S: No such file or directory
 1920 | #define CONFIG_DEBUG_LL_INCLUDE "mach/debug-macro.S"

There should be a way to make it work even with semihosting,
but for now, this just disables the combination.

Fixes: 2596a72d3384 ("ARM: 9009/1: uncompress: Enable debug in head.S")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>