ASoC: fsl: fix dependencies for wm8962
The wm8962 driver uses the input subsystem, but is selected by
SND_SOC_FSL_ASOC_CARD, which can be built with CONFIG_INPUT
disabled, resulting in this link error:

ERROR: "input_event" [sound/soc/codecs/snd-soc-wm8962.ko] undefined!
ERROR: "input_register_device" [sound/soc/codecs/snd-soc-wm8962.ko] undefined!
ERROR: "devm_input_allocate_device" [sound/soc/codecs/snd-soc-wm8962.ko] undefined!

This adds an explicit Kconfig dependency to prevent this configuration
from being used.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 708b4351f08 ("ASoC: fsl: Add Freescale Generic ASoC Sound Card with ASRC support")