media: venus: select qcom firmware unconditionally
qcom_scm has become user-selectable and 'tristate' now, which
means we can build it as a loadable module while having the
venus driver built-in, causing a link failure:

arm-linux-gnueabi-ld: drivers/media/platform/qcom/venus/firmware.o: in function `venus_set_hw_state':
firmware.c:(.text+0x60): undefined reference to `qcom_scm_set_remote_state'
arm-linux-gnueabi-ld: drivers/media/platform/qcom/venus/firmware.o: in function `venus_shutdown':
firmware.c:(.text+0x1ac): undefined reference to `qcom_scm_pas_shutdown'

Change the 'select' to even enable those modules when compile-testing
to ensure that all dependencies are met correctly.

Fixes: b42000e4b874 ("firmware: qcom_scm: Allow qcom_scm driver to be loadable as a permenent module")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>