[SUBMITTED 20160706] pinctrl: imx21: include linux/module.h
The pinctrl driver includes a device table, but the macro used for
declaring it is declared in a header that is not visible here:

drivers/pinctrl/freescale/pinctrl-imx21.c:328:1: error: data definition has no type or storage class [-Werror]
 MODULE_DEVICE_TABLE(of, imx21_pinctrl_of_match);

This adds the missing include.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: e2756baa4217 ("pinctrl: imx21: make it explicitly non-modular")