[SUBMITTED] netfilter: fix Kconfig dependencies for nft_dup_ipv{4,6}
nft_dup_ipv4 and nft_dup_ipv6 select the respective nf_dup_ipv{4,6}
drivers, which must not be built-in if nf_conntrack is a loadable
module, otherwise we get a link error:

net/built-in.o: In function `nf_dup_ipv6':
(.text+0xdef20): undefined reference to `nf_conntrack_untracked'

The dependency was fixed for the nf_dup_* modules recently, but this
patch adds the same dependency to the nft_dup_* modules for
the (hopefully) complete fix.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 6ece90f9a13e ("netfilter: fix Kconfig dependencies for nf_dup_ipv{4,6}")