ARM: imx: remove unused mx25_revision()
This function has no prototype and no callers:

arm/mach-imx/cpu-imx25.c:43:5: error: no previous prototype for 'mx25_revision' [-Werror=missing-prototypes]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>