ionic: fix linking against PTP code
When the PTP_1588_CLOCK support is a loadable module, the ionic
fails to link as a built-in driver because its own clock support
gets left out:

aarch64-linux-ld: drivers/net/ethernet/pensando/ionic/ionic_lif.o: in function `ionic_do_ioctl':
ionic_lif.c:(.text+0xc24): undefined reference to `ionic_lif_hwstamp_get'
aarch64-linux-ld: ionic_lif.c:(.text+0xc6c): undefined reference to `ionic_lif_hwstamp_set'
aarch64-linux-ld: drivers/net/ethernet/pensando/ionic/ionic_lif.o: in function `ionic_lif_alloc':
ionic_lif.c:(.text+0x6e80): undefined reference to `ionic_lif_alloc_phc'
aarch64-linux-ld: drivers/net/ethernet/pensando/ionic/ionic_lif.o: in function `ionic_lif_free':
ionic_lif.c:(.text+0x6fa4): undefined reference to `ionic_lif_free_phc'
aarch64-linux-ld: drivers/net/ethernet/pensando/ionic/ionic_lif.o: in function `ionic_lif_handle_fw_up':
ionic_lif.c:(.text+0x76f4): undefined reference to `ionic_lif_hwstamp_replay'

Changing the way this driver is built to include that code anyway would
cause a similar link error against the PTP core.

Solve it by using Kconfig logic to avoid the broken configuration and
force the ionic driver to also be a loadable module unless the ptp
core is either built-in or disabled.

Fixes: 61db421da31b ("ionic: link in the new hw timestamp code")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>