ARM: lpc32xx: add missing include
lpc32xx_loopback_set() is defined in linux/soc/nxp/lpc32xx-misc.h but
this is not included before the function definition.

arch/arm/mach-lpc32xx/serial.c:63:6: error: no previous prototype for 'lpc32xx_loopback_set'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>