ipvs: use div_s64 for signed division
do_div() is only well-behaved for positive numbers, and now warns
when the first argument is a an s64:

net/netfilter/ipvs/ip_vs_est.c: In function 'ip_vs_est_calc_limits':
include/asm-generic/div64.h:222:35: error: comparison of distinct pointer types lacks a cast [-Werror]
  222 |         (void)(((typeof((n)) *)0) == ((uint64_t *)0));  \
      |                                   ^~
net/netfilter/ipvs/ip_vs_est.c:694:17: note: in expansion of macro 'do_div'
  694 |                 do_div(val, loops);

Convert to using the more appropriate div_s64(), which also
simplifies the code a bit.

Fixes: 705dd3444081 ("ipvs: use kthreads for stats estimation")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>