rbd: work around false positive warning
gcc cannot track the content of the has_current_state across
the spinlock and gets confused here:

drivers/block/rbd.c: In function 'rbd_object_map_callback':
drivers/block/rbd.c:2122:21: error: 'current_state' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      (current_state == OBJECT_EXISTS && state == OBJECT_EXISTS_CLEAN))
drivers/block/rbd.c:2090:23: note: 'current_state' was declared here
  u8 state, new_state, current_state;
                       ^~~~~~~~~~~~~

I tried to rewrite the code to avoid the warning but could not
come up with a good fix, so this is a bad workaround, adding
a fake initialization.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>