netfilter: ebtables: address vmalloc overflow warning
Both vmalloc() and the array_size() helper are designed to avoid
an integer overflow from multiplying a user-supplied length.

However the combination ends up causing a -Walloc-size-larger-than=
warning when that is enabled:

In function 'copy_counters_to_user',
    inlined from 'copy_everything_to_user' at net/bridge/netfilter/ebtables.c:1575:8:
net/bridge/netfilter/ebtables.c:1525:23: error: argument 1 value '4294967295' exceeds maximum object size 2147483647 [-Werror=alloc-size-larger-than=]
 1525 |         counterstmp = vmalloc(array_size(nentries, sizeof(*counterstmp)));
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from net/bridge/netfilter/ebtables.c:16:
include/linux/vmalloc.h: In function 'copy_everything_to_user':
include/linux/vmalloc.h:142:14: note: in a call to allocation function 'vmalloc' declared here
  142 | extern void *vmalloc(unsigned long size) __alloc_size(1);
      |              ^~~~~~~

Use the vmalloc_array() helper instead.

Cc: Kees Cook <keescook@chromium.org>
Fixes: 42bc47b35320 ("treewide: Use array_size() in vmalloc()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
Kees, you did the original conversion to array_size and the __alloc_size
annotation here, so you probably have an idea of what is going on here.

Does this make sense to you, and should we consider another mass
conversion? I have no idea why I only see the warning in this one
function, but not elsewhere.