test_overflow: mark malloc tests as noinline
With KASAN and asan-stack enabled, all the malloc tests get inlined into
a single function, leading to an extreme kernel stack usage:

lib/test_overflow.c: In function 'test_overflow_allocation':
lib/test_overflow.c:589:1: error: the frame size of 1456 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

I could not figure out why this happens, but marking the
individual tests as noinline_for_stack reduces the stack
usage of each one to 192 bytes here, which seems harmless
enough.

Fixes: ca90800a91ba ("test_overflow: Add memory allocation overflow tests")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>