[SUBMITTED 20230323] mm: vmalloc: fix vmap_ram_vread_iter() return value
The error handling in vmap_ram_vread_iter() can return an
uninitialized value in some cases:

mm/vmalloc.c:3539:6: error: variable 'remains' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
        if (!vb)
            ^~~
mm/vmalloc.c:3587:17: note: uninitialized use occurs here
        return count - remains + zero_iter(iter, remains);
                       ^~~~~~~

Move the initialization up a few lines.

Fixes: d9cab54f7737 ("mm: vmalloc: convert vread() to vread_iter()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>