[SUBMITTED] mm, page_owner: only track migration if enabled
The newly added code to print page ownership in dump_page fails
to link when CONFIG_MIGRATION is disabled:

mm/built-in.o: In function `print_page_owner':
frame_vector.c:(.text+0x72358): undefined reference to `migrate_reason_names'

This changes the two users of migrate_reason_names to first check
CONFIG_MIGRATION, which avoids the error.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: cf7ec391dae4 ("mm, page_owner: dump page owner info from dump_page()")