power: collie_battery: hide unused variable
drivers/power/collie_battery.c:29:12: error: 'wakeup_enabled' defined but not used [-Werror=unused-variable]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>