parisc: iommu: remove SBA_INLINE/CCIO_INLINE macros
The CCIO_INLINE macro is added in the wrong place:

drivers/parisc/ccio-dma.c:555:1: error: 'inline' is not at beginning of declaration [-Werror=old-style-declaration]
  555 | static void CCIO_INLINE
drivers/parisc/sba_iommu.c:565:1: error: 'inline' is not at beginning of declaration [-Werror=old-style-declaration]
  565 | static void SBA_INLINE

It could be replaced with regular 'inline', but as gcc is usually
better at figuring out whether to inline functions, and these are
rather big functions to start with, just remove these completely.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>