ipv4: ipconfig: avoid unused ic_proto_used symbol
net/ipv4/ipconfig.c:146:12: error: 'ic_proto_used' defined but not used [-Werror=unused-variable]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>