ARM: always select IRQ_WORK on SMP
Any SMP kernel now requires the irq_work code after
generic_smp_call_function_single_interrupt() started using it,
or we get:

kernel/built-in.o: In function `flush_smp_call_function_queue':
:(.text+0x4dc3a): undefined reference to `irq_work_run'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 478850160636c4f ("irq_work: Implement remote queueing")