mtd: rawnand: toshiba: avoid unused variable warnigns
drivers/mtd/nand/raw/nand_toshiba.c: In function 'toshiba_nand_read_page_benand':
drivers/mtd/nand/raw/nand_toshiba.c:54:19: error: unused variable 'mtd' [-Werror=unused-variable]
  struct mtd_info *mtd = nand_to_mtd(chip);
                   ^~~
drivers/mtd/nand/raw/nand_toshiba.c: In function 'toshiba_nand_read_subpage_benand':
drivers/mtd/nand/raw/nand_toshiba.c:68:19: error: unused variable 'mtd' [-Werror=unused-variable]
  struct mtd_info *mtd = nand_to_mtd(chip);

Fixes: fe8b76ec9886 ("mtd: rawnand: toshiba: Pass a single nand_chip object to the status helper")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>