RDMA/siw: Fix 64/32bit pointer inconsistency a bit more
Despite the previous fix, there is still a warning on 32-bit
architectures:

drivers/infiniband/sw/siw/siw_qp_rx.c: In function 'siw_rx_pbl':
drivers/infiniband/sw/siw/siw_qp_rx.c:142:23: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
   if (siw_rx_kva(srx, (void *)buf_addr, bytes) == bytes) {

Apply the same workaround as before here.

Fixes: c536277e0db1 ("RDMA/siw: Fix 64/32bit pointer inconsistency")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>