[SUBMITTED 20211019] dmaengine: stm32-dma: avoid 64-bit division in stm32_dma_get_max_width
Using the % operator on a 64-bit variable is expensive and can
cause a link failure:

arm-linux-gnueabi-ld: drivers/dma/stm32-dma.o: in function `stm32_dma_get_max_width':
stm32-dma.c:(.text+0x170): undefined reference to `__aeabi_uldivmod'
arm-linux-gnueabi-ld: drivers/dma/stm32-dma.o: in function `stm32_dma_set_xfer_param':
stm32-dma.c:(.text+0x1cd4): undefined reference to `__aeabi_uldivmod'

As we know that we just want to check the alignment in
stm32_dma_get_max_width(), there is no need for a full division, and
using a simple mask is a faster replacement.

In stm32_dma_set_xfer_param(), it is possible to pass a non-power-of-two
length, so this does not work. I assume this would in fact be a mistake,
and the hardware does not work correctly with a burst of e.g. 5 bytes
on a five-byte aligned address. Change this to only allow burst
transfers if the address is a multiple of the length, and that length
is a power-of-two number.

Fixes: b20fd5fa310c ("dmaengine: stm32-dma: fix stm32_dma_get_max_width")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>