drm/amd/display: work around -Wmaybe-uninitialized warning
The Renoir code confuses gcc into thinking one variable
might be used without an initialization.

drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn21/display_mode_vba_21.c: In function 'CalculateVMAndRowBytes.constprop':
drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn21/display_mode_vba_21.c:1449:37: error: 'PixelPTEReqHeightPTEs' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   if (SurfaceTiling != dm_sw_linear && PixelPTEReqHeightPTEs == 1 && ScanDirection != dm_horz) {
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This case does not happen because the use is inside of an 'if
(GPUVMEnable)' check, which is the same condition used for the
initialization. Add a fake initialization in the 'else' path,
next to where we already set PixelPTEBytesPerRow.

Fixes: b04641a3f4c5 ("drm/amd/display: Add Renoir DML")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>