[SUBMITTED 20190307] x86: vdso: fix compat_vdso build
When we build the compat vdso, the kernel headers will be used
with a 32-bit compiler combined with configuration options
for the 64-bit kernel, which leads to many undesired effects
from header files that make assumptions about the configuration
options, such as:

In file included from include/linux/mm_types.h:15,
                 from include/asm-generic/fixmap.h:19,
                 from arch/x86/include/asm/fixmap.h:193,
                 from arch/x86/include/asm/apic.h:10,
                 from arch/x86/include/asm/smp.h:13,
                 from include/linux/smp.h:68,
                 from include/linux/percpu.h:7,
                 from include/linux/hrtimer.h:19,
                 from arch/x86/entry/vdso/vdso32/../../../../../lib/vdso/gettimeofday.c:9,
                 from arch/x86/entry/vdso/vdso32/../vclock_gettime.c:13,
                 from arch/x86/entry/vdso/vdso32/vclock_gettime.c:31:
include/linux/page-flags-layout.h:95:2: error: #warning "KASAN: not enough bits in page flags for tag" [-Werror=cpp]
 #warning "KASAN: not enough bits in page flags for tag"
  ^~~~~~~

Limit the scope of the headers much more, by removing linux/hrtimer.h
and asm/mshyperv.h from the list of included files. Instead, the parts
we actually need are moved into separate headers that are included
by the normal ones.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>