[SUBMITTED 20200428] x86/unwind/orc: fix unused function warnings
Without CONFIG_MODULES, these two variables are unused:

arch/x86/kernel/unwind_orc.c:29:26: error: 'cur_orc_table' defined but not used [-Werror=unused-variable]
   29 | static struct orc_entry *cur_orc_table = __start_orc_unwind;
      |                          ^~~~~~~~~~~~~
arch/x86/kernel/unwind_orc.c:28:13: error: 'cur_orc_ip_table' defined but not used [-Werror=unused-variable]
   28 | static int *cur_orc_ip_table = __start_orc_unwind_ip;
      |             ^~~~~~~~~~~~~~~~

Move them into the #ifdef section.

Fixes: 153eb2223c79 ("x86/unwind/orc: Convert global variables to static")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>