ARM: spear: include "pl080.h" for pl080_get_signal() prototype
pl080_get_signal() and pl080_put_signal() are declared in pl080.h
and defined in pl080.c, but this file is missing an include
of the header:

arch/arm/mach-spear/pl080.c:27:5: error: no previous prototype for 'pl080_get_signal'
arch/arm/mach-spear/pl080.c:62:6: error: no previous prototype for 'pl080_put_signal'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>