[SUBMITTED 20201204] cpufreq: scmi: add COMMON_CLK dependency
Wtihout CONFIG_COMMON_CLK, the scmi driver fails to link:

arm-linux-gnueabi-ld: drivers/cpufreq/scmi-cpufreq.o: in function `scmi_cpufreq_probe':
scmi-cpufreq.c:(.text+0x20c): undefined reference to `devm_of_clk_add_hw_provider'
arm-linux-gnueabi-ld: scmi-cpufreq.c:(.text+0x22c): undefined reference to `of_clk_hw_simple_get'

Add a Kconfig dependency for it.

Fixes: 8410e7f3b31e ("cpufreq: scmi: Fix OPP addition failure with a dummy clock provider")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>