media: rtl28xxu: reduce kernel stack usage
The USB register access uses suboptimal calling conventions that
require allocating a struct on the stack for each access. With
KASAN, that leads to an overly large stack usage:

drivers/media/usb/dvb-usb-v2/rtl28xxu.c: In function 'rtl2832u_read_config':
drivers/media/usb/dvb-usb-v2/rtl28xxu.c:603:1: error: the frame size of 1408 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Use a helper function to ensure we always pass the arguments
in registers rather than a struct.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>