sh: define nommio ioremap/iounmap as inline functions
Build testing se7619_defconfig produces a harmless warning:

drivers/tty/serial/sh-sci.c: In function 'sci_remap_port':
drivers/tty/serial/sh-sci.c:2666:19: error: unused variable 'sport' [-Werror=unused-variable]
 2666 |  struct sci_port *sport = to_sci_port(port);

Change the definition of the two helpers to inline functions
to get proper type checking as well as telling the compiler
when these veriables are actually used.

Fixes: e4d6f911a7ce ("sh-sci: Get register size from platform device")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>