gcov: add prototypes for internal functions
gcov uses global functions that are called from generated code,
but these have no prototype in a header, which causes a W=1
build warning:

kernel/gcov/gcc_base.c:12:6: error: no previous prototype for '__gcov_init' [-Werror=missing-prototypes]
kernel/gcov/gcc_base.c:40:6: error: no previous prototype for '__gcov_flush' [-Werror=missing-prototypes]
kernel/gcov/gcc_base.c:46:6: error: no previous prototype for '__gcov_merge_add' [-Werror=missing-prototypes]
kernel/gcov/gcc_base.c:52:6: error: no previous prototype for '__gcov_merge_single' [-Werror=missing-prototypes]

Add prototypes for all of these to an internal header.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>