[SUBMITTED] ASoC: Samsung: add missing I2C/SPI dependencies
The SND_SOC_ARNDALE_RT5631_ALC5631 selects the rt5631 codec
that requires I2C to work, so we get a build error if I2C
is disabled:

codecs/rt5631.c:1737:1: warning: data definition has no type or storage class
31_i2c_driver);

codecs/rt5631.c:1737:1: error: type defaults to 'int' in declaration of 'module_i2c_driver' [-Werror=implicit-int]
codecs/rt5631.c:1737:1: warning: parameter names (without types) in function declaration
codecs/rt5631.c:1726:26: warning: 'rt5631_i2c_driver' defined but not used [-Wunused-variable]

The same thing can happen on odroid-x2, littlemill, bells
and speyside, so this patch adds all the dependencies.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>