ARM: davinci: avoid unused mityomapl138_pn_info variable
mach-davinci/board-mityomapl138.c:59:28: error: 'mityomapl138_pn_info' defined but not used [-Werror=unused-variable]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>