panasonic-laptop: replace ACPI_DEBUG with dev_err
The driver uses the ACPI_DB_ERROR debug type that was removed
a while ago, so it won't build when ACPI debugging is enabled,
and it doesn't print any error indication when it's turned off.

Error messages may look like

In file included from ../include/linux/kernel.h:13:0,
                 from ../drivers/platform/x86/panasonic-laptop.c:119:
../drivers/platform/x86/panasonic-laptop.c: In function ‘acpi_pcc_get_sqty’:
../include/linux/printk.h:114:3: error: too few arguments to function ‘printk’
   printk(fmt, ##__VA_ARGS__); \
   ^
../include/acpi/acoutput.h:460:31: note: in expansion of macro ‘__ACPI_DEBUG_PRINT’
 #define ACPI_DEBUG_PRINT(pl)  __ACPI_DEBUG_PRINT pl
                               ^
../drivers/platform/x86/panasonic-laptop.c:266:3: note: in expansion of macro ‘ACPI_DEBUG_PRINT’
   ACPI_DEBUG_PRINT((ACPI_DB_ERROR,
   ^

This uses the more appropriate dev_err() macro to print information
about what went wrong in case it runs into a problem.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>