[SUBMITTED 20200429] pinctrl: mediatek: fix mtk_eint link error
In a configuration with CONFIG_PINCTRL_MTK_MOORE=y and CONFIG_PINCTRL_MTK_PARIS=m,
we end up with the mtk_eint driver as a loadable module that cannot be
linked from built-in code:

aarch64-linux-ld: drivers/pinctrl/mediatek/pinctrl-mtk-common-v2.o: in function `mtk_build_eint':
(.text+0x304): undefined reference to `mtk_eint_do_init'
aarch64-linux-ld: drivers/pinctrl/mediatek/pinctrl-moore.o: in function `mtk_gpio_set_config':
pinctrl-moore.c:(.text+0xf80): undefined reference to `mtk_eint_set_debounce'
aarch64-linux-ld: drivers/pinctrl/mediatek/pinctrl-moore.o: in function `mtk_gpio_to_irq':
pinctrl-moore.c:(.text+0x1028): undefined reference to `mtk_eint_find_irq'

Simplify the Kconfig logic to always select EINT_MTK when it is needed, and
remove the 'default' statements.

Fixes: 8174a8512e3e ("pinctrl: mediatek: make MediaTek pinctrl v2 driver ready for buidling loadable module")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>