[SUBMITTED 20211204] x86/efi: select ARCH_USE_MEMREMAP_PROT
The patch to map the EFI memmap as encrypted introduces a
link failure in configurations without encryption support:

x86_64-linux-ld: arch/x86/platform/efi/quirks.o: in function `efi_arch_mem_reserve':
quirks.c:(.init.text+0x127): undefined reference to `early_memremap_prot'

Select the necessary symbol here as well to fix the build.

Fixes: 8f1dd76c9b55 ("x86/sme: Explicitly map new EFI memmap table as encrypted")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>