[SUBMITTED 20231214] mips: fix r3k_cache_init build regression
My earlier patch removed __weak function declarations that used to
be turned into wild branches by the linker, instead causing
a link failure when the called functions are unavailable:

mips-linux-ld: arch/mips/mm/cache.o: in function `cpu_cache_init':
cache.c:(.text+0x670): undefined reference to `r3k_cache_init'

The __weak method seems suboptimal, so rather than putting that
back, make the function calls conditional on the Kconfig symbol
that controls the compilation.

Reported-by: kernelci.org bot <bot@kernelci.org>
Fixes: 66445677f01e ("mips: move cache declarations into header")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
My broken patch is currently in linux-mm, so the fix should
be applied on top.