kmsan: export kmsan_handle_dma
The virtio subsystem can be a loadable module, which now fails
to link with kmsan:

ERROR: modpost: "kmsan_handle_dma" [drivers/virtio/virtio_ring.ko] undefined!

Export this symbol to make it work again.

Fixes: 88938359e2df ("virtio: kmsan: check/unpoison scatterlist in vring_map_one_sg()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>