mfd: ab8500: remove duplicate table entries
gcc -Wextra finds two duplicate initializations for ab8500_debug_ranges:

drivers/mfd/ab8500-debugfs.c:466:11: error: initialized field overwritten [-Werror=override-init]
drivers/mfd/ab8500-debugfs.c:466:11: note: (near initialization for 'ab8500_debug_ranges[17]')
drivers/mfd/ab8500-debugfs.c:470:11: error: initialized field overwritten [-Werror=override-init]
drivers/mfd/ab8500-debugfs.c:470:11: note: (near initialization for 'ab8500_debug_ranges[18]')

In both cases, one initialization looks valid, the other one overrides
it with an empty one. I'm removing the empty overrides now, assuming
they were not intentional.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>