[SUBMITTED 20201204] soc/tegra: fix T234 build failure
In a T234-only configuration, the fuse driver fails to build:

drivers/soc/tegra/fuse/fuse-tegra30.c:376:10: error: 'tegra30_fuse_read' undeclared here (not in a function); did you mean 'tegra_fuse_readl'?

Add the missing check in the #ifdef conditional.

Fixes: 1f44febf71ba ("soc/tegra: fuse: Add Tegra234 support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>