ionic: use print_hex_dump_debug() instead of dynamic_hex_dump()
dynamic_hex_dump() is an internal helper that is only available
when CONFIG_DYNAMIC_DEBUG is enabled, without that we get a build
failure:

drivers/net/ethernet/pensando/ionic/ionic_rx_filter.c: In function 'ionic_rx_filter_replay':
drivers/net/ethernet/pensando/ionic/ionic_rx_filter.c:38:4: warning: implicit declaration of function 'dynamic_hex_dump' [-Wimplicit-function-declaration]
   38 |    dynamic_hex_dump("cmd ", DUMP_PREFIX_OFFSET, 16, 1,
      |    ^~~~~~~~~~~~~~~~

Use the official print_hex_dump_debug() interface instead, which
can become an empty stub or dynamic_hex_dump() depending on
configuration.

Fixes: 7e4d47596b68 ("ionic: replay filters after fw upgrade")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>