drm/bridge/sii8620: add extcon dependency
A built-in sii8620 driver cannot link against a modular extcon framework:

drivers/gpu/drm/bridge/sil-sii8620.o: In function `sii8620_remove':
sil-sii8620.c:(.text+0x294): undefined reference to `extcon_unregister_notifier'
drivers/gpu/drm/bridge/sil-sii8620.o: In function `sii8620_probe':
sil-sii8620.c:(.text+0x3370): undefined reference to `extcon_find_edev_by_node'
sil-sii8620.c:(.text+0x341c): undefined reference to `extcon_register_notifier'
drivers/gpu/drm/bridge/sil-sii8620.o: In function `sii8620_extcon_work':
sil-sii8620.c:(.text+0x3498): undefined reference to `extcon_get_state'

I assume that extcon is meant to be optional here, so instead of adding
a hard dependency, this allows to either build sii8620 without extcon disabled
or built-in, or to built it as a loadable module if extcon itself is a module.

Fixes: 688838442147 ("drm/bridge/sii8620: use micro-USB cable detection logic to detect MHL")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>