[SUBMITTED 20230927] accel/habanalabs: add missing debugfs function stubs
Two function stubs were removed in an earlier commit but are now needed
again:

drivers/accel/habanalabs/common/device.c: In function 'hl_device_init':
drivers/accel/habanalabs/common/device.c:2231:14: error: implicit declaration of function 'hl_debugfs_device_init'; did you mean 'drm_debugfs_dev_init'? [-Werror=implicit-function-declaration]
 2231 |         rc = hl_debugfs_device_init(hdev);
drivers/accel/habanalabs/common/device.c:2367:9: error: implicit declaration of function 'hl_debugfs_device_fini'; did you mean 'hl_debugfs_remove_file'? [-Werror=implicit-function-declaration]
 2367 |         hl_debugfs_device_fini(hdev);
      |         ^~~~~~~~~~~~~~~~~~~~~~

Fixes: 3b9abb4fa642e ("accel/habanalabs: expose debugfs files later")
Fixes: 09fe78d2e4421 ("accel/habanalabs: register compute device as an accel device")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>