[SUBMITTED 20210927] loop: avoid out-of-range warning
clang warns that the sanity check for page size always succeeds
when building with 64KB pages:

drivers/block/loop.c:282:27: error: result of comparison of constant 65536 with expression of type 'unsigned short' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
        if (bsize < 512 || bsize > PAGE_SIZE || !is_power_of_2(bsize))
                           ~~~~~ ^ ~~~~~~~~~

There is nothing wrong here, so just shut up the check by changing
the type of the bsize argument.

Fixes: 3448914e8cc5 ("loop: Add LOOP_CONFIGURE ioctl")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>