[SUBMITTED 20260216] drm/bridge: lontium-lt9611uxc: select CONFIG_DRM_DISPLAY_HDMI_AUDIO_HELPER
The audio helpers are now a dependency, causing the build to fail
when the Kconfig symbol is turned off:

lontium-lt9611uxc.o: in function `lt9611uxc_bridge_hpd_notify':
lontium-lt9611uxc.c:(.text+0x316): undefined reference to `drm_connector_hdmi_audio_plugged_notify'
lontium-lt9611uxc.c:(.text+0x332): undefined reference to `drm_connector_hdmi_audio_plugged_notify'
lontium-lt9611uxc.o: in function `lt9611uxc_bridge_hpd_notify':
lontium-lt9611uxc.c:(.text.lt9611uxc_bridge_hpd_notify+0x24): undefined reference to `drm_connector_hdmi_audio_plugged_notify'

Fixes: c08c123d4cd6 ("drm/bridge: lontium-lt9611uxc: switch to HDMI audio helpers")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>