ARM: disable OABI for COMPILE_TEST
A number of drivers fail to build with OABI because of its
unusual struct alignment rules:

drivers/scsi/advansys.c: In function 'AscSendScsiQueue':
drivers/scsi/advansys.c:3860:26: error: '*((void *)&scsi_sg_q+7)' may be used uninitialized in this function [-Werror=maybe-uninitialized]

inlined from 'init_xfs_fs' at /git/arm-soc/fs/xfs/xfs_super.c:1991:2:
fs/xfs/xfs_ondisk.h:119:208: error: call to '__compiletime_assert_119' declared with attribute error: XFS: sizeof(xfs_dir2_sf_entry_t) is wrong, expected 3

drivers/net/wireless/intel/ipw2x00/ipw2100.c: In function 'ipw2100_set_wpa_ie.constprop':
drivers/net/wireless/intel/ipw2x00/ipw2100.c:5154:2: error: 'memcpy' writing 404 bytes into a region of size 400 overflows the destination [-Werror=stringop-overflow=]

drivers/net/ethernet/intel/i40evf/i40e_adminq_cmd.h:315:32: error: division by zero [-Werror=div-by-zero]
  { i40e_static_assert_##X = (n)/((sizeof(struct X) == (n)) ? 1 : 0) }
drivers/net/ethernet/intel/i40evf/i40e_adminq_cmd.h:1684:1: note: in expansion of macro 'I40E_CHECK_STRUCT_LEN'

include/linux/avf/virtchnl.h:465:30: error: enumerator value for 'virtchnl_static_assert_virtchnl_rss_lut' is not an integer constant
 VIRTCHNL_CHECK_STRUCT_LEN(6, virtchnl_rss_lut);
                              ^
include/linux/avf/virtchnl.h:144:53: note: in definition of macro 'VIRTCHNL_CHECK_STRUCT_LEN'
  { virtchnl_static_assert_##X = (n)/((sizeof(struct X) == (n)) ? 1 : 0) }

In function 'smc_llc_add_pending_send',
    inlined from 'smc_llc_send_confirm_link' at /git/arm-soc/net/smc/smc_llc.c:82:5:
include/linux/compiler.h:560:38: error: call to '__compiletime_assert_63' declared with attribute error: must adapt SMC_WR_TX_SIZE to sizeof(struct smc_llc_msg); if not all smc_wr upper layer protocols use the same message size any more, must start to set link->wr_tx_sges[i].length on each individual smc_wr_tx_send()

drivers/staging/lustre/lustre/lov/lov_pack.c: In function 'lov_getstripe':
include/linux/compiler.h:560:38: error: call to '__compiletime_assert_352' declared with attribute error: BUILD_BUG_ON failed: sizeof(lum) != sizeof(struct lov_mds_md_v3)

drivers/vhost/vhost.c: In function 'vhost_vring_ioctl':
include/linux/compiler.h:560:38: error: call to '__compiletime_assert_1434' declared with attribute error: BUILD_BUG_ON failed: __alignof__ *vq->avail > VRING_AVAIL_ALIGN_SIZE

We could in theory fix those drivers to use packed structure and work
correctly with OABI, but I don't think it's worth the effort at this
point as many other drivers likely contain similar problems but
lack compile-time assertions for them.

There are probably other configurations that work fine with
OABI, so this leaves the option available but disables it whenever
we do compile-testing, to get it out of the picture of randconfig tests.

Note that gcc-4.7 deprecated support for the OABI based targets, and
they were removed with gcc-4.8 in 2015. The kernel still supports
running existing OABI binaries with CONFIG_OABI_COMPAT, and we can
still build the kernel itself for OABI with an EABI toolchain using
the -mabi=apcs-gnu compiler flag with the latest compilers.
As of commit 4f01ab7b8fd7 ("ARM: always enable AEABI for ARMv6+"),
we disallow OABI for ARMv6 and higher, as that led to many other
compile-time problems.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>