[HACK] ARM: omap2: mark unused functions as __maybe_unused
/git/arm-soc/arch/arm/mach-omap2/io.c:412:123: error: 'omap_hwmod_init_postsetup' defined but not used [-Werror=unused-function]
cc1: all warnings being treated as errors
make[3]: *** [arch/arm/mach-omap2/io.o] Error 1
/git/arm-soc/arch/arm/mach-omap2/board-generic.c:30:123: error: 'omap_generic_init' defined but not used [-Werror=unused-function]
cc1: all warnings being treated as errors
make[3]: *** [arch/arm/mach-omap2/board-generic.o] Error 1
make[3]: Target `__build' not remade because of errors.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>