[SUBMITTED 20210422] regulator: bd71815: include <linux/of.h> and <linux/gpio/consumer.h>
The new driver causes a build failure because of a missing includes:

drivers/regulator/bd71815-regulator.c: In function 'buck12_set_hw_dvs_levels':
drivers/regulator/bd71815-regulator.c:210:13: error: implicit declaration of function 'of_find_property' [-Werror=implicit-function-declaration]
  210 |         if (of_find_property(np, "rohm,dvs-run-voltage", NULL) ||
      |             ^~~~~~~~~~~~~~~~
drivers/regulator/bd71815-regulator.c: At top level:
drivers/regulator/bd71815-regulator.c:461:37: error: implicit declaration of function 'of_match_ptr' [-Werror=implicit-function-declaration]
  461 |                         .of_match = of_match_ptr(#_name),               \
      |                                     ^~~~~~~~~~~~
drivers/regulator/bd71815-regulator.c: In function 'bd7181x_probe':
drivers/regulator/bd71815-regulator.c:590:19: error: implicit declaration of function 'devm_gpiod_get_from_of_node' [-Werror=implicit-function-declaration]
  590 |         ldo4_en = devm_gpiod_get_from_of_node(&pdev->dev,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/regulator/bd71815-regulator.c:593:50: error: 'GPIOD_ASIS' undeclared (first use in this function); did you mean 'GPIOF_IN'?
  593 |                                                  GPIOD_ASIS, "ldo4-en");
      |                                                  ^~~~~~~~~~
      |                                                  GPIOF_IN

Fixes: 1aad39001e85 ("regulator: Support ROHM BD71815 regulators")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
As found yesterday with another patch I sent for this driver,
it is apparently not part of the regulator tree but only merged
through Lee's mfd tree.