[SUBMITTED 20231009] clk: imx: imx8: build base support for scu clk
There is now a dependency on a function from the clk.c file, so
this also needs to be built:

aarch64-linux-ld: Unexpected GOT/PLT entries detected!
aarch64-linux-ld: Unexpected run-time procedure linkages detected!
aarch64-linux-ld: drivers/clk/imx/clk-imx8-acm.o: in function `imx8_acm_clk_probe':
clk-imx8-acm.c:(.text+0xbf0): undefined reference to `imx_check_clk_hws'

Fixes: d3a0946d7ac9a ("clk: imx: imx8: add audio clock mux driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>