[SUBMITTED 20221215] reset: ti-sci: fix compile test dependencies
The SCI reset driver can be compile testing on targets that
do not support the SCI firmware, but it fails to link when
the firmware driver is built as a module, and the reset driver
is built-in:

arm-linux-gnueabi-ld: drivers/reset/reset-ti-sci.o: in function `ti_sci_reset_probe':
reset-ti-sci.c:(.text+0x422): undefined reference to `devm_ti_sci_get_handle'

Prevent this configuration by limiting the compile test
to configurations without SCI firmware.

Fixes: a6af504184c9 ("reset: ti-sci: Allow building under COMPILE_TEST")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>