x86/kaslr, ACPI/NUMA: avoid including asm/kaslr.h on arm64
Only x86 has an asm/kasrl.h file, so we now get a build failure on arm64:

drivers/acpi/numa.c:34:10: fatal error: asm/kaslr.h: No such file or directory

Adding an #ifdef around the header inclusion and the call to kaslr_check_padding
avoids the problem.

Fixes: 3a387c6d96e6 ("x86/kaslr, ACPI/NUMA: Fix KASLR build error")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>