[SUBMITTED 20210103] pldmfw: select CONFIG_CRC32
Without CRC32, pldmfw fails to link:

arm-linux-gnueabi-ld: lib/pldmfw/pldmfw.o: in function `pldmfw_flash_image':
(.text+0x1028): undefined reference to `crc32_le'

Fixes: b8265621f488 ("Add pldmfw library for PLDM firmware update")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>