[SUBMITTED] rtc: abx805 depends on i2c
The recently added X805 rtc driver uses the i2c subsystem,
but has no Kconfig dependency, so it can result in a build
error when i2c is disabled:

drivers/rtc/rtc-abx805.c: In function 'abx805_read_multiple_regs':
drivers/rtc/rtc-abx805.c:55:2: error: implicit declaration of function 'i2c_transfer' [-Werror=implicit-function-declaration]

This adds the obvious dependency.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 9033ab8ddd29 ("rtc: add rtc-abx805, a driver for the Abracon AB 1805 i2c rtc")
Cc: Philippe De Muyter <phdm@macqel.be>
Cc: Alessandro Zummo <a.zummo@towertech.it>
Cc: Andrew Morton <akpm@linux-foundation.org>