[SUBMITTED] NVMe: add explicit BLK_DEV_INTEGRITY dependency
A patch that was added to 4.0-rc1 in the last minute caused a
build break in the NVMe driver unless integrity support is
also enabled:

drivers/block/nvme-core.c: In function 'nvme_dif_remap':
drivers/block/nvme-core.c:523:24: error: dereferencing pointer to incomplete type
  pmap = kmap_atomic(bip->bip_vec->bv_page) + bip->bip_vec->bv_offset;
                        ^
drivers/block/nvme-core.c:523:49: error: dereferencing pointer to incomplete type
  pmap = kmap_atomic(bip->bip_vec->bv_page) + bip->bip_vec->bv_offset;
                                                 ^

This changes the Kconfig entry for NVMe to depend on that
support, to avoid the build error. Using 'select' would work
as well, but might have unintended side-effects when users
do not actually want the integerity support.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: e1e5e5641e6f ("NVMe: Metadata format support")