crypto: caam - avoid -Wnonnull warning on memcpy
The append_data() function already had a hack to prevent a sparse warning
when the 'len' argument is zero, but now gcc warns anyway when 'data'
is NULL, so add another check:

drivers/crypto/caam/desc_constr.h: In function 'append_data.constprop':
include/linux/fortify-string.h:57:33: error: argument 2 null where non-null expected [-Werror=nonnull]
   57 | #define __underlying_memcpy     __builtin_memcpy
      |                                 ^

Signed-off-by: Arnd Bergmann <arnd@arndb.de>