[SUBMITTED] cpufreq: qoriq depends on thermal
The thermal subsystem can be a loadable module, so the qoriq driver has to be
a module in that case as well in order to call of_cpufreq_cooling_register:

drivers/built-in.o: In function `qoriq_cpufreq_ready':
text+0x1f4548): undefined reference to `of_cpufreq_cooling_register'

This adds a dependency that clarifies how we can either build the driver
when the cpu_thermal support is completely disabled, or how it depends
on the thermal support to enforce the qoriq driver to be a module.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>