PM / Domains: add missing include to linux/pm.h
The newly added attach/detach API introduces a use of -ENODEV
in linux/pm.h, which can cause build errors:

In file included from arch/arm/mach-shmobile/cpuidle.c:11:0:
include/linux/pm.h: In function 'dev_pm_domain_attach':
include/linux/pm.h:631:10: error: 'ENODEV' undeclared (first use in this function)

This is easily solved by adding an include of linux/errno.h

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 46420dd73b80 ("PM / Domains: Add APIs to attach/detach a PM domain for a device")
Cc: linux-pm@vger.kernel.org
Cc: Ulf Hansson <ulf.hansson@linaro.org>
Cc: Philipp Zabel <p.zabel@pengutronix.de>
Cc: Kevin Hilman <khilman@linaro.org>
Cc: Dmitry Torokhov <dmitry.torokhov@gmail.com>
Cc: Rafael J. Wysocki <rafael.j.wysocki@intel.com>