[SUBMITTED] pcmcia: badge4: avoid unused function warning
The pcmv_setup is only used when the badge4 driver is built-in, but
not when it is a loadable module:

drivers/pcmcia/sa1111_badge4.c:153:122: error: 'pcmv_setup' defined but not used [-Werror=unused-function]

This adds an #ifdef to avoid the definition of the unused function
in the modular case.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>