[SUBMITTED 20210421] KVM: arm64: build perf support only when enabled
The perf_num_counters() function is only defined when CONFIG_PERF_EVENTS
is enabled:

arch/arm64/kvm/perf.c: In function 'kvm_perf_init':
arch/arm64/kvm/perf.c:58:43: error: implicit declaration of function 'perf_num_counters'; did you mean 'dec_mm_counter'? [-Werror=implicit-function-declaration]
   58 |         if (IS_ENABLED(CONFIG_ARM_PMU) && perf_num_counters() > 0
      |                                           ^~~~~~~~~~~~~~~~~

Use conditional compilation to disable this feature entirely when
CONFIG_PERF_EVENTS is disabled in the host.

Fixes: 6b5b368fccd7 ("KVM: arm64: Turn kvm_arm_support_pmu_v3() into a static key")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
Not sure if this is the correct symbol to check for, but this is
one way to avoid the build failure.