reiserfs: slightly shrink struct reiserfs_dir_entry
I'm trying to lower the stack frame warning limit when CONFIG_KASAN is enabled,
and one of the remaining corner cases is reiserfs, using slightly more than the
1536 byte limit I'm aiming for:

fs/reiserfs/namei.c:1643:1: error: the frame size of 1568 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]

I could not find a good way to reorganize the code to use significantly less
stack, but a very simple of change to struct reiserfs_dir_entry manages to
shrink this stack frame by 96 bytes, which is enough to shut up the warning
and use a little less memory in a couple of other places.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>