[SUBMITTED 20160701] drm/tegra: add missing include
A newly merged patch to configure the XBAR caused a build failure
in some configurations:

drivers/gpu/drm/tegra/sor.c: In function 'tegra_sor_set_pinmux':
drivers/gpu/drm/tegra/sor.c:252:10: error: implicit declaration of function 'pinctrl_lookup_state' [-Werror=implicit-function-declaration]
  state = pinctrl_lookup_state(sor->pinctrl, name);
          ^~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/tegra/sor.c:252:8: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
  state = pinctrl_lookup_state(sor->pinctrl, name);

The functions are declared in linux/pinctrl/consumer.h, so we need
to include that file instead of relying on the inclusion to happen
through another header.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 9e9d1315f4f4 ("drm/tegra: sor: Make XBAR configurable per SoC")