[SUBMITTED] tracing: fix missing osnoise tracer on max_latency
The compiler warns when the data are actually unused:

  kernel/trace/trace.c:1712:13: error: ‘trace_create_maxlat_file’ defined but not used [-Werror=unused-function]
   1712 | static void trace_create_maxlat_file(struct trace_array *tr,
        |             ^~~~~~~~~~~~~~~~~~~~~~~~

[Why]
CONFIG_HWLAT_TRACER=n, CONFIG_TRACER_MAX_TRACE=n, CONFIG_OSNOISE_TRACER=y
gcc report warns.

[How]
Now trace_create_maxlat_file will only take effect when
CONFIG_HWLAT_TRACER=y or CONFIG_TRACER_MAX_TRACE=y. In fact, after
adding osnoise trace, it also needs to take effect.

Fixes: bce29ac9ce0b ("trace: Add osnoise tracer")
Suggested-by: Steven Rostedt <rostedt@goodmis.org>
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Daniel Bristot de Oliveira <bristot@kernel.org>
Cc: Daniel Bristot de Oliveira <bristot@redhat.com>
Link: https://lore.kernel.org/all/20210922025122.3268022-1-liu.yun@linux.dev/
Signed-off-by: Arnd Bergmann <arnd@arndb.de>