[SUBMITTED 20210920] ASoC: mediatek: mt8195: force COMMON_CLK dependency
Without CONFIG_COMMON_CLK, this driver fails to link:

ERROR: modpost: "clk_unregister_gate" [sound/soc/mediatek/mt8195/snd-soc-mt8195-afe.ko] undefined!
ERROR: modpost: "clk_register_gate" [sound/soc/mediatek/mt8195/snd-soc-mt8195-afe.ko] undefined!

Add the proper Kconfig dependency for compile testing.

Fixes: 6746cc858259 ("ASoC: mediatek: mt8195: add platform driver")
Fixes: 940ffa194547 ("ASoC: mediatek: SND_SOC_MT8195 should depend on ARCH_MEDIATEK")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>