staging: vt665x: fix more alignment constraints
gcc still warns for two structures that I did not catch
the first time around, so it seems the same fix as before is needed:

drivers/staging/vt6655/rxtx.h:153:1: error: alignment 1 of 'struct vnt_cts' is less than 2 [-Werror=packed-not-aligned]
drivers/staging/vt6655/rxtx.h:163:1: error: alignment 1 of 'struct vnt_cts_fb' is less than 2 [-Werror=packed-not-aligned]

Fixes: 2faf12c57efe ("staging: vt665x: fix alignment constraints")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>