[SUBMITTED] leds: ipaq needs LEDS_CLASS
All other drivers have a dependency on this already, but this one
does not, which can lead to a link error when LEDS_CLASS is not set.

drivers/built-in.o: In function `micro_leds_remove':
:(.text+0x13d1bc): undefined reference to `led_classdev_unregister'
drivers/built-in.o: In function `micro_leds_probe':
:(.text+0x13d3d0): undefined reference to `led_classdev_register'

This patch adds the missing dependency.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Linus Walleij <linus.walleij@linaro.org>