platform/x86: dell: fix fix DELL_WMI_PRIVACY again
The previous fix made it possible to build DELL_WMI_PRIVACY when both
DELL_WMI and LEDS_TRIGGER_AUDIO are both disabled, but this breaks
building DELL_LAPTOP:

x86_64-linux-ld: drivers/platform/x86/dell/dell-laptop.o: in function `dell_init':
dell-laptop.c:(.init.text+0xad6): undefined reference to `dell_privacy_has_mic_mute'

Add back the explicit dependency on DELL_WMI, using an ifdef block
around all the DELL_WMI sub-options.

Fixes: 5b72dafaca73 ("platform/x86: dell: fix DELL_WMI_PRIVACY dependencies & build error")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>