[SUBMITTED] ASoC: omap: fix up SND_OMAP_SOC_OMAP_ABE_TWL6040 dependency
The change to enable OMAP5 support on this platform was a little too
eager in adding a 'select' for a particular clock driver that might
not be enabled in all configurations, which in turn leads to a build
error:

warning: (SND_OMAP_SOC_OMAP_ABE_TWL6040) selects COMMON_CLK_PALMAS which has unmet direct dependencies (COMMON_CLK && MFD_PALMAS)
drivers/built-in.o: In function `palmas_clks_probe':
drivers/clk/clk-palmas.c:228: undefined reference to `palmas_ext_control_req_config'

I do not see a strong dependency here, so it's probably better to
drop this select and to avoid adding more complexity here.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 5163c1eede8e9 ("ASoC: omap: Kconfig: Support for omap5-uevm analog audio")