[SUBMITTED 20210323] ARM: vexpress: spc: fix uniprocessor initialization
When CONFIG_SMP is disabled, topology_physical_package_id()
returns -1 and gcc notices undefined behavior:

arch/arm/mach-versatile/spc.c: In function 've_spc_clk_init':
arch/arm/mach-versatile/spc.c:583:21: error: array subscript -1 is below array bounds of 'bool[2]' {aka '_Bool[2]'} [-Werror=array-bounds]
  583 |   if (init_opp_table[cluster])
      |       ~~~~~~~~~~~~~~^~~~~~~~~
arch/arm/mach-versatile/spc.c:556:7: note: while referencing 'init_opp_table'
  556 |  bool init_opp_table[MAX_CLUSTERS] = { false };
      |       ^~~~~~~~~~~~~~

It's not clear to me what the correct behavior should be, but
it seems safe to just not continue with the initialization.

Fixes: 2a76352ad2cc ("ARM: vexpress: Set-up shared OPP table instead of individual for each CPU")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>