[SUBMITTED 20210723] gpu: host1x: select CONFIG_SYNC_FILE
With the addition of the DMA fence, the host1x driver now fails to
build without the sync_file helper:

arm-linux-gnueabi-ld: drivers/gpu/host1x/fence.o: in function `host1x_fence_create_fd':
fence.c:(.text+0x624): undefined reference to `sync_file_create'

Fixes: ad0529424def ("gpu: host1x: Add DMA fence implementation")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>