[SUBMITTED 20170324] staging: media: atomisp: remove ifdef around HMM_BO_ION
The revert reintroduced a build failure without CONFIG_ION:

media/atomisp/pci/atomisp2/hmm/hmm.c:52:2: error: excess elements in array initializer [-Werror]
media/atomisp/pci/atomisp2/hmm/hmm.c:52:2: note: (near initialization for 'hmm_bo_type_strings')

We should really be able to build in any configuration, so this tries a
different fix to make sure the symbol is defined.

Fixes: 9ca98bd07748 ("Revert "staging: media: atomisp: fill properly hmm_bo_type_strings when ION is disabled"")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>