ceph: fix building without debugfs
With CONFIG_DEBUG_FS disabled, we get a build warning:

fs/ceph/debugfs.c:297:2: error: void function 'ceph_fs_debugfs_init' should not return a value [-Wreturn-type]
        return 0;

Remove the extraneous return statement.

Fixes: 1a829ff2a6c3 ("ceph: no need to check return value of debugfs_create functions")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>