zstd: avoid clang -Wbitwise warning
clang-14 points to an unusual use of '&' on boolean values:

lib/zstd/decompress/huf_decompress.c:890:25: error: use of bitwise '&' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
                        (BIT_reloadDStreamFast(&bitD1) == BIT_DStream_unfinished)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In this case it was clearly intentional, but it can be written the
same way as all the other instances in this file to avoid the warning.

Fixes: ecea7adad80d ("lib: zstd: Upgrade to latest upstream zstd version 1.4.10")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>