[SUBMITTED 8372] ARM: KGDB does not build on BE32
KGDB requires code patching, which only works on little-endian
or newer big-endian (BE8) machines but not on the older big-endian
ones (BE32) where it results in this build error:

arch/arm/kernel/patch.c: In function '__patch_text_real':
arch/arm/kernel/patch.c:93:4: error: implicit declaration of function '__opcode_to_mem_thumb32' [-Werror=implicit-function-declaration]
    insn = __opcode_to_mem_thumb32(insn);

This adds a Kconfig dependency to avoid the broken case and
for all other symbols that require code patching.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 23a4e4050ba9 ("arm: kgdb: Handle read-only text / modules")