[3.16-stable] iio: fix printk format string warning
On 3.16, we get this warning:

drivers/iio/industrialio-core.c: In function 'iio_format_value':
drivers/iio/industrialio-core.c:408:30: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'long int' [-Werror=format=]

Upstream commit 8f57e4d930d4 ("include/linux/kernel.h: change abs() macro
so it uses consistent return type") addressed this in a more verbose
way, but here we can simply add a type cast to shut up the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>