[SUBMITTED 20190322] bitrev: fix constant bitrev
clang points out with hundreds of warnings that the bitrev macros
have a problem with constant input:

drivers/hwmon/sht15.c:187:11: error: variable '__x' is uninitialized when used within its own initialization
      [-Werror,-Wuninitialized]
        u8 crc = bitrev8(data->val_status & 0x0F);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/linux/bitrev.h:102:21: note: expanded from macro 'bitrev8'
        __constant_bitrev8(__x) :                       \
        ~~~~~~~~~~~~~~~~~~~^~~~
include/linux/bitrev.h:67:11: note: expanded from macro '__constant_bitrev8'
        u8 __x = x;                     \
           ~~~   ^

Both the bitrev and the __constant_bitrev macros use an internal variable
named __x, which goes horribly wrong when passing one to the other.

The obvious fix is to rename one of the variables, so this adds an
extra '_'.

It seems we got away with this because
- there are only a few drivers using bitrev macros
- usually there are no constant arguments to those
- when they are constant, they tend to be either 0 or (unsigned)-1
  (drivers/isdn/i4l/isdnhdlc.o, drivers/iio/amplifiers/ad8366.c)
  and give the correct result by pure chance.

In fact, the only driver that I could find that gets different results
with this is drivers/net/wan/slic_ds26522.c, which in turn is a driver
for fairly rare hardware (adding the maintainer to Cc for testing).

Cc: Zhao Qiang <qiang.zhao@nxp.com>
Cc: Yalin Wang <yalin.wang@sonymobile.com>
Cc: stable@vger.kernel.org
Fixes: 556d2f055bf6 ("ARM: 8187/1: add CONFIG_HAVE_ARCH_BITREVERSE to support rbit instruction")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>