[SUBMITTED 20170201] random: move random_min_urandom_seed into #ifdef
It is now only used if CONFIG_SYSCTL is enabled, and otherwise causes a warning:

drivers/char/random.c:318:12: error: 'random_min_urandom_seed' defined but not used [-Werror=unused-variable]

This moves it into the #ifdef that contains its only user.

Fixes: 43d8a72cd985 ("random: remove variable limit")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>