[SUBMITTED 20230214] Input: mainstone: fix pxa2xx_ac97 dependency
The exported PXA AC97 symbols are provided by the snd-pxa2xx-lib module
if SND_PXA2XX_SOC_AC97 is set, so both symbols have to be enabled for
the mainstone driver to actually work, and if snd-pxa2xx-lib is a loadable
module, the touchscreen driver cannot be built-in:

arm-linux-gnueabi-ld: drivers/input/touchscreen/mainstone-wm97xx.o: in function `wm97xx_acc_pen_up':
mainstone-wm97xx.c:(.text+0x8c): undefined reference to `pxa2xx_ac97_read_modr'
arm-linux-gnueabi-ld: drivers/input/touchscreen/mainstone-wm97xx.o: in function `wm97xx_acc_pen_down':
mainstone-wm97xx.c:(.text+0x2e0): undefined reference to `pxa2xx_ac97_read_modr'

The misconfiguration has always been possible but I never hit this after
my previous incomplete fix in 2019: since there were many options that
each 'select SND_PXA2XX_SOC_AC97', randconfig builds for PXA would almost
always have this built-in, not in a loadable module.

Fixes: e217b085a1ac ("Input: touchscreen: use wrapper for pxa2xx ac97 registers")
Fixes: b401d1fd8053 ("ASoC: pxa: remove unused board support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>