iommu: amd: fix function declarations
The amdkdf and events implementations both have headers with function
declarations that do not match the definition in the actual driver,
which is generally a bad idea and prevents a build with LTO enabled:

drivers/gpu/drm/amd/amdkfd/kfd_topology.h:187:0: error: type of 'amd_iommu_pc_get_max_banks' does not match original declaration [-Werror=lto-type-mismatch]
 extern u8 amd_iommu_pc_get_max_banks(u16 devid);

drivers/iommu/amd_iommu_init.c:2961:0: note: type mismatch in parameter 1
 u8 amd_iommu_pc_get_max_banks(unsigned int idx)

drivers/iommu/amd_iommu_init.c:2961:0: note: type 'unsigned int' should match type 'u16'
include/asm-generic/int-ll64.h:20:24: note: the incompatible type is defined here
 typedef unsigned short u16;
                        ^
drivers/iommu/amd_iommu_init.c:2961:0: note: 'amd_iommu_pc_get_max_banks' was previously declared here
 u8 amd_iommu_pc_get_max_banks(unsigned int idx)

drivers/iommu/amd_iommu_init.c:2961:0: note: code may be misoptimized unless -fno-strict-aliasing is used

This moves all those declaration out of the header files into the existing
linux/amd-iommu.h file. Since arch/x86/events/amd/iommu.h is otherwise
almost empty and only used in one place, I also move the rest of the
file into the driver using it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>