[SUBMITTED 20170710] staging: rtl8192u: reduce stack frame size in ieee80211_rx_mgt_rsl
I ran into a stack frame size warning in code that hasn't changed much
recently, no idea why I didn't spot this earlier despite build many
thousand randconfigs.

drivers/staging/rtl8192u/ieee80211/ieee80211_rx.c: In function 'ieee80211_rx_mgt_rsl':
drivers/staging/rtl8192u/ieee80211/ieee80211_rx.c:2563:1: error: the frame size of 1676 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

We have a couple of other copies of the same function in the kernel,
and they simply don't put a gigantic structure on the stack, so I'm
changing this copy to do the same as the others, replacing the
stack variable with a GFP_ATOMIC allocation.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
This one is not important, as it only seems to show up in rare
configurations. I'd suggest adding it to staging-next for 4.14
after the merge window.

v2: fix missing kfree() as pointed out by Dan Carpenter.