[SUBMITTED 20210802] switchdev: add Kconfig dependencies for bridge
Multiple switchdev drivers depend on CONFIG_NET_SWITCHDEV in Kconfig,
but have also gained a dependency on the bridge driver as they now
call switchdev_bridge_port_offload():

drivers/net/ethernet/microchip/sparx5/sparx5_switchdev.o: In function `sparx5_netdevice_event':
sparx5_switchdev.c:(.text+0x3cc): undefined reference to `switchdev_bridge_port_offload'
drivers/net/ethernet/ti/cpsw_new.o: In function `cpsw_netdevice_event':
cpsw_new.c:(.text+0x1098): undefined reference to `switchdev_bridge_port_offload'

Some of these drivers already have a 'BRIDGE || !BRIDGE' dependency
that avoids the link failure, but the 'rocker' driver was missing this

For MLXSW/MLX5, SPARX5_SWITCH, and TI_K3_AM65_CPSW_NUSS, the
driver can conditionally use switchdev support, which is then guarded
by another Kconfig symbol. For these, add a dependency on a new Kconfig
symbol NET_MAY_USE_SWITCHDEV that is defined to correctly model the
dependency: if switchdev support is enabled, these drivers cannot be
built-in when bridge support is in a module, but if either bridge or
switchdev is disabled, or both are built-in, there is no such restriction.

Fixes: 2f5dc00f7a3e ("net: bridge: switchdev: let drivers inform which bridge ports are offloaded")
Fixes: b0e81817629a ("net: build all switchdev drivers as modules when the bridge is a module")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
This version seems to pass my randconfig builds for the moment,
but that doesn't mean it's correct either. Please have a closer
look before this gets applied.