mm/memfd: avoid unused variable warning
The 'ns' variable was introduced in a recent patch, but
the only user is in an #ifdef, so the declaration needs the
same check to avoid

mm/memfd.c:280:24: error: unused variable 'ns' [-Werror,-Wunused-variable]

Fixes: ba59f107773a ("mm/memfd: add MFD_NOEXEC_SEAL and MFD_EXEC")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>