[SUBMITTED 20260202] pinctrl: polarfire: restore GENERIC_PINCONF dependency
Changing over to the new CONFIG_GENERIC_PINCTRL dropped the GENERIC_PINCONF
option, causing a build failure:

WARNING: unmet direct dependencies detected for GENERIC_PINCTRL
  Depends on [n]: PINCTRL [=y] && GENERIC_PINCONF [=y] && GENERIC_PINCTRL_GROUPS [=n] && GENERIC_PINMUX_FUNCTIONS [=n]
  Selected by [y]:
  - PINCTRL_POLARFIRE_SOC [=y] && PINCTRL [=y] && (ARCH_MICROCHIP [=y] || COMPILE_TEST [=y]) && OF [=y]
drivers/pinctrl/microchip/pinctrl-mpfs-mssio.c:296:29: error: 'pinctrl_generic_get_group_count' undeclared here (not in a function)
  296 |         .get_groups_count = pinctrl_generic_get_group_count,
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Select both GENERIC_PINCTRL and GENERIC_PINCONF to address this.

Fixes: 488d704ed7b7 ("pinctrl: add polarfire soc mssio pinctrl driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>