scsi: devinfo: rework scsi_strcpy_devinfo()
scsi_strcpy_devinfo() appears to work as intended but its semantics are
so confusing that gcc warns about it when -Wstringop-truncation is enabled:

In function 'scsi_strcpy_devinfo',
    inlined from 'scsi_dev_info_list_add_keyed' at drivers/scsi/scsi_devinfo.c:370:2:
drivers/scsi/scsi_devinfo.c:297:9: error: 'strncpy' specified bound 16 equals destination size [-Werror=stringop-truncation]
  297 |         strncpy(to, from, to_length);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Reorganize the function to completely separate the nul-terminated from
the space-padded/non-terminated case. The former is just strscpy_pad(),
while the latter does not have a standard function.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>