[SUBMITTED 20190325] lockdep: avoid bogus clang warning
When lockdep is enabled, and -Wuninitialized warnings are enabled,
clang produces a silly warning for every file we compile:

In file included from  kernel/sched/fair.c:23:
 kernel/sched/sched.h:1094:15: error: variable 'cookie' is uninitialized when used here [-Werror,-Wuninitialized]
        rf->cookie = lockdep_pin_lock(&rq->lock);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
 include/linux/lockdep.h:474:60: note: expanded from macro 'lockdep_pin_lock'
 #define lockdep_pin_lock(l)                     ({ struct pin_cookie cookie; cookie; })
                                                                             ^~~~~~
 kernel/sched/sched.h:1094:15: note: variable 'cookie' is declared here
 include/linux/lockdep.h:474:34: note: expanded from macro 'lockdep_pin_lock'
 #define lockdep_pin_lock(l)                     ({ struct pin_cookie cookie; cookie; })
                                                   ^
As the 'struct pin_cookie' structure is empty in this configuration,
there is no need to initialize it for correctness, but it also
does not hurt to set it to an empty structure, so do that to
avoid the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>