[UNDER REVIEW] ARM: fix copypage-*.c building with clang
clang does not allow inline assembly in __naked functions to
have any register parameters and throws an error:

arch/arm/mm/copypage-v4wb.c:47:9: error: parameter references not allowed in naked functions
        : "r" (kto), "r" (kfrom), "I" (PAGE_SIZE / 64));

Fortunately, all of these functions are trivial to convert to
using the registers directly.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Nicolas Pitre <nico@linaro.org>