mlxbf-bootctl: open-code sysfs_format_mac() for CONFIG_NET dependency
sysfs_format_mac() can only be called when networking is enabled, so
randconfig builds can run into a link failure with mlxbf-bootctl
after the latest sysfs additions:

aarch64-linux/bin/aarch64-linux-ld: drivers/platform/mellanox/mlxbf-bootctl.o: in function `oob_mac_show':
mlxbf-bootctl.c:(.text+0x152c): undefined reference to `sysfs_format_mac'

This could be solved by adding a CONFIG_NET dependency for this driver,
but since sysfs_format_mac() is just a trivial wrapper around
sysfs_emit(), it seems easier to just call that directly.

Fixes: 7e38a7422f128 ("mlxbf-bootctl: Support sysfs entries for MFG fields")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>