[SUPERCEDED] mtk_star_emac: avoid uninitialized variable use
clang points out the use of an uninitialized variable in the error path:

drivers/net/ethernet/mediatek/mtk_star_emac.c:1296:6: error: variable 'new_dma_addr' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
        if (!new_skb) {
            ^~~~~~~~
drivers/net/ethernet/mediatek/mtk_star_emac.c:1321:23: note: uninitialized use occurs here
        desc_data.dma_addr = new_dma_addr;
                             ^~~~~~~~~~~~

Change the error path to set the dma address to zero explicitly.

Fixes: 8c7bd5a454ff ("net: ethernet: mtk-star-emac: new driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>