[HACK] sfc
/home/arnd/arm-soc/drivers/net/ethernet/sfc/falcon/selftest.c:45:16: error: field ip within 'struct ef4_loopback_payload::(unnamed at /home/arnd/arm-soc/drivers/net/ethernet/sfc/falcon/selftest.c:43:2)' is less aligned than 'struct iphdr' and is usually due to 'struct ef4_loopback_payload::(unnamed at /home/arnd/arm-soc/drivers/net/ethernet/sfc/falcon/selftest.c:43:2)' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
2 errors generated.
make[9]: *** [/home/arnd/arm-soc/scripts/Makefile.build:243: drivers/net/ethernet/sfc/falcon/selftest.o] Error 1
make[9]: Target 'drivers/net/ethernet/sfc/falcon/' not remade because of errors.
make[8]: *** [/home/arnd/arm-soc/scripts/Makefile.build:480: drivers/net/ethernet/sfc/falcon] Error 2
/home/arnd/arm-soc/drivers/net/ethernet/sfc/selftest.c:47:16: error: field ip within 'struct efx_loopback_payload::(anonymous at /home/arnd/arm-soc/drivers/net/ethernet/sfc/selftest.c:45:2)' is less aligned than 'struct iphdr' and is usually due to 'struct efx_loopback_payload::(anonymous at /home/arnd/arm-soc/drivers/net/ethernet/sfc/selftest.c:45:2)' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
                struct iphdr ip;
                             ^
/home/arnd/arm-soc/drivers/net/ethernet/sfc/selftest.c:47:16: error: field ip within 'struct efx_loopback_payload::(unnamed at /home/arnd/arm-soc/drivers/net/ethernet/sfc/selftest.c:45:2)' is less aligned than 'struct iphdr' and is usually due to 'struct efx_loopback_payload::(unnamed at /home/arnd/arm-soc/drivers/net/ethernet/sfc/selftest.c:45:2)' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>