[media] MEDIA_TUNER_E4000 requires V4L2
The RTL28xxU driver tries to select the MEDIA_TUNER_E4000 option,
which itself has a dependency on VIDEO_V4L2, which leads to this
build error when V4L2 is disabled:

drivers/built-in.o: In function `e4000_remove':
:(.text+0x40211c): undefined reference to `v4l2_ctrl_handler_free'
drivers/built-in.o: In function `e4000_probe':
:(.text+0x402cf4): undefined reference to `v4l2_ctrl_handler_init_class'
:(.text+0x402d00): undefined reference to `v4l2_ctrl_new_std'
:(.text+0x402d1c): undefined reference to `v4l2_ctrl_auto_cluster'
:(.text+0x402d40): undefined reference to `v4l2_ctrl_handler_free'

We can easily avoid this problem by making that 'select' statement
conditional on VIDEO_V4L2 as well.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>