[RFC] Kconfig: disable -Wuninitialized for old compilers
gcc-4.8 has a lot of false positive warnings with -Wmaybe-uninitialized,
and we disable those already. However, older compilers have even more
such false-positive warnings, which clutter the build logs and are not
disabled because they don't understand the -Wno-maybe-uninitialized
flag.

This turns them off as well by disabling -Wuninitialized entirely
by default (unless 'make W=1' is used), significantly reducing the
total number of warnings, e.g. on current linux-next:

			before				after
		defconfig	allmodconfig	defconfig	allmodconfig
gcc-4.3		45		364		0		74
gcc-4.4		68		210		0		4
gcc-4.5		33		145		0		6
gcc-4.6		8		39		0		3
gcc-4.7		0		12		0		3

I have also submitted patches for the remaining warnings we get on
gcc-4.6+, so we should get a clean build at least for allmodconfig with
this patch. I have also looked at all 39 warnings we get with gcc-4.6 on
an allmodconfig build. 35 of them are false-positives that newer gccs
correctly understand and don't warn about. The remaining foud are also
false-positives, but I would expect gcc to warn about them anyway since
it cannot see why the code is safe:

drivers/media/platform/rcar_drif.c:658:2: error: ‘ret’ may be used uninitialized in this function [-Werror=uninitialized]
drivers/mtd/spi-nor/stm32-quadspi.c:248:2: error: ‘ret’ may be used uninitialized in this function [-Werror=uninitialized]
drivers/net/ethernet/mellanox/mlx5/core/fpga/sdk.c:147:6: error: ‘err’ may be used uninitialized in this function [-Werror=uninitialized]
drivers/net/ethernet/mellanox/mlx5/core/fpga/sdk.c:126:6: error: ‘err’ may be used uninitialized in this function [-Werror=uninitialized]

All four cases are for code that initializes a return code in a loop
that may be entered at all for invalid arguments (typically a counter).

Newer gcc and clang transform this so the return code of the function
becomes zero unless one loop iteration has failed earlier. The variable
holding the return code is optimized away before those warnings get
generated. In practice, those functions should never be called with a
zero loop counter, but I decided to submit patches for them anyway.
Presumably, smatch also detects all four as uninitialized variable uses,
but I did not try that.

Cc: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Dan Carpenter <dan.carpenter@oracle.com>
Link: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82203
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
Geert, you probably have an opinion on this, as you do build-testing
with gcc-4.1 and regularly report new warnings you get. I think
overall, we are better off without the false-positives here, and
we still get the regular warnings from newer compilers.

Would this patch get in your way?