[SUBMITTED 20180525] memory: tegra: include linux/spinlock.h
The newly added code in this file causes a build error unless
we include linux/spinlock.h, at least in some configurations:

In file included from drivers/memory/tegra/mc.h:15,
                 from drivers/memory/tegra/tegra20.c:11:
include/soc/tegra/mc.h:159:2: error: unknown type name 'spinlock_t'
  spinlock_t lock;
  ^~~~~~~~~~
drivers/memory/tegra/tegra20.c: In function 'terga20_mc_hotreset_assert':
drivers/memory/tegra/tegra20.c:207:2: error: implicit declaration of function 'spin_lock_irqsave'; did you mean 'arch_local_irq_save'? [-Werror=implicit-function-declaration]
  spin_lock_irqsave(&mc->lock, flags);
  ^~~~~~~~~~~~~~~~~

Fixes: cb557757e1aa ("memory: tegra: Add Tegra20 memory controller hot resets")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>