[SUBMITTED] printk: use C99 style varargs in no_printk
> -static inline __printf(1, 2)
> -int no_printk(const char *fmt, ...)
> -{
> -       return 0;
> -}
> +#define no_printk(fmt, ...)                    \
> +do {                                           \
> +       if (0) {                                \
> +               printk(fmt, ##__VA_ARGS__);     \
> +       }                                       \
> +} while (0)
>

This change breaks compiling lib/842/, at least in some configurations:

lib/842/842_decompress.c: In function '__do_index':
lib/842/842_decompress.c:205:12422: error: implicit declaration of function 'no_printk'

Using a gcc style vararg macro instead of the C99 style makes it work, but
I don't know why the original version didn't work.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 4005f13d472c ("printk: help pr_debug and pr_devel to optimize out arguments")