ARM: fix MPU build error after meminfo removal
I ran into a new build error while doing randconfig builds today,
which was introduced by 1c2f87c2256 ("ARM: 8025/1: Get rid of meminfo"):

arch/arm/mm/nommu.c: In function 'sanity_check_meminfo_mpu':
arch/arm/mm/nommu.c:147:26: error: 'aligned_round_size' undeclared (first use in this function)
     specified_mem_size - aligned_round_size);
                          ^
arch/arm/mm/nommu.c:147:26: note: each undeclared identifier is reported only once for each function it appears in
arch/arm/mm/nommu.c:90:6: warning: unused variable 'i' [-Wunused-variable]
  int i;
      ^
arch/arm/mm/nommu.c: In function 'mpu_setup':
arch/arm/mm/nommu.c:264:29: error: 'meminfo' undeclared (first use in this function)
      ilog2(meminfo.bank[0].size),
                             ^

It looks like three independent mistakes crept in after the patch
was originally written, and it never got tested again because nobody
uses the MPU. It's extremely rare for the randconfig builds to
run into this, otherwise I could have cought this earlier.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Jason Cooper <jason@lakedaemon.net>
Cc: Catalin Marinas <catalin.marinas@arm.com>
Cc: Santosh Shilimkar <santosh.shilimkar@ti.com>
Cc: Kukjin Kim <kgene.kim@samsung.com>
Cc: Marek Szyprowski <m.szyprowski@samsung.com>
Cc: Leif Lindholm <leif.lindholm@linaro.org>
Cc: Laura Abbott <lauraa@codeaurora.org>
Cc: Russell King <rmk+kernel@arm.linux.org.uk>