[SUBMITTED 20250305] mm/mremap: fix uninitialized return code
The 'err' variable is set in a conditinal branch and is not
set otherwise:

mm/mremap.c:1017:7: error: variable 'err' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
 1017 |                 if (vma->vm_start != old_addr)

Set it to zero before the initial value is set.

Fixes: 3129f7896afb ("mm/mremap: initial refactor of move_vma()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>