bcachefs: reduce bch_check_extent stack usage for kmsan
Enabling kmsan on current clang compilers leads to excessive stack usage
in a number of functions in fs/bcachefs/fsck.c:

fsck.c:1305:5: error: stack frame size (1000) exceeds limit (100) in 'bch2_check_inodes' [-Werror,-Wframe-larger-than]
fsck.c:1407:5: error: stack frame size (856) exceeds limit (100) in 'bch2_check_unreachable_inodes' [-Werror,-Wframe-larger-than]
fsck.c:1882:5: error: stack frame size (1424) exceeds limit (100) in 'bch2_check_extents' [-Werror,-Wframe-larger-than]
fsck.c:2315:5: error: stack frame size (1112) exceeds limit (100) in 'bch2_check_dirents' [-Werror,-Wframe-larger-than]
fsck.c:2731:5: error: stack frame size (1072) exceeds limit (100) in 'bch2_check_directory_structure' [-Werror,-Wframe-larger-than]
fsck.c:364:12: error: stack frame size (1048) exceeds limit (100) in 'reattach_inode' [-Werror,-Wframe-larger-than]

My best guess is that this problem is caused by a missed optimization when
compiling the bch2_trans_run(c, for_each_btree_key(...)) with kmsan,
though I have not tried to analyse it much beyond that.

The only one that is really high here is bch2_check_extents(), so work
around this one by marking its child functions as noinline_for_stack,
which seems to completely avoid the problem here.

The same thing could be done for the other users of the same construct,
but I skipped that to keep the change small.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>