resource: change min_t() to umin()
Commit 017fa3e89187 ("minmax: simplify and clarify min_t()/max_t()
implementation") introduced a warning on 32-bit Arm systems with a
32-bit resource_size_t, due to the MAX_PHYSMEM_BITS definition to 36
bit address spaces:

In file included from include/linux/ioport.h:15,
                 from kernel/resource.c:15:
kernel/resource.c: In function 'gfr_start':
include/linux/minmax.h:49:37: error: conversion from 'long long unsigned int' to 'resource_size_t' {aka 'unsigned int'} changes value from '68719476735' to '4294967295' [-Werror=overflow]
   49 |         ({ type ux = (x); type uy = (y); __cmp(op, ux, uy); })
      |                                     ^
kernel/resource.c:1829:23: note: in expansion of macro 'min_t'
 1829 |                 end = min_t(resource_size_t, base->end,
      |                       ^~~~~

Address this in arm specific code by lowering the maximum to
32 bit addressing in non-LPAE configurations that have the smaller
phys_addr_t/resource_size_t.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>