auditfilter: avoid missing braces warning
kernel/auditfilter.c: In function 'audit_data_to_entry':
kernel/auditfilter.c:580:3: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
   audit_remove_mark(entry->rule.exe); /* that's the template one */
   ^
kernel/auditfilter.c: In function 'audit_dupe_rule':
kernel/auditfilter.c:846:5: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
     audit_remove_mark(new->exe);
     ^
kernel/auditfilter.c: In function 'audit_del_rule':
kernel/auditfilter.c:1010:3: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
   audit_remove_mark_rule(&e->rule);
   ^
kernel/auditfilter.c: In function 'audit_rule_change':
kernel/auditfilter.c:1118:4: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
    audit_remove_mark(entry->rule.exe);
    ^
kernel/auditfilter.c: In function 'update_lsm_rule':
kernel/auditfilter.c:1413:3: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
   audit_remove_mark(entry->rule.exe);
   ^
cc1: all warnings being treated as errors

Signed-off-by: Arnd Bergmann <arnd@arndb.de>