ARM: omap1: h2: actually register gpiod lookup table
The conversion to gpio lookup was apparently incomplete:

arch/arm/mach-omap1/board-h2.c:345:34: error: unused variable 'isp1301_gpiod_table' [-Werror,-Wunused-variable]

Unless there is something else missing, adding the call to
gpiod_add_lookup_table() should fix both the compile-time warning and
finding the gpio at runtime.

Fixes: f3ef38160e3d ("usb: isp1301-omap: Convert to use GPIO descriptors")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>