[HACK] trace.c: avoid unused function warning
I have reported this but have not figured out the solution here

kernel/trace/trace.c:1712:13: error: 'trace_create_maxlat_file' defined but not used [-Werror=unused-function]
 1712 | static void trace_create_maxlat_file(struct trace_array *tr,

Signed-off-by: Arnd Bergmann <arnd@arndb.de>