[SUBMITTED 20210920] soc: samsung: exynos-pmu: select CONFIG_MFD_CORE
Using devm_mfd_add_devices() fails if no driver selects the
MFD core code:

aarch64-linux-ld: drivers/soc/samsung/exynos-pmu.o: in function `exynos_pmu_probe':
exynos-pmu.c:(.text+0xa0): undefined reference to `devm_mfd_add_devices'

Add the missing select statement.

Fixes: 93618e344a5e ("soc: samsung: exynos-pmu: instantiate clkout driver as MFD")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>