[SUBMITTED 20210723] ARM: imx: fix imx_mmdc_probe build failure
There are two definitions of imx_mmdc_probe(), the function just
gained a third argument, but the empty macro did not get changed
the same way:

arch/arm/mach-imx/mmdc.c: In function 'imx_mmdc_probe':
arch/arm/mach-imx/mmdc.c:575:63: error: macro "imx_mmdc_perf_init" passed 3 arguments, but takes just 2
  575 |         err = imx_mmdc_perf_init(pdev, mmdc_base, mmdc_ipg_clk);
      |                                                               ^
arch/arm/mach-imx/mmdc.c:537: note: macro "imx_mmdc_perf_init" defined here
  537 | #define imx_mmdc_perf_init(pdev, mmdc_base) 0
      |
arch/arm/mach-imx/mmdc.c:575:15: error: 'imx_mmdc_perf_init' undeclared (first use in this function)
  575 |         err = imx_mmdc_perf_init(pdev, mmdc_base, mmdc_ipg_clk);
      |               ^~~~~~~~~~~~~~~~~~

Fixes: f07ec8536580 ("ARM: imx: add missing clk_disable_unprepare()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>