serial: imx: fix earlycon dependencies again
With CONFIG_SERIAL_CORE=m, the previously added logic breaks down:

arm-linux-gnueabi-ld: drivers/tty/serial/imx_earlycon.o: in function `imx_uart_console_early_write':
imx_earlycon.c:(.text+0xc): undefined reference to `uart_console_write'
arm-linux-gnueabi-ld: drivers/tty/serial/earlycon.o: in function `parse_options':
earlycon.c:(.init.text+0x3f6): undefined reference to `uart_parse_earlycon'

Change the dependencies so the earlycon support can only be selected
when the console is built-in.

Fixes: 427627a23c3e ("tty: serial: imx: enable earlycon by default if IMX_SERIAL_CONSOLE is enabled")
Fixes: 699cc4dfd140 ("tty: serial: imx: add imx earlycon driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>