vdpa: build virtio-pci-lib even with CONFIG_VIRTIO=n
The new VP_VDPA support can be enabled even on kernels without normal
virtio support, but this causes a link failure because the library
code is not built here:

ERROR: modpost: "vp_modern_generation" [drivers/vdpa/virtio_pci/vp_vdpa.ko] undefined!
ERROR: modpost: "vp_modern_set_status" [drivers/vdpa/virtio_pci/vp_vdpa.ko] undefined!
ERROR: modpost: "vp_modern_config_vector" [drivers/vdpa/virtio_pci/vp_vdpa.ko] undefined!
ERROR: modpost: "vp_modern_queue_vector" [drivers/vdpa/virtio_pci/vp_vdpa.ko] undefined!
ERROR: modpost: "vp_modern_get_status" [drivers/vdpa/virtio_pci/vp_vdpa.ko] undefined!

Fix this by forcing Kbuild to enter the drivers/virtio directory
whenever VDPA is enabled.

Fixes: 010eee82c84e ("vdpa: introduce virtio pci driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>