[media] marvell-ccic: mmp-driver never worked
Building the Armada 610 camera driver always results in
lots of build errors:

marvell-ccic/mmp-driver.c: In function 'mmpcam_calc_dphy':
marvell-ccic/mmp-driver.c:252:15: error: 'struct mmp_camera_platform_data' has no member named 'dphy3_algo'
  switch (pdata->dphy3_algo) {
               ^
marvell-ccic/mmp-driver.c:253:7: error: 'DPHY3_ALGO_PXA910' undeclared (first use in this function)
  case DPHY3_ALGO_PXA910:
       ^
marvell-ccic/mmp-driver.c:253:7: note: each undeclared identifier is reported only once for each function it appears in
marvell-ccic/mmp-driver.c:257:8: error: 'struct mmp_camera_platform_data' has no member named 'dphy'
   pdata->dphy[0] =
        ^
marvell-ccic/mmp-driver.c:258:17: error: 'struct mmp_camera_platform_data' has no member named 'lane_clk'
    (((1 + (pdata->lane_clk * 80) / 1000) & 0xff) << 8)
                 ^
marvell-ccic/mmp-driver.c:261:7: error: 'DPHY3_ALGO_PXA2128' undeclared (first use in this function)
  case DPHY3_ALGO_PXA2128:
       ^
marvell-ccic/mmp-driver.c: In function 'mmpcam_probe':
marvell-ccic/mmp-driver.c:360:24: error: 'struct mmp_camera_platform_data' has no member named 'mclk_min'
  mcam->mclk_min = pdata->mclk_min;
                        ^
marvell-ccic/mmp-driver.c:361:24: error: 'struct mmp_camera_platform_data' has no member named 'mclk_src'
  mcam->mclk_src = pdata->mclk_src;
                        ^
marvell-ccic/mmp-driver.c:362:24: error: 'struct mmp_camera_platform_data' has no member named 'mclk_div'
  mcam->mclk_div = pdata->mclk_div;
                        ^
marvell-ccic/mmp-driver.c:363:24: error: 'struct mmp_camera_platform_data' has no member named 'bus_type'
  mcam->bus_type = pdata->bus_type;
                        ^
marvell-ccic/mmp-driver.c:364:20: error: 'struct mmp_camera_platform_data' has no member named 'dphy'
  mcam->dphy = pdata->dphy;
                    ^
marvell-ccic/mmp-driver.c:371:20: error: 'struct mmp_camera_platform_data' has no member named 'lane'
  mcam->lane = pdata->lane;

As far as I can tell, it has never worked upstream, and the driver
must have been tested with a different set up header files in some
private kernel repository.

This marks it as BROKEN, so we can keep building allmodconfig kernels when
MMP becomes part of that.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Libin Yang <lbyang@marvell.com>
Cc: Jonathan Corbet <corbet@lwn.net>
Cc: Hans Verkuil <hans.verkuil@cisco.com>
Cc: Mauro Carvalho Chehab <m.chehab@samsung.com>