[SUBMITTED 20240528] drm/amdkfd: select CONFIG_CRC16
The amdkfd support fails to link when CONFIG_CRC16 is disabled:

aarch64-linux-ld: drivers/gpu/drm/amd/amdkfd/kfd_topology.o: in function `kfd_topology_add_device':
kfd_topology.c:(.text+0x3a4c): undefined reference to `crc16'

This is a library module that needs to be selected from every user.

Fixes: 3ed181b8ff43 ("drm/amdkfd: Ensure gpu_id is unique")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>