drm: rcar-du: of: fix calling rcar_du_of_init
When CONFIG_RCAR_LVDS is a loadable module and

drivers/gpu/drm/rcar-du/rcar_du_of.c:320:13: error: redefinition of 'rcar_du_of_init'
 void __init rcar_du_of_init(const struct of_device_id *of_ids)
             ^~~~~~~~~~~~~~~
In file included from drivers/gpu/drm/rcar-du/rcar_du_of.c:21:
drivers/gpu/drm/rcar-du/rcar_du_of.h:17:20: note: previous definition of 'rcar_du_of_init' was here

Fixes: c18e9a098605 ("drm: rcar-du: of: Include header to define prototypes")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>