[SUBMITTED 20221215] regulator: tps65219: fix Wextra warning
gcc warns about an invalid pointer comparison when building with
-Wextra enabled:

drivers/regulator/tps65219-regulator.c: In function 'tps65219_regulator_probe':
drivers/regulator/tps65219-regulator.c:370:26: error: ordered comparison of pointer with integer zero [-Werror=extra]
  370 |                 if (rdev < 0) {
      |                          ^

It appears that the intention here was to check for an error code, rather
than the pointer, so adapt the code to propagate the error from the
called function instead.

Fixes: c12ac5fc3e0a ("regulator: drivers: Add TI TPS65219 PMIC regulators support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>