[SUBMITTED 20260204] [net-next] net/mlx5e: fix ip6_dst_lookup link failure
Changing mlx5 to call ip6_dst_lookup() means it now fails to link
when IPv6 is a loadable module but ipsec support is built-in:

ipsec.c:(.text+0x1061): undefined reference to `ip6_dst_lookup'

Add a Kconfig dependency that removes avoids this configuration.

Fixes: e35d7da8dd9e ("net/mlx5e: Use ip6_dst_lookup instead of ipv6_dst_lookup_flow for MAC init")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>