[SUBMITTED] rtc: ds1685: fix ds1685_rtc_alarm_irq_enable build error
The newly added ds1685 driver causes a build error in linux-next
when enabled without CONFIG_RTC_INTF_DEV:

drivers/rtc/rtc-ds1685.c:919:22: error: 'ds1685_rtc_alarm_irq_enable' undeclared here (not in a function)
  .alarm_irq_enable = ds1685_rtc_alarm_irq_enable,

Apparently the driver was incorrectly changed to reflect the interface
change from 16380c153a69c ("RTC: Convert rtc drivers to use the
alarm_irq_enable method"), which removed the respective #ifdef
from all other rtc drivers.

This does the same change that was merged for the other drivers
before and removes the #ifdef, allowing the interrupts to be
enabled through the in-kernel rtc interface independent of the
existence of /dev/rtc.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: aaaf5fbf56f ("rtc: add driver for DS1685 family of real time clocks")