[SUBMITTED 20260211] PCI: endpoint: pci-epf-test: select configfs
Like some of the other endpoint modules, this one now also
uses configfs, but is missing an indication in Kconfig:

arm-linux-gnueabi-ld: drivers/pci/endpoint/functions/pci-epf-test.o: in function `pci_epf_test_add_cfs':
pci-epf-test.c:(.text.pci_epf_test_add_cfs+0x2c): undefined reference to `config_group_init_type_name'

Select the symbol as needed.

Fixes: ffcc4850a161 ("PCI: endpoint: pci-epf-test: Allow overriding default BAR sizes")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>