net: microchip: sparx5: kunit: reduce stack usage further
drivers/net/ethernet/microchip/vcap/vcap_api_kunit.c: In function 'vcap_api_next_lookup_advanced_test':
drivers/net/ethernet/microchip/vcap/vcap_api_kunit.c:1996:1: error: the frame size of 1384 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Fixes: 129ff4de58ff ("net: microchip: sparx5: reduce stack usage")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>