[SUBMITTED 20250503] arm64/fpsimd: hide unused sve_to_fpsimd() function
The one caller outside of an #ifdef was removed:

arch/arm64/kernel/fpsimd.c:676:13: error: 'sve_to_fpsimd' defined but not used [-Werror=unused-function]
  676 | static void sve_to_fpsimd(struct task_struct *task)
      |             ^~~~~~~~~~~~~

Add annother #ifdef around the definition.

Fixes: 929fa99b1215 ("arm64/fpsimd: signal: Always save+flush state early")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>