[SUBMITTED] serial: digicolor: fix sysrq handling
Trying to build the digicolor-usart driver when sysrq is disabled
results in a compile error:

drivers/tty/serial/digicolor-usart.c: In function 'digicolor_uart_console_write':
drivers/tty/serial/digicolor-usart.c:407:33: error: 'struct uart_port' has no member named 'sysrq'

Like a lot of other drivers, this one requires an #ifdef to avoid
accessing the sysrq field here. While looking into this, I noticed
that the case where sysrq support is enabled is also broken, because
the driver fails to set the SUPPORT_SYSRQ macro.

This patch hopefully fixes both, but I do not hardware to test if sysrq
is actually working now.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>