ARM: imx: select ARM_CPU_SUSPEND for cpuidle
At the moment, we select ARM_CPU_SUSPEND from i.MX because it
gets called by some power management code, but we also need
it when CONFIG_PM is disabled and CONFIG_CPU_IDLE is turned on:

arch/arm/mach-imx/built-in.o: In function `imx6sx_enter_wait':
platform-imx-dma.c:(.text+0x1e8): undefined reference to `cpu_suspend'

This clarifies the dependency.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>