[SUBMITTED 20170329] initify: mark more functions __unverified_nocapture
These are from an overnight randconfig run:

drivers/acpi/acpica/utdebug.c: In function 'acpi_debug_print':
drivers/acpi/acpica/utdebug.c:158:1: error: 'acpi_debug_print' captures its 3 ('function_name') parameter, please remove it from the nocapture attribute. [-Werror]
 acpi_debug_print(u32 requested_debug_level,

fs/ntfs/debug.c: In function '__ntfs_warning':
fs/ntfs/debug.c:43:6: error: '__ntfs_warning' captures its 1 ('function') parameter, please remove it from the nocapture attribute. [-Werror]
 void __ntfs_warning(const char *function, const struct super_block *sb,
fs/ntfs/debug.c: In function '__ntfs_error':
fs/ntfs/debug.c:86:6: error: '__ntfs_error' captures its 1 ('function') parameter, please remove it from the nocapture attribute. [-Werror]
 void __ntfs_error(const char *function, const struct super_block *sb,
fs/ntfs/debug.c: In function '__ntfs_debug':
fs/ntfs/debug.c:115:6: error: '__ntfs_debug' captures its 3 ('function') parameter, please remove it from the nocapture attribute. [-Werror]
 void __ntfs_debug(const char *file, int line, const char *function,

kernel/audit.c: In function 'audit_log_n_string':
kernel/audit.c:1845:6: error: 'audit_log_n_string' captures its 2 ('string') parameter, please remove it from the nocapture attribute. [-Werror]
 void audit_log_n_string(struct audit_buffer *ab, const char *string,

kernel/panic.c: In function '__warn':
kernel/panic.c:515:6: error: '__warn' captures its 1 ('file') parameter, please remove it from the nocapture attribute. [-Werror]
 void __warn(const char *file, int line, void *caller, unsigned taint,
kernel/panic.c: In function '__warn':

mm/util.c: In function 'kstrdup':
mm/util.c:47:7: error: 'kstrdup' captures its 1 ('s') parameter, please remove it from the nocapture attribute. [-Werror]
 char *kstrdup(const char *s, gfp_t gfp)
mm/util.c: In function 'kstrndup':
mm/util.c:87:7: error: 'kstrndup' captures its 1 ('s') parameter, please remove it from the nocapture attribute. [-Werror]
 char *kstrndup(const char *s, size_t max, gfp_t gfp)
mm/util.c: In function 'kmemdup':
mm/util.c:112:7: error: 'kmemdup' captures its 1 ('src') parameter, please remove it from the nocapture attribute. [-Werror]
 void *kmemdup(const void *src, size_t len, gfp_t gfp)

lib/string.c: In function 'strlcpy':
lib/string.c:139:8: error: 'strlcpy' captures its 2 ('src') parameter, please remove it from the nocapture attribute. [-Werror]
 size_t strlcpy(char *dest, const char *src, size_t size)
lib/string.c: In function 'strlcat':
lib/string.c:294:8: error: 'strlcat' captures its 2 ('src') parameter, please remove it from the nocapture attribute. [-Werror]
 size_t strlcat(char *dest, const char *src, size_t count)
lib/string.c: In function 'strnstr':
lib/string.c:858:7: error: 'strnstr' captures its 1 ('s1') parameter, please remove it from the nocapture attribute. [-Werror]
 char *strnstr(const char *s1, const char *s2, size_t len)
lib/string.c: In function 'strnstr':
lib/string.c:858:33: error: 'strnstr' captures its 2 ('s2') parameter, please remove it from the nocapture attribute. [-Werror]
 __unverified_nocapture(1) char *strnstr(const char *s1, const char *s2, size_t len)
lib/string.c: In function 'check_bytes8':
lib/string.c:900:7: error: 'check_bytes8' captures its 1 ('start') parameter, please remove it from the nocapture attribute. [-Werror]
 void *check_bytes8(const u8 *start, u8 value, unsigned int bytes)
lib/string.c: In function 'memchr_inv':
lib/string.c:920:7: error: 'memchr_inv' captures its 1 ('start') parameter, please remove it from the nocapture attribute. [-Werror]
 void *memchr_inv(const void *start, int c, size_t bytes)

I blindly marked all instances as __unverified_nocapture() but did not
actually verify that this is correct. Please verify before folding the
patch into the previous one.

Fixes: 968375b64840 ("initify: Mark functions with the __unverified_nocapture attribute")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>