[SUBMITTED 20190722] [v3] xen: avoid link error on ARM
Building the privcmd code as a loadable module on ARM, we get
a link error due to the private cache management functions:

ERROR: "__sync_icache_dcache" [drivers/xen/xen-privcmd.ko] undefined!

Move the code into a new that is always built in when Xen is enabled,
as suggested by Juergen Gross and Boris Ostrovsky.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
v2: rename mm.o to xen-builtin.o, make it unconditional
v3: move new code into xlate_mmu as suggested by Boris Ostrovsky.
    sorry for the long delay since v2, I lost track of this.