wireless: avoid fortified-memcpy warnings on *_get_et_strings()
When building with W=1, the source data overrun check triggets on every
instance of the get_et_strings callbacks, because the entire array of
strings is copied but the source pointer only points to the first entry
in that array:

In file included from drivers/net/wireless/mediatek/mt76/mt7921/main.c:4:
In file included from include/linux/string.h:254:
include/linux/fortify-string.h:592:4: error: call to '__read_overflow2_field' declared with 'warning' attribute: detected read beyond size of field (2nd parameter); maybe use struct_group()? [-Werror,-Wattribute-warning]
                        __read_overflow2_field(q_size_field, size);

Change this to make the source pointer and the sizeof() argument operate
on the same object. The first instance of the code was added to mac80211
and copied to a lot of device drivers from there.

Fixes: b1ab79255c539 ("mac80211: Support getting sta_info stats via ethtool.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>