[SUBMITTED 20170710] ftrace: avoid unused-variable warning
When CONFIG_DYNAMIC_FTRACE is disabled, we get a harmless
compile-time warning:

kernel/trace/trace_stack.c: In function 'stack_trace_filter_open':
kernel/trace/trace_stack.c:412:21: error: unused variable 'ops' [-Werror=unused-variable]

We could replace the macros in linux/ftrace.h with inline functions,
which would solve this problem for all callers. However, as these
are only called internally in the ftrace code, it seems simpler
to change the caller instead.

Fixes: 0f17976568b3 ("ftrace: Fix regression with module command in stack_trace_filter")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>