caif: reduce stack usage further
An earlier patch of mine has reduced the stack usage of cfctrl_recv()
previously, but with gcc - 8, I still run into warnings:

net/caif/cfctrl.c: In function 'cfctrl_recv':
net/caif/cfctrl.c:549:1: error: the frame size of 1400 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Address this further by cleaning it up in multiple related ways:

- split out the CFCTRL_CMD_LINK_SETUP processing into its own function
  to better see where the stack usage is
- remove the 255 byte 'param' variable from the stack, this is
  never used after it gets filled by cfpkt_extr_head(), and that
  function can take a NULL pointer to the same effect.
- Remove the duplicate cfctrl_link_param structure from the stack
  and just the copy that is part of cfctrl_request_info.

Fixes: ce6289661b14 ("caif: reduce stack size with KASAN")
Fixes: b482cd2053e3 ("net-caif: add CAIF core protocol stack")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>