[SUBMITTED 20230421] ext4: avoid unused-variable warning with CONFIG_QUOTA=n
After some code reshuffling, the index variables in two functions
are only used in an #ifdef:

fs/ext4/super.c: In function 'ext4_put_super':
fs/ext4/super.c:1262:13: error: unused variable 'i' [-Werror=unused-variable]
fs/ext4/super.c: In function '__ext4_fill_super':
fs/ext4/super.c:5200:22: error: unused variable 'i' [-Werror=unused-variable]

Since all supported compilers now allow having variable declarations
inside of a for() loop, move them into the #ifdef block directly.

Fixes: dcbf87589d90 ("ext4: factor out ext4_flex_groups_free()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>