[UNDER DISCUSSION] [media] smiapp: mark PM functions as __maybe_unused
The functions are only referenced when CONFIG_PM_SLEEP is set, but
the #ifdef checks for CONFIG_PM:

media/i2c/smiapp/smiapp-core.c:1352:12: error: 'smiapp_power_off' defined but not used [-Werror=unused-function]
media/i2c/smiapp/smiapp-core.c:1206:12: error: 'smiapp_power_on' defined but not used [-Werror=unused-function]
media/i2c/smiapp/smiapp-core.c:2771:12: error: 'smiapp_resume' defined but not used [-Werror=unused-function]
media/i2c/smiapp/smiapp-core.c:2746:12: error: 'smiapp_suspend' defined but not used [-Werror=unused-function]

Removing the #ifdef entirely and marking the functions as __maybe_unused
simplifies this.

Fixes: 4ecc2d75c0c5 ("[media] smiapp: Set use suspend and resume ops for other functions")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>