[SUBMITTED 20210103] cxgb4: fix TLS dependencies again
A previous patch tried to avoid a build failure, but missed one case
that Kconfig warns about:

WARNING: unmet direct dependencies detected for CHELSIO_T4
  Depends on [m]: NETDEVICES [=y] && ETHERNET [=y] && NET_VENDOR_CHELSIO [=y] && PCI [=y] && (IPV6 [=y] || IPV6 [=y]=n) && (TLS [=m] || TLS [=m]=n)
  Selected by [y]:
  - SCSI_CXGB4_ISCSI [=y] && SCSI_LOWLEVEL [=y] && SCSI [=y] && PCI [=y] && INET [=y] && (IPV6 [=y] || IPV6 [=y]=n) && ETHERNET [=y]
x86_64-linux-ld: drivers/net/ethernet/chelsio/cxgb4/cxgb4_main.o: in function `cxgb_select_queue':
cxgb4_main.c:(.text+0xf5df): undefined reference to `tls_validate_xmit_skb'

When any of the dependencies of CHELSIO_T4 are not met, then
SCSI_CXGB4_ISCSI must not 'select' it either.

Fix it by mirroring the network driver dependencies on the iscsi
driver. A more invasive but also more reliable alternative would
be to use 'depends on CHELSIO_T4' instead.

Fixes: 659fbdcf2f14 ("cxgb4: Fix build failure when CONFIG_TLS=m")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>