[SUBMITTED] dvb: usb: fix dib3000mc dependencies
The dibusb_read_eeprom_byte function is defined in dibusb-common.c,
but that file is not compiled for CONFIG_DVB_USB_DIBUSB_MB as it
is for the other driver using the common functions, so we can
get a link error:

drivers/built-in.o: In function `dibusb_dib3000mc_tuner_attach':
(.text+0x2c5124): undefined reference to `dibusb_read_eeprom_byte'
(.text+0x2c5134): undefined reference to `dibusb_read_eeprom_byte'

This changes the Makefile to treat the file like all the others
in this directory, and enforce building dvb-usb-dibusb-common.o
as a dependency.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>