[SUBMITTED 20210920] [RFC] io_uring: warning about unused-but-set parameter
When enabling -Wunused warnings by building with W=1, I get an
instance of the -Wunused-but-set-parameter warning in the io_uring code:

fs/io_uring.c: In function 'io_queue_async_work':
fs/io_uring.c:1445:61: error: parameter 'locked' set but not used [-Werror=unused-but-set-parameter]
 1445 | static void io_queue_async_work(struct io_kiocb *req, bool *locked)
      |                                                       ~~~~~~^~~~~~

There are very few warnings of this type, so it would be nice to enable
this by default and fix all the existing instances. I was almost
done, but this was added recently as a precaution to prevent code
from using the parameter, which could be done by either removing
the initialization, or by adding a (fake) use of the variable, which
I do here with the cast to void.

Fixes: f237c30a5610 ("io_uring: batch task work locking")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>