[SUBMITTED 20200529] block: add 'struct gendisk' declaration
The added disk_start_io_acct() function declaration causes a warning
when CONFIG_BLOCK is disabled:

include/linux/blkdev.h:1895:41: error: declaration of 'struct gendisk' will not be visible outside of this function [-Werror,-Wvisibility]

Declare the struct tag before the function to suppress that warning.

Fixes: 956d510ee78c ("block: add disk/bio-based accounting helpers")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>