ARM: EFI: limit CONFIG_EFI to CPU_V7
EFI mandates ARMv7 or later, but so far we have allowed building
it for all architecture levels. With the latest patch to
randomize the base address, I ran into a build error on older
architectures:

drivers/firmware/efi/libstub/arm-stub.stub.o: In function `efi_entry':
arm-stub.c:(.text.efi_entry+0x334): undefined reference to `__aeabi_lmul'

This adds a Kconfig dependency to only allow EFI if CONFIG_CPU_V7
is set.

Fixes: e69176d68d26 ("ef/libstub/arm/arm64: Randomize the base of the UEFI rt services region")
Cc: Ard Biesheuvel <ard.biesheuvel@linaro.org>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>