ARM: imx: add missing include
imx25_pm_init() is declared in common.h but this is not included
before its definition:

arch/arm/mach-imx/pm-imx25.c:31:13: error: no previous prototype for 'imx25_pm_init'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>