[SUBMITTED 20181002] nvmem: lpc18xx_eeprom: remove an unused variable
drivers/nvmem/lpc18xx_eeprom.c: In function 'lpc18xx_eeprom_remove':
drivers/nvmem/lpc18xx_eeprom.c:258:6: error: unused variable 'ret' [-Werror=unused-variable]

Fixes: 226014d13fa5 ("nvmem: lpc18xx_eeprom: use devm_nvmem_register()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>