regulator: remove incorrect of_match_ptr annotation
Building with W=1 shows a warning about of_match tables being unused
when CONFIG_OF is disabled:

    drivers/regulator/pbias-regulator.c:136:34: error: unused variable 'pbias_of_match' [-Werror,-Wunused-const-variable]
    drivers/regulator/twl-regulator.c:552:34: error: unused variable 'twl_of_match' [-Werror,-Wunused-const-variable]
    drivers/regulator/twl6030-regulator.c:645:34: error: unused variable 'twl_of_match' [-Werror,-Wunused-const-variable]

In all three cases, the of_match_ptr() annotation makes no sense because
these regulators are only ever used on systems with CONFIG_OF enabled.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>