[SUBMITTED 20190322] pwm: img: work around clang -Wunintialized warning
clang fails to notice that 'if (mul > max_timebase * 512)' is
always true here based on excluding all the other case, and
warns about the subsequent use of the 'timebase' variable:

drivers/pwm/pwm-img.c:126:13: error: variable 'timebase' is used uninitialized whenever 'if' condition is false
      [-Werror,-Wsometimes-uninitialized]
        } else if (mul > max_timebase * 512) {
                   ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/pwm/pwm-img.c:132:22: note: uninitialized use occurs here
        duty = DIV_ROUND_UP(timebase * duty_ns, period_ns);
                            ^~~~~~~~
include/linux/kernel.h:90:22: note: expanded from macro 'DIV_ROUND_UP'
 define DIV_ROUND_UP __KERNEL_DIV_ROUND_UP
                     ^
include/uapi/linux/kernel.h:13:40: note: expanded from macro '__KERNEL_DIV_ROUND_UP'
 define __KERNEL_DIV_ROUND_UP(n, d) (((n) + (d) - 1) / (d))
                                       ^
drivers/pwm/pwm-img.c:126:9: note: remove the 'if' if its condition is always true
        } else if (mul > max_timebase * 512) {
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/pwm/pwm-img.c:98:30: note: initialize the variable 'timebase' to silence this warning
        u32 val, div, duty, timebase;
                                    ^
                                     = 0

Since this is always true here, we can just eliminate the redundant
check to avoid the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>