[SUBMITTED] mfd: fsl-imx25-tsadc: select IRQ_DOMAIN
The newly added tsadc code use irq domains, but it can be enabled
when they are disabled in Kconfig:

drivers/mfd/fsl-imx25-tsadc.c:41:22: error: implicit declaration of function 'irq_find_mapping' [-Werror=implicit-function-declaration]
   generic_handle_irq(irq_find_mapping(tsadc->domain, 1));
drivers/mfd/fsl-imx25-tsadc.c: In function 'mx25_tsadc_setup_irq':
drivers/mfd/fsl-imx25-tsadc.c:80:18: error: implicit declaration of function 'irq_domain_add_simple' [-Werror=implicit-function-declaration]

This adds a 'select IRQ_DOMAIN' code, like we have it in all other
drivers with this requirement.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: e2fccf5c1515 ("mfd: fsl-imx25-tsadc: Register touchscreen ADC driver")