[SUBMITTED 20211027] virtio-blk: select CONFIG_SG_POOL
Switching virtio-blk to the sg_pool interfaces causes a build
failures when they are not part of the kernel:

drivers/block/virtio_blk.c:182:3: error: implicit declaration of function 'sg_free_table_chained' [-Werror,-Wimplicit-function-declaration]
                sg_free_table_chained(&vbr->sg_table,
                ^
drivers/block/virtio_blk.c:195:8: error: implicit declaration of function 'sg_alloc_table_chained' [-Werror,-Wimplicit-function-declaration]
        err = sg_alloc_table_chained(&vbr->sg_table,
              ^

Select this symbol through Kconfig, as is done for all other
users.

Fixes: b2c5221fd074 ("virtio-blk: avoid preallocating big SGL for data")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>