bcachefs: ioctl: avoid stack overflow warning
An allmodconfig build on arm32 causes a warning in bcachefs for narrowly
exceeding the stack size warning limit:

fs/bcachefs/chardev.c:655:6: error: stack frame size (1032) exceeds limit (1024) in 'bch2_fs_ioctl' [-Werror,-Wframe-larger-than]
  655 | long bch2_fs_ioctl(struct bch_fs *c, unsigned cmd, void __user *arg)

The problem here is that the ioctl function is fully inlined

Signed-off-by: Arnd Bergmann <arnd@arndb.de>