i2c: adv7604: mark register access as noinline_if_stackbloat
When building with KASAN, we get a stack frame size warning about a function
that could potentially cause a stack overflow:

drivers/media/i2c/adv7604.c: In function 'adv76xx_log_status':
drivers/media/i2c/adv7604.c:2615:1: error: the frame size of 3248 bytes is larger than 3072 bytes [-Werror=frame-larger-than=]

This is caused by adv76xx_read_check() being inlined repeatedly, and
marking this function as noinline_if_stackbloat solves the problem
completely.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>