[SUBMITTED 20160511] mm, compaction: avoid uninitialized variable use
A recent rework of the compaction code introduced a warning about
an uninitialized variable when CONFIG_COMPACTION is disabled and
__alloc_pages_direct_compact() does not set its 'compact_result'
output argument:

mm/page_alloc.c: In function '__alloc_pages_nodemask':
mm/page_alloc.c:3651:6: error: 'compact_result' may be used uninitialized in this function [-Werror=maybe-uninitialized]

This adds another check for CONFIG_COMPACTION to ensure we never
evaluate the uninitialized variable in this configuration, which
is probably the simplest way to avoid the warning.

A more elaborate rework might make this more readable.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 13cff7b81275 ("mm, compaction: simplify __alloc_pages_direct_compact feedback interface")