[SUBMITTED 20210322] acpi: avoid -Wempty-body warnings
The acpi drivers produce a number of avoidable warnings for empty macros
when building with 'make W=1':

drivers/acpi/acpi_processor.c: In function 'acpi_processor_errata_piix4':
drivers/acpi/acpi_processor.c:133:95: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
  133 |                                   "Bus master activity detection (BM-IDE) erratum enabled\n"));
      |                                                                                               ^
drivers/acpi/acpi_processor.c:136:82: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
  136 |                                   "Type-F DMA livelock erratum (C3 disabled)\n"));
      |                                                                                  ^
drivers/acpi/acpi_processor.c: In function 'acpi_processor_get_info':
drivers/acpi/acpi_processor.c:251:77: error: suggest braces around empty body in an 'else' statement [-Werror=empty-body]
  251 |                                   "No bus mastering arbitration control\n"));
      |                                                                             ^
drivers/acpi/processor_pdc.c: In function 'acpi_processor_eval_pdc':
drivers/acpi/processor_pdc.c:136:79: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
  136 |                     "Could not evaluate _PDC, using legacy perf. control.\n"));
      |                                                                               ^

I tried making these call no_printk() instead, which would add proper
format string checking, but that turned out to be a rather invasive
change, so just shut up the warning by turning the macros into empty
"do {} while (0)" statements.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>