[REWORK] soc: qcom: fix missing nul-termination warning
Using strncpy() to copy into a fixed-length array can result
in an unterminated string as pointed out by gcc:

In function 'strncpy',
    inlined from 'apr_add_device' at /git/arm-soc/drivers/soc/qcom/apr.c:222:3,
    inlined from 'of_register_apr_devices' at /git/arm-soc/drivers/soc/qcom/apr.c:264:7,
    inlined from 'apr_probe' at /git/arm-soc/drivers/soc/qcom/apr.c:290:2:
include/linux/string.h:254:9: error: '__builtin_strncpy' specified bound 32 equals destination size [-Werror=stringop-truncation]
  return __builtin_strncpy(p, q, size);

This uses strlcpy() here, which is safer when we expect the string
to be terminated later.

Fixes: 6adba21eb434 ("soc: qcom: Add APR bus driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>

fix soc: qcom: fix missing nul-termination warning

Signed-off-by: Arnd Bergmann <arnd@arndb.de>