[SUBMITTED 20161124] clk: renesas: cpg_mstp: build for R8A774{3,5}
We get a link failure on R8A7745 and R8A7743 when the other platforms
are disabled and nothing selects the clk-rcar-gen2 driver:

drivers/clk/renesas/clk-rcar-gen2.o: In function `rcar_gen2_cpg_clocks_init':
clk-rcar-gen2.c:(.init.text+0x39c): undefined reference to `cpg_mstp_add_clk_domain'

This adds another 'select' statement to get them to build as well.

Fixes: 9127d54bb894 ("clk: renesas: cpg-mssr: Add R8A7745 support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>