[SUPERCEDED] hash: fix gcc-4 build warnings in test_hash.c
The newly added lib/test_hash.c file builds fine with gcc-5 or newer,
but causes some annoying warnings witih gcc-4.9 and older:

lib/test_hash.c: In function ‘test_hash_init’:
lib/test_hash.c:146:2: error: missing braces around initializer [-Werror=missing-braces]
lib/test_hash.c:146:2: error: (near initialization for ‘hash_or[0]’) [-Werror=missing-braces]
lib/test_hash.c:224:7: error: "HAVE_ARCH__HASH_32" is not defined [-Werror=undef]
lib/test_hash.c:229:7: error: "HAVE_ARCH_HASH_32" is not defined [-Werror=undef]
lib/test_hash.c:234:7: error: "HAVE_ARCH_HASH_64" is not defined [-Werror=undef]

This adds the braces and extra #ifdef checks for the macros to shut up those
warnings.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>