[SUBMITTED 20190416] serial: sc16is7xx: fix unused label warning
A bugfix introduced a harmless warning:

drivers/tty/serial/sc16is7xx.c:1523:1: error: unused label 'err_spi' [-Werror,-Wunused-label]

Move each label inside the correct #ifdef.

Fixes: ac0cdb3d9901 ("sc16is7xx: missing unregister/delete driver on error in sc16is7xx_init()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>