ARM: add missing include statements
After removing linux/vmalloc.h from asm-generic/io.h, a few other
files fail:

arch/arm/mach-shmobile/pm-r8a7779.c:35:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'r8a7779_pm_init'
 void __init r8a7779_pm_init(void)
             ^~~~~~~~~~~~~~~
scripts/Makefile.build:311: recipe for target 'arch/arm/mach-shmobile/pm-r8a7779.o' failed
make[3]: *** [arch/arm/mach-shmobile/pm-r8a7779.o] Error 1
make[3]: Target '__build' not remade because of errors.
Makefile:1019: recipe for target 'arch/arm/mach-shmobile' failed
make[2]: *** [arch/arm/mach-shmobile] Error 2
In file included from arch/arm/mach-imx/devices/../mx3x.h:146:0,
                 from arch/arm/mach-imx/devices/../hardware.h:109,
                 from arch/arm/mach-imx/devices/platform-flexcan.c:8:

Signed-off-by: Arnd Bergmann <arnd@arndb.de>