[TEMPORARY] net: netfilter: IPV6 XT sockets need CONFIG_NF_DEFRAG_IPV6
If IP6_NF_IPTABLES=m, NF_DEFRAG_IPV6 gets selected as a module as well
from NETFILTER_XT_MATCH_SOCKET, so the latter cannot be built-in, or
we get:

net/built-in.o: In function `socket_mt_init':
:(.init.text+0x32a0): undefined reference to `nf_defrag_ipv6_enable'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>