[SUBMITTED 20190306] mm/hmm: fix unused variable warning in hmm_vma_walk_pud
Without CONFIG_HUGETLB_PAGE, the 'vma' variable is never referenced
on x86, so we get this warning:

mm/hmm.c: In function 'hmm_vma_walk_pud':
mm/hmm.c:764:25: error: unused variable 'vma' [-Werror=unused-variable]

Remove the local variable by open-coding walk-vma in the only
place it is used.

Reported-by: John Hubbard <jhubbard@nvidia.com>
Suggested-by: John Hubbard <jhubbard@nvidia.com>
Fixes: 1bed8a07a556 ("mm/hmm: allow to mirror vma of a file on a DAX backed filesystem")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
Andrew, you already took a similar patch from me for a different
warning in the same file. Feel free to fold both patches into
one if you haven't already forwarded the first patch, or leave
them separate. Note that the warnings were introduced by different
patches from the same series originally.