[SUBMITTED 20180115] x86/jailhouse: fix building without X86_X2APIC
When CONFIG_X86_X2APIC is disabled, jailhouse fails to build:

arch/x86/kernel/jailhouse.c: In function 'jailhouse_get_smp_config':
arch/x86/kernel/jailhouse.c:73:3: error: 'x2apic_phys' undeclared (first use in this function); did you mean 'x2apic_mode'?

The code is protected by an appropriate x2apic_enabled() check that leads
to the assignment being optimized out without a link-time reference to
x2apic_phys, so we just lack a declaration.

Let's move x2apic_mode and x2apic_phys outside of the #ifdef together,
for consistency.

Fixes: 11c8dc419bbc ("x86/jailhouse: Enable APIC and SMP support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>