staging/imx-drm: use GENERIC_IRQ_CHIP
This driver defines its own irqchip using the generic chip
infrastructure, and hence needs the GENERIC_IRQ_CHIP Kconfig
symbol enabled, or get this build error:

drivers/built-in.o: In function `ipu_probe':
:(.text+0x49ea4c): undefined reference to `irq_generic_chip_ops'
:(.text+0x49ea5c): undefined reference to `irq_alloc_domain_generic_chips'
:(.text+0x49ea60): undefined reference to `irq_get_domain_generic_chip'
:(.text+0x49ea64): undefined reference to `irq_gc_ack_set_bit'
:(.text+0x49ea6c): undefined reference to `irq_gc_mask_clr_bit'
:(.text+0x49ea70): undefined reference to `irq_gc_mask_set_bit'

Cc: Dave Airlie <airlied@redhat.com>
Cc: dri-devel@lists.freedesktop.org
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Cc: Philipp Zabel <p.zabel@pengutronix.de>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>