ARM: highbank: add missing include
highbank_pm_init() is declared in core.h this is not included in the
file that defines it.

arch/arm/mach-highbank/pm.c:43:13: error: no previous prototype for 'highbank_pm_init'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>