[SUBMITTED] mempool: add missing include
This is a fix^3 for the mempool poisoning patch, which introduces
a compile-time error on some ARM randconfig builds:

mm/mempool.c: In function 'check_element':
mm/mempool.c:65:16: error: implicit declaration of function 'kmap_atomic' [-Werror=implicit-function-declaration]
   void *addr = kmap_atomic((struct page *)element);

The problem is clearly the missing declaration, and including
linux/highmem.h fixes it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: a3db5a8463b0db ("mm, mempool: poison elements backed by page allocator fix fix")