[SUBMITTED 20230417] net: hyperv: select CONFIG_NLS for mac address setting
A rare randconfig build error happens when this driver is
enabled, but nothing else enables NLS support:

x86_64-linux-ld: drivers/net/hyperv/rndis_filter.o: in function `rndis_filter_set_device_mac':
rndis_filter.c:(.text+0x1536): undefined reference to `utf8s_to_utf16s'

This is normally selected by PCI, USB, ACPI, or common file systems.
Since the dependency on ACPI is now gone, NLS has to be selected
here directly.

Fixes: 38299f300c12 ("Driver: VMBus: Add Devicetree support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>