[SUBMITTED 20210723] drm/hisilicon/hibmc: remove an unused variable
A recent patch left an unused variable in place that needs to be
removed:

drivers/gpu/drm/hisilicon/hibmc/hibmc_drm_drv.c: In function 'hibmc_unload':
drivers/gpu/drm/hisilicon/hibmc/hibmc_drm_drv.c:252:35: error: unused variable 'priv' [-Werror=unused-variable]
  252 |         struct hibmc_drm_private *priv = to_hibmc_drm_private(dev);

Fixes: 39a364a19e03 ("drm/hisilicon/hibmc: Convert to Linux IRQ interfaces")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>