[SUBMITTED 20190918] platform/x86: asus-wmi: add ACPI_BATTERY dependency
Without this dependency, we can run into a link failure:

drivers/platform/x86/asus-wmi.o: In function `asus_wmi_remove':
asus-wmi.c:(.text+0x430): undefined reference to `battery_hook_unregister'
drivers/platform/x86/asus-wmi.o: In function `asus_wmi_probe':
asus-wmi.c:(.text+0x2c6f): undefined reference to `battery_hook_register'

Fixes: 7973353e92ee ("platform/x86: asus-wmi: Refactor charge threshold to use the battery hooking API")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>