drm/exynos: fix fimd_dp dependency
drivers/built-in.o: In function `exynos_dp_poweroff':
:(.text+0x29f4e0): undefined reference to `fimd_dp_clock_enable'
drivers/built-in.o: In function `exynos_dp_poweron':
:(.text+0x29ff34): undefined reference to `fimd_dp_clock_enable'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 377b8fc67dc320 ("drm/exynos: Enable DP clock to fix display on Exynos5250 and other")