[SUBMITTED 20230616] scsi: bfa: fix function pointer type mismatch for hcb_qe->cbfn
Some callback functions used here take a boolean argument, others
take a status argument. This breaks KCFI type checking, so clang
now warns about the function pointer cast:

drivers/scsi/bfa/bfad_bsg.c:2138:29: error: cast from 'void (*)(void *, enum bfa_status)' to 'bfa_cb_cbfn_t' (aka 'void (*)(void *, enum bfa_boolean)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]

Assuming the code is actually correct here and the callers always match
the argument types of the callee, rework this to replace the explicit
cast with a union of the two pointer types. This does not change the
behavior of the code, so if something is actually broken here, a larger
rework may be necessary.

Fixes: 37ea0558b87ab ("[SCSI] bfa: Added support to collect and reset fcport stats")
Fixes: 3ec4f2c8bff25 ("[SCSI] bfa: Added support to configure QOS and collect stats.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>