damon: disable structleak plugin for kunit test
This is one more file that needs the plugin to be disabled in order
to avoid overly large stack usage:

In file included from mm/damon/vaddr.c:672:
mm/damon/vaddr-test.h: In function 'damon_test_split_evenly':
mm/damon/vaddr-test.h:309:1: error: the frame size of 1080 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

The contents of the kunit test are currently in a separate .h file,
but I see no reason why it was done that way, and in order to pass
custom compiler flags, it needs to be a separate object, with
a couple of local symbols turned into globals.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>