[SUBMITTED 20160616] sunrpc: fix old-style declaration
Modern C standards expect the 'static' keyword to come before the return
type in a declaration, and we get a warning for this with "make W=1":

net/sunrpc/clnt.c:2580:1: error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>