mm: hugetlb: fix build CMD failure
for_each_mem_pfn_range() is defined conditionally, causing a
build failure when CONFIG_HAVE_MEMBLOCK_NODE_MAP is disabled:

mm/hugetlb.c: In function 'hugetlb_cma_reserve':
mm/hugetlb.c:5580:3: error: implicit declaration of
function 'for_each_mem_pfn_range'; did you mean 'for_each_mem_range'?
[-Werror=implicit-function-declaration]
 5580 |   for_each_mem_pfn_range(i, nid, &start_pfn, &end_pfn, NULL) {
      |   ^~~~~~~~~~~~~~~~~~~~~~
      |   for_each_mem_range
mm/hugetlb.c:5580:61: error: expected ';' before '{' token
 5580 |   for_each_mem_pfn_range(i, nid, &start_pfn, &end_pfn, NULL) {
      |                                                             ^~
      |                                                             ;

Make the code that relies on this also conditional on the same
symbol.

Fixes: 7cfe2df30b35 ("mm: hugetlb: optionally allocate gigantic hugepages using cma")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>