mem_encrypt: add inline helper
The header file only has a prototype for mem_encrypt_init() if it
is enabled, otherwise we get (with "make C=1" or "make W=1"):

init/main.c:722:20: error: no previous prototype for 'mem_encrypt_init' [-Werror=missing-prototypes]
  722 | void __init __weak mem_encrypt_init(void) { }
      |                    ^~~~~~~~~~~~~~~~

Remove the __weak function and instead add a simple inline
stub in the header, as we do in most other places.

Fixes: ae67d58d0546 ("init/main.c: include <linux/mem_encrypt.h>")
Fixes: c7753208a94c ("x86, swiotlb: Add memory encryption support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>