[SUBMITTED 20161122] kasan: turn off -fsanitize-address-use-after-scope for now
In the upcoming gcc-7 release, the -fsanitize=kernel-address option
implies -fsanitize-address-use-after-scope, which relies on the
definition of two global functions, causing many link errors if they
are not defined, e.g:

arch/x86/built-in.o: In function `x86_pmu_handle_irq':
(.text+0x88e6): undefined reference to `__asan_unpoison_stack_memory'
arch/x86/built-in.o: In function `x86_pmu_handle_irq':
(.text+0x8ad7): undefined reference to `__asan_poison_stack_memory'
kernel/built-in.o: In function `perf_tp_event':
(.text+0x225472): undefined reference to `__asan_unpoison_stack_memory'
kernel/built-in.o: In function `perf_tp_event':
(.text+0x22583a): undefined reference to `__asan_unpoison_stack_memory'
kernel/built-in.o: In function `perf_tp_event':
(.text+0x2258ae): undefined reference to `__asan_poison_stack_memory'
kernel/built-in.o: In function `perf_event_aux_event':

I think we really want to define those two functions so we can make
use of a helpful feature, but as I have no idea what they are supposed
to do, I'd suggest to turn the option off on existing kernels to allow
building with gcc-7 and kasan.

For some reason, the problem showed up in only a few randconfig builds,
but it is easy to reproduce using an x86-64 tinyconfig build with
CONFIG_KASAN=y.

If we decide to take this approach, we probably want to do the same
change on all stable kernels that support KASAN, i.e. v4.0 or higher.

Link: https://gcc.gnu.org/viewcvs/gcc?limit_changes=0&view=revision&revision=241896
Cc: Martin Liška <marxin@gcc.gnu.org>
Cc: Andrey Ryabinin <a.ryabinin@samsung.com>
Cc: stable@vger.kernel.org
Signed-off-by: Arnd Bergmann <arnd@arndb.de>