[SUBMITTED 20200108] [v2] of: add more dummy helper functions
The new phy-j721e-wiz driver causes a link failure without CONFIG_OF:

drivers/phy/ti/phy-j721e-wiz.o: In function `wiz_remove':
phy-j721e-wiz.c:(.text+0x40): undefined reference to `of_platform_device_destroy'

Add a dummy version of of_platform_device_destroy to avoid having to add
Kconfig dependencies for the driver. As there are a few other functions
without dummy implementations, add those as well for completeness.

Fixes: 42440de5438a ("phy: ti: j721e-wiz: Add support for WIZ module present in TI J721E SoC")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>