ARM: actions: select CONFIG_PM_GENERIC_DOMAINS
arm-linux-gnueabi-ld: arch/arm/mach-actions/platsmp.o: in function `s500_smp_boot_secondary':
platsmp.c:(.text.s500_smp_boot_secondary+0x2e): undefined reference to `owl_sps_set_pg'

Fixes: 7ed363cd8d0a ("genpd: move owl-sps-helper.c from drivers/soc")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>