LiquidIO VF: add dependency for PTP_1588_CLOCK
The 'imply' keyword no longer does what it was originally
introduced for:

lio_ethtool.c:(.text+0xba8): undefined reference to `ptp_clock_index'

Use a dependency instead.

Fixes: cd7aeb1f9706 ("LiquidIO VF: s/select/imply/ for PTP_1588_CLOCK")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>