w1: ds2505: select CRC16
drivers/w1/slaves/w1_ds250x.o: In function `w1_ds2505_read_page':
w1_ds250x.c:(.text+0xed4): undefined reference to `crc16'

Fixes: 25ec8710d9c2 ("w1: add DS2501, DS2502, DS2505 EPROM device driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>