iwlwifi: fix 32-bit compilation warning again
After the UEFI code was moved into another file, a warning
came back that was already fixed in commit 436b265671d6 ("iwlwifi:
fix ARCH=i386 compilation warnings"):

drivers/net/wireless/intel/iwlwifi/fw/uefi.c: In function 'iwl_uefi_get_pnvm':
drivers/net/wireless/intel/iwlwifi/fw/uefi.c:52:30: error: format '%zd' expects argument of type 'signed size_t', but argument 7 has type 'long unsigned int' [-Werror=format=]
   52 |                              "PNVM UEFI variable not found %d (len %zd)\n",
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   53 |                              err, package_size);
      |                                   ~~~~~~~~~~~~
      |                                   |
      |                                   long unsigned int

Fix it again the same way.

Fixes: 84c3c9952afb ("iwlwifi: move UEFI code to a separate file")
Fixes: 436b265671d6 ("iwlwifi: fix ARCH=i386 compilation warnings")
Fixes: a1a6a4cf49ec ("iwlwifi: pnvm: implement reading PNVM from UEFI")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>