[SUBMITTED 20161216] gcc-plugin: include memmodel.h and tree_vrp.h for gcc-7
Building our gcc plugins currently fails with the gcc-7 snapshots,
due to some slightly modified header interfaces:

In file included from /git/arm-soc/scripts/gcc-plugins/gcc-common.h:42:0,
                 from <stdin>:1:
/home/arnd/cross-gcc/lib/gcc/x86_64-linux/7.0.0/plugin/include/emit-rtl.h:371:41: error: use of enum ‘memmodel’ without previous declaration
 extern bool need_atomic_barrier_p (enum memmodel, bool);
                                         ^
In file included from /git/arm-soc/scripts/gcc-plugins/gcc-common.h:94:0,
                 from <stdin>:1:
/home/arnd/cross-gcc/lib/gcc/x86_64-linux/7.0.0/plugin/include/tree-ssanames.h:70:40: error: use of enum ‘value_range_type’ without previous declaration
 extern void set_range_info (tree, enum value_range_type, const wide_int_ref &,

This makes it work again, which will be important once we turn
the plugins on in allmodconfig by default. It probably also
makes sense to backport these to v4.9 and v4.8, which
added the header file originally.

Cc: stable@vger.kernel.org
Suggested-by: Kugan <kugan.vivekanandarajah@linaro.org>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>