ARM: decompressor: avoid stack frame warning
clang's inlining changed, and if merge_fdt_bootargs() is inlined
into its caller, the combined stack size is larger than the
(already increased) limit:

arch/arm/boot/compressed/atags_to_fdt.c:129:5: error: stack frame size (1344) exceeds limit (1280) in 'atags_to_fdt' [-Werror,-Wframe-larger-than]

Avoid this warning by forcing the inlining to be the same way that
gcc does it. This should be safe because the only caller comes
from a known call stack and won't overflow the total 8KB of
stack.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>