[SUBMITTED 20240322] coda: avoid Wunused-but-set-variable warning
The UPARG() macro implicitly sets the outp variable, but a lot of the
callers never actually use the results instead, causing a W=1 warning:

fs/coda/upcall.c:115:27: error: variable 'outp' set but not used [-Werror,-Wunused-but-set-variable]
  115 |         union outputArgs *outp;
      |                           ^

Add a cast to void to shut up that warning for callers that don't
care bout the output.

Fixes: 1da177e4c3f4 ("Linux-2.6.12-rc2")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>