ARM: pxa: hx4700: include mach/irqs.h in hx4700.h
commit 9705e74671f0e4 "ARM: pxa: fix various compilation problems" fixed
a lot of the same bugs, but missed the hx4700 platform, which needs
to include irqs.h to avoid this build error:

drivers/pcmcia/pxa2xx_hx4700.c:22:6: error: 'PXA_NR_BUILTIN_GPIO' undeclared here (not in a function)
  { EGPIO4_CF_3V3_ON,           GPIOF_OUT_INIT_LOW,   "CF 3.3V enable"  },
      ^

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Linus Walleij <linus.walleij@linaro.org>