[SUBMITTED 20240315] speakup: devsynth: remove c23 label
clang-16 and higher warn about a c23 C extension that is also a GNU extension:

drivers/accessibility/speakup/devsynth.c:111:3: error: label at end of compound statement is a C23 extension [-Werror,-Wc23-extensions]

clang-15 just produces an error here:

drivers/accessibility/speakup/devsynth.c:111:3: error: expected statement

This is apparently the only such warning in the kernel tree at the moment,
so just convert it into standard C code using the equivalent 'continue'
keyword.

Fixes: 807977260ae4 ("speakup: Add /dev/synthu device")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>