drm/vc4: fix building without CONFIG_PM
If CONFIG_PM is disabled, we get a build failure trying to call
pm_generic_power{off,on}:

drivers/gpu/drm/vc4/vc4_v3d.c: In function 'vc4_v3d_set_power':
drivers/gpu/drm/vc4/vc4_v3d.c:157:10: error: called object is not a function or function pointer
drivers/gpu/drm/vc4/vc4_v3d.c:159:10: error: called object is not a function or function pointer
drivers/gpu/drm/vc4/vc4_v3d.c:160:1: warning: control reaches end of non-void function [-Wreturn-type]

This patch fixes compilation by making the calling function optional.
However, this might not be the correct solution, as it is called by
vc4_reset(), and that function looks like it relies on the PM
code to reset the 3D unit. An alternative workaround would be
to add a Kconfig dependency, so we cannot build the driver without
CONFIG_PM.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: d5b1a78a772f ("drm/vc4: Add support for drawing 3D frames.")