iommu: amd: hide unused iommu_table_lock
/git/arm-soc/drivers/iommu/amd_iommu.c:86:24: error: 'iommu_table_lock' defined but not used [-Werror=unused-variable]
 static DEFINE_SPINLOCK(iommu_table_lock);

Signed-off-by: Arnd Bergmann <arnd@arndb.de>