ARM: versatile: mark mmc_status() static
mmc_status() is only used in the file it is defined in, and
no longer has an 'extern' declaration:

arch/arm/mach-versatile/versatile.c:56:14: error: no previous prototype for 'mmc_status'

Fixes: 16956fed35fe ("ARM: versatile: switch to DT only booting and remove legacy code")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>