[SUBMITTED 20170710] 9p: hide cachetag option for non-CONFIG_9P_FSCACHE
show_options cannot print this option when it is disabled in Kconfig:

fs/9p/v9fs.c: In function 'v9fs_show_options':
fs/9p/v9fs.c:140:13: error: 'struct v9fs_session_info' has no member named 'cachetag'; did you mean 'cache'?

Fixes: ccb0055985b9 ("9p: Implement show_options")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>