[SUBMITTED 20190905] soundwire: add back ACPI dependency
Soundwire gained a warning for randconfig builds without
CONFIG_ACPI during the linux-5.3-rc cycle:

drivers/soundwire/slave.c:16:12: error: unused function 'sdw_slave_add' [-Werror,-Wunused-function]

Add the CONFIG_ACPI dependency at the top level now.

Fixes: 8676b3ca4673 ("soundwire: fix regmap dependencies and align with other serial links")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>