ALSA: seq: avoid array overflow warning
The fortified memcpy function warns that the data[] array in cvt_to_ump_midi2()
might overflow using an unchecked index number:

In file included from sound/core/seq/seq_ump_convert.c:8:
In file included from include/linux/string.h:254:
include/linux/fortify-string.h:592:4: error: call to '__read_overflow2_field' declared with 'warning' attribute: detected read beyond size of field (2nd parameter); maybe use struct_group()? [-Werror,-Wattribute-warning]
                        __read_overflow2_field(q_size_field, size);
                        ^

Add a runtime check to ensure the index is in range, which avoids this
warning and makes the code more robust against unexpected return codes.

Fixes: e9e02819a98a5 ("ALSA: seq: Automatic conversion of UMP events")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>