sched: fixup prototypes
A lot of scheduler functions are sometime unused, and their
declarations are hidden, but based on the configuration the
definition is still visible to the compiler, which leads to
warnings:

kernel/sched/core.c:6730:35: error: no previous prototype for 'schedule_user'
kernel/sched/fair.c:11936:6: error: no previous prototype for 'task_vruntime_update'
kernel/sched/fair.c:12544:6: error: no previous prototype for 'free_fair_sched_group'
kernel/sched/fair.c:12546:5: error: no previous prototype for 'alloc_fair_sched_group'
kernel/sched/fair.c:12546:6: error: no previous prototype for 'free_fair_sched_group'
kernel/sched/fair.c:12548:5: error: no previous prototype for 'alloc_fair_sched_group'
kernel/sched/fair.c:12551:6: error: no previous prototype for 'online_fair_sched_group'
kernel/sched/fair.c:12553:6: error: no previous prototype for 'online_fair_sched_group'
kernel/sched/fair.c:12555:6: error: no previous prototype for 'unregister_fair_sched_group'
kernel/sched/fair.c:6131:6: error: no previous prototype for 'init_cfs_bandwidth'
kernel/sched/fair.c:688:5: error: no previous prototype for 'sched_update_scaling'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>