powerpc: kvm: allocate kvmppc_gs_parser off stack
The structure is over 1KB in size, which is really too much to have
on the stack, and causes a warning once we reduce the default limit:

arch/powerpc/perf/kvm-hv-pmu.c:305:1: error: the frame size of 1488 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Use dynamic allocation here, adding a small runtime cost and error
handling for a failed allocation.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>