ARM: sbsa110: fix readsw prototype
The declaration has changed in "ARM: normalize asm/io.h accessors", so
we need to change the code as well.

mach-ebsa110/include/mach/io.h:89:16: error: conflicting types for 'readsw'
 #define readsw readsw
                ^
mach-ebsa110/io.c:105:6: note: in expansion of macro 'readsw'
 void readsw(const volatile void __iomem *addr, void *data, int len)
      ^
mach-ebsa110/include/mach/io.h:89:16: note: previous declaration of 'readsw' was here
 #define readsw readsw
                ^
mach-ebsa110/include/mach/io.h:90:13: note: in expansion of macro 'readsw'
 extern void readsw(const void __iomem *addr, void *data, int wordlen);
             ^

Signed-off-by: Arnd Bergmann <arnd@arndb.de>