[media] s5p-jpeg: remove bogus #ifdef
The s5p-jpeg driver only supports DT based probing, using the
jpeg_get_drv_data function. Trying to build the driver without
CONFIG_OF results in this build error:

drivers/built-in.o: In function `s5p_jpeg_probe':
:(.text+0x24c828): undefined reference to `jpeg_get_drv_data'

There is no problem building the code without CONFIG_OF for
build testing, so we should just allow that and remove the
incorrect #ifdef to avoid the build error.

Cc: Mauro Carvalho Chehab <m.chehab@samsung.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>