zswap: include linux/memcontrol.h
mm/zswap.c: In function 'mem_cgroup_from_entry':
mm/zswap.c:313:31: error: implicit declaration of function 'obj_cgroup_memcg'; did you mean 'obj_cgroup_put'? [-Werror=implicit-function-declaration]
  313 |         return entry->objcg ? obj_cgroup_memcg(entry->objcg) : NULL;
      |                               ^~~~~~~~~~~~~~~~
      |                               obj_cgroup_put
mm/zswap.c:313:62: error: pointer/integer type mismatch in conditional expression [-Werror]
  313 |         return entry->objcg ? obj_cgroup_memcg(entry->objcg) : NULL;
      |                                                              ^
mm/zswap.c: In function 'shrink_worker':
mm/zswap.c:984:31: error: invalid use of undefined type 'struct mem_cgroup'
  984 |                 css_get(&memcg->css);
      |                               ^~

Fixes: 70dd375afcfe ("zswap: make shrinking memcg-aware")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>