ARM: mm: avoid unused variable warnings
The references to itcm_end/dtcm_end have been removed, so we should
also remove the declarations to avoid the harmless warning:

arch/arm/mm/init.c: In function 'mem_init':
arch/arm/mm/init.c:471:13: error: unused variable 'itcm_end' [-Werror=unused-variable]
  extern u32 itcm_end;
             ^~~~~~~~
arch/arm/mm/init.c:470:13: error: unused variable 'dtcm_end' [-Werror=unused-variable]
  extern u32 dtcm_end;
             ^~~~~~~~

Fixes: 1c31d4e96b8c ("ARM: 8820/1: mm: Stop printing the virtual memory layout")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>