staging: atomisp: address -Wformat-security warning
dtrace_dot() takes a format string and arguments, causing a W-1 warning
with a non-constant format string:

drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c: In function 'ia_css_debug_pipe_graph_dump_epilogue':
drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1135:28: error: format not a string literal and no format arguments [-Werror=format-security]
 1135 |                 dtrace_dot(ring_buffer);
      |                            ^~~~~~~~~~~
drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c: In function 'ia_css_debug_pipe_graph_dump_sp_raw_copy':
drivers/staging/media/atomisp/pci/runtime/debug/src/ia_css_debug.c:1406:20: error: format not a string literal and no format arguments [-Werror=format-security]
 1406 |         dtrace_dot(ring_buffer);
      |                    ^~~~~~~~~~~

Change this one to use "%s" as the format.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>