kasan: limit CONFIG_KASAN_STACK to gcc-9 and up
Stack usage depends a lot on inlining decisions that are compiler
specific. gcc-9 changed how much inlining it does, so the behavior on
newer versions will cause different functions to exceed the warning limit
from older versions. Since developers these days only test the new ones,
this causes regressions on gcc-8 and older that often remain unfixed
and lead to clutter in the warning log such as:

lib/crypto/curve25519-fiat32.c: In function 'curve25519_generic':
lib/crypto/curve25519-fiat32.c:864:1: error: the frame size of 1480 bytes is larger than 1400 bytes [-Werror=frame-larger-than=]
drivers/input/mouse/cyapa_gen5.c: In function 'cyapa_gen5_show_baseline':
drivers/input/mouse/cyapa_gen5.c:2435:1: error: the frame size of 1936 bytes is larger than 1400 bytes [-Werror=frame-larger-than=]
kernel/rcu/tree_stall.h: In function 'show_rcu_gp_kthreads':
kernel/rcu/tree_stall.h:935:1: error: the frame size of 1672 bytes is larger than 1400 bytes [-Werror=frame-larger-than=]
lib/tests/overflow_kunit.c: In function 'overflow_allocation_test':
lib/tests/overflow_kunit.c:698:1: error: the frame size of 1632 bytes is larger than 1400 bytes [-Werror=frame-larger-than=]

As it is fairly clear that nobody is fixing these issues for old compilers
any more and that these are not helpful either, limit KASAN_STACK to
modern versions of gcc that don't exceed the stack warning limit.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>