afs: use xchg64() instead of xchg() on 64-bit data
ERROR: modpost: "__bad_xchg" [fs/afs/kafs.ko] undefined!

Signed-off-by: Arnd Bergmann <arnd@arndb.de>