[SUBMITTED 20230117] scsi: stex: fix MU_MAX_DELAY typecheck
time_after() expects arguments of the same type, but gcc-13 changed the
way that typeof(MU_MAX_DELAY) is determined, causing a build warning as
'before + MU_MAX_DELAY * HZ' gets promoted to a 64-bit integer:

In file included from include/linux/bitops.h:7,
                 from include/linux/kernel.h:22,
                 from drivers/scsi/stex.c:13:
drivers/scsi/stex.c: In function 'stex_common_handshake':
include/linux/typecheck.h:12:25: error: comparison of distinct pointer types lacks a cast [-Werror]
   12 |         (void)(&__dummy == &__dummy2); \
      |                         ^~
include/linux/jiffies.h:106:10: note: in expansion of macro 'typecheck'
  106 |          typecheck(unsigned long, b) && \
      |          ^~~~~~~~~
drivers/scsi/stex.c:1035:29: note: in expansion of macro 'time_after'
 1035 |                         if (time_after(jiffies, before + MU_MAX_DELAY * HZ)) {

Change the enum definition so all values fit into an unsigned
32-bit number.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>