[SUBMITTED 20170201] phy: qcom-usb-hs: add extcon dependency
If extcon is a loadable module and qcom-usb-hs is built-in,
we get a link failure:

drivers/phy/phy-qcom-usb-hs.o: In function `qcom_usb_hs_phy_power_off':
phy-qcom-usb-hs.c:(.text.qcom_usb_hs_phy_power_off+0x24): undefined reference to `extcon_unregister_notifier'
drivers/phy/phy-qcom-usb-hs.o: In function `qcom_usb_hs_phy_power_on':
phy-qcom-usb-hs.c:(.text.qcom_usb_hs_phy_power_on+0x1a0): undefined reference to `extcon_get_state'
phy-qcom-usb-hs.c:(.text.qcom_usb_hs_phy_power_on+0x1cc): undefined reference to `extcon_register_notifier'
drivers/phy/phy-qcom-usb-hs.o: In function `qcom_usb_hs_phy_probe':
phy-qcom-usb-hs.c:(.text.qcom_usb_hs_phy_probe+0x15c): undefined reference to `extcon_get_edev_by_phandle'

Adding a hard dependency avoids the problem. Alternatively we could
use "depends on EXTCON || !EXTCON" to allow building with extcon
disabled completely, but the other PHY drivers with extcon support
also just have a dependency, so this is more consistent.

Fixes: e2427b09ba92 ("phy: Add support for Qualcomm's USB HS phy")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>