scsi: pm80xx: work around fortified memcpy warning
Both the pm8001 and pm80xx variants cause a warning about the copy
of the returned "dev_to_host_fis  sata_fis" structure:

In file included from /home/arnd/arm-soc/drivers/scsi/pm8001/pm80xx_hwi.c:40:
include/linux/fortify-string.h:592:4: error: call to '__read_overflow2_field' declared with 'warning' attribute: detected read beyond size of field (2nd parameter); maybe use struct_group()? [-Werror,-Wattribute-warning]
                        __read_overflow2_field(q_size_field, size);

For some reason, they copy four bytes of the previous structure but
not the last bytes of this one. I have no idea if this is actually the
intended behavior or why this is done.

Assuming this is indeed intentional, avoid the warning by splitting up
the memcpy() into two separate copies for the two portions.

Fixes: dbf9bfe615717 ("[SCSI] pm8001: add SAS/SATA HBA driver")
Fixes: f5860992db55c ("[SCSI] pm80xx: Added SPCv/ve specific hardware functionalities and relevant changes in common files")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>