x86: remove "temporary" -ffreestanding flag
The -ffreestanding flag was added in 2006 temporarily to suppress
certain optimizations to string operations until the kernel
could deal with them.

I noticed that one of the optimizations that is avoided by this
leads to large stack usage with clang, when it avoids the use
of a memcpy() to assign a variable from a compound literal:

drivers/staging/greybus/audio_topology.c:977:12: error: stack frame size of 1812 bytes in function 'gbaudio_tplg_create_widget' [-Werror,-Wframe-larger-than=]
static int gbaudio_tplg_create_widget(struct gbaudio_module_info *module,

Removing the flag seems to work fine in build testing and produce
slightly better code in a number of places.

Fixes: 6edfba1b33c7 ("[PATCH] x86_64: Don't define string functions to builtin")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>