[SUBMITTED 20211027] net: ax88796c: fix -Wpointer-bool-conversion warning
ax_local->phydev->advertising is an array, not a pointer, so
clang points out that checking for NULL is unnecessary:

drivers/net/ethernet/asix/ax88796c_main.c:851:24: error: address of array 'ax_local->phydev->advertising' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
        if (ax_local->phydev->advertising &&
            ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~ ~~

Fixes: a97c69ba4f30 ("net: ax88796c: ASIX AX88796C SPI Ethernet Adapter Driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>