[SUBMITTED] net/wireless: CFG80211_WEXT_EXPORT requires wireless extensions
The CFG80211_WEXT_EXPORT symbol is selected by two drivers that
make direct use of compat handlers for the wireless ioctls.
However, this has no effect when the wireless extensions themselves
are disabled, and results in a link error:

ERROR: "cfg80211_wext_giwrts" [drivers/net/wireless/orinoco/orinoco.ko] undefined!
ERROR: "cfg80211_wext_siwfrag" [drivers/net/wireless/orinoco/orinoco.ko] undefined!
ERROR: "cfg80211_wext_giwname" [drivers/net/wireless/ipw2x00/ipw2200.ko] undefined!

This changes the Kconfig logic so that CFG80211_WEXT can not
be disabled when CFG80211_WEXT_EXPORT is set.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 2afe38d15cee01 ("cfg80211-wext: export symbols only when needed")