arm64: avoid Woverride-init warning for init_pg_dir
In file included from include/linux/mm_types.h:19,
                 from mm/init-mm.c:2:
arch/arm64/include/asm/mmu.h:54:16: error: initialized field overwritten [-Werror=override-init]
   54 |         .pgd = init_pg_dir,
      |                ^~~~~~~~~~~
mm/init-mm.c:41:9: note: in expansion of macro 'INIT_MM_CONTEXT'
   41 |         INIT_MM_CONTEXT(init_mm)
      |         ^~~~~~~~~~~~~~~

Fixes: 2b5548b68199 ("arm64/mm: Separate boot-time page tables from swapper_pg_dir")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>