net: iosm: fix printing of dma_addr_t
A dma_addr_t is not necessarily the same length as a pointer, so
we may get a warning on 32-bit architectures with 64-bit DMA
addressing:

In file included from include/linux/device.h:15:0,
                 from include/linux/dma-mapping.h:7,
                 from include/linux/skbuff.h:31,
                 from drivers/net/wwan/iosm/iosm_ipc_imem.h:9,
                 from drivers/net/wwan/iosm/iosm_ipc_protocol.h:9,
                 from drivers/net/wwan/iosm/iosm_ipc_protocol_ops.c:6:
drivers/net/wwan/iosm/iosm_ipc_protocol_ops.c: In function 'ipc_protocol_dl_td_process':
drivers/net/wwan/iosm/iosm_ipc_protocol_ops.c:416:4: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
    (void *)p_td->buffer.address, skb->data);
    ^
include/linux/dev_printk.h:110:23: note: in definition of macro 'dev_printk_index_wrap'
   _p_func(dev, fmt, ##__VA_ARGS__);   \
                       ^~~~~~~~~~~
drivers/net/wwan/iosm/iosm_ipc_protocol_ops.c:415:3: note: in expansion of macro 'dev_err'
   dev_err(ipc_protocol->dev, "invalid buf=%p or skb=%p",
   ^~~~~~~

Use the special %pad format modifier for printing the address, passing
it by reference.

Fixes: 64516f633bfd ("net: iosm: protocol operations")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>