net: mdio-octeon: fix gcc build warnings
The previous fix only addressed the warnings from clang, but gcc
and sparse produces another set of warnings from the type mismatch
between a 'u64' and a the expected 'void __iomem *':

In file included from drivers/net/phy/mdio-cavium.c:11:
drivers/net/phy/mdio-cavium.c: In function 'cavium_mdiobus_set_mode':
drivers/net/phy/mdio-cavium.h:114:37: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 #define oct_mdio_readq(addr)  readq((void *)addr)
                                     ^
drivers/net/phy/mdio-cavium.c:21:16: note: in expansion of macro 'oct_mdio_readq'
  smi_clk.u64 = oct_mdio_readq(p->register_base + SMI_CLK);
                ^~~~~~~~~~~~~~
drivers/net/phy/mdio-cavium.h:113:48: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 #define oct_mdio_writeq(val, addr) writeq(val, (void *)addr)
                                                ^
drivers/net/phy/mdio-octeon.c:48:18: warning: cast removes address space of expression
drivers/net/phy/mdio-octeon.c:56:9: warning: incorrect type in argument 2 (different address spaces)
drivers/net/phy/mdio-octeon.c:56:9:    expected void volatile [noderef] <asn:2>*addr
drivers/net/phy/mdio-octeon.c:56:9:    got void *
drivers/net/phy/mdio-octeon.c:77:9: warning: incorrect type in argument 2 (different address spaces)
drivers/net/phy/mdio-octeon.c:77:9:    expected void volatile [noderef] <asn:2>*addr
drivers/net/phy/mdio-octeon.c:77:9:    got void *
drivers/net/phy/mdio-octeon.c:91:9: warning: incorrect type in argument 2 (different address spaces)
drivers/net/phy/mdio-octeon.c:91:9:    expected void volatile [noderef] <asn:2>*addr
drivers/net/phy/mdio-octeon.c:91:9:    got void *

Change the struct member to the regular 'void __iomem *' to keep
everything as expected, moving the conversion to u64 into the wrapper
for cvmx_read/write_csr.

Fixes: b8fb640643fc ("net: mdio-octeon: Fix Kconfig warnings and build errors")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>