[SUBMITTED 20200108] arm/ftrace: fix building on BE32
Compiling patch.c on BE32 fails because there is no definition
of __opcode_to_mem_thumb32()

arch/arm/kernel/patch.c: In function '__patch_text_real':
arch/arm/kernel/patch.c:94:11: error: implicit declaration of function '__opcode_to_mem_thumb32' [-Werror=implicit-function-declaration]

Since we don't actually call it, only a declaration is required
here, add one without a definition that fixes the build here
but will cause a link failure if someone actually relies on the
result.

Fixes: 5a735583b764 ("arm/ftrace: Use __patch_text()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
Not sure if this version is any less ugly than the first
approach of adding an #ifdef in patch.c