bcachefs: suppress warning on 64KB page size kernels
clang does not like the comparison of a 16-bit variable against a constant
PAGE_SIZE if that is outside of the range:

fs/bcachefs/super.c:954:25: error: result of comparison of constant 65536 with expression of type 'u16' (aka 'unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]

Add a check for the page size first so the compiler can see this is
intentional.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>