bfa: remove unused variables
Building with W=1 shows some warnings about local variables that
are initialized but never used:

bfa/bfad_attr.c: In function 'bfad_im_vport_delete':
bfa/bfad_attr.c:490:22: error: variable 'port' set but not used
bfa/bfa_fcs_rport.c: In function 'bfa_fcs_rport_process_adisc':
bfa/bfa_fcs_rport.c:2259:21: error: variable 'adisc' set but not used
bfa/bfa_fcpim.c: In function 'bfa_fcpim_lunmask_delete':
bfa/bfa_fcpim.c:2366:22: error: variable 'rp' set but not used
bfa/bfa_ioc.c: In function 'bfa_iocpf_sm_fwcheck_entry':
bfa/bfa_ioc.c:720:27: error: variable 'pgoff' set but not used
bfa/bfa_ioc.c: In function 'bfa_ioc_fwver_get':
bfa/bfa_ioc.c:1463:13: error: variable 'pgoff' set but not used
bfa/bfa_ioc.c: In function 'bfa_ioc_fwsig_invalidate':
bfa/bfa_ioc.c:1685:13: error: variable 'pgoff' set but not used
bfa/bfa_ioc.c: In function 'bfa_ioc_download_fw':
bfa/bfa_ioc.c:1884:13: error: variable 'pgoff' set but not used
bfa/bfa_ioc.c: In function 'bfa_diag_memtest_done':
bfa/bfa_ioc.c:4763:13: error: variable 'pgoff' set but not used
bfa/bfa_ioc.c: In function 'bfa_flash_fifo_flush':
bfa/bfa_ioc.c:6803:6: error: variable 't' set but not used
bfa/bfa_svc.c: In function 'uf_recv':
bfa/bfa_svc.c:5605:17: error: variable 'fchs' set but not used

This removes all those variables.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>