coredump: move dump_emit_page() into CONFIG_ELF_CORE check
If CONFIG_ELF_CORE is disabled, dump_emit_page() is unused, which
causes a warning:

fs/coredump.c:834:12: error: 'dump_emit_page' defined but not used [-Werror=unused-function]

There is only one caller, so move the definition next to it.

Fixes: 06bbaa6dc53c ("[coredump] don't use __kernel_write() on kmap_local_page()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>