maple_tree: try to reduce stack usage
While test building with a reduced warning limit, I came across two
warnings in this file, from various clang versions:

lib/maple_tree.c:3727:22: error: stack frame size (1296) exceeds limit (1280) in 'mas_wr_spanning_store' [-Werror,-Wframe-larger-than]
lib/maple_tree.c:4080:20: error: stack frame size (1296) exceeds limit (1280) in 'mas_wr_store_entry' [-Werror,-Wframe-larger-than]

The warning in mas_wr_store_entry() is from mas_wr_bnode() getting inlined
into its only caller, which is problematic here for all architectures, as
now both mas_wr_store_entry() and mas_wr_spanning_store() use over 1000 bytes
of stack space and are in the same call chain. Marking mas_wr_store_entry()
as noinline is the best fix here and will reduce the worst-case stack usage
on clang based builds.

The warning in mas_wr_spanning_store() does not have a good solution, the
problem here is that the function itself has multiple large structures on
the stack, which gets it close to my arbitrarily chosen limit of 1280 bytes
without KASAN, and slightly over the limit with KASAN enabled. Mark
mas_wr_walk_index() as noinline to keep the caller under the limit again.
Note that this does not use the noinline_for_kasan macro because the
problem happens also without CONFIG_KASAN_STACK.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>