[SUBMITTED 20211204] cachefiles: fix __cachefiles_prepare_write() error handling
clang points out that __cachefiles_prepare_write() returns an
uninitialized error code in one of the code paths:

fs/cachefiles/io.c:489:6: error: variable 'ret' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        if (pos == 0)
            ^~~~~~~~
fs/cachefiles/io.c:492:6: note: uninitialized use occurs here
        if (ret < 0) {
            ^~~
fs/cachefiles/io.c:489:2: note: remove the 'if' if its condition is always true
        if (pos == 0)
        ^~~~~~~~~~~~~
fs/cachefiles/io.c:440:9: note: initialize the variable 'ret' to silence this warning
        int ret;
               ^

Rework to return zero for success here and skip the rest of the
function.

Fixes: 0443b01eccbb ("cachefiles: Implement the I/O routines")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>