[SUBMITTED 20161116] phy: rockchip-inno-usb2: add extcon dependency
If extcon is a loadable module and rockchip-inno-usb2 is built-in,
we get a link failure:

drivers/phy/phy-rockchip-inno-usb2.o: In function `rockchip_usb2phy_probe':
phy-rockchip-inno-usb2.c:(.text.rockchip_usb2phy_probe+0x1ec): undefined reference to `extcon_get_edev_by_phandle'
phy-rockchip-inno-usb2.c:(.text.rockchip_usb2phy_probe+0x25c): undefined reference to `devm_extcon_dev_allocate'
phy-rockchip-inno-usb2.c:(.text.rockchip_usb2phy_probe+0x2a8): undefined reference to `devm_extcon_dev_register'
phy-rockchip-inno-usb2.c:(.text.rockchip_usb2phy_probe+0xa28): undefined reference to `extcon_register_notifier'

Adding a hard dependency avoids the problem. Alternatively we could
use "depends on EXTCON || !EXTCON" to allow building with extcon
disabled completely, but the other PHY drivers with extcon support
also just have a dependency, so this is more consistent.

Fixes: 0c42fe48fd23 ("phy: rockchip-inno-usb2: support otg-port for rk3399")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>