[SUBMITTED 20190305] [v2] xen: avoid link error on ARM
Building the privcmd code as a loadable module on ARM, we get
a link error due to the private cache management functions:

ERROR: "__sync_icache_dcache" [drivers/xen/xen-privcmd.ko] undefined!

Move the code into a new file that is always built in when Xen
is enabled, as suggested by Juergen Gross. Additional code will
be moved into this file later.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
v2: rename mm.o to xen-builtin.o, make it unconditional