[HACK] DMA_RESTRICTED_POOL: disable on nommu kernels
Not sure whether this is supposed to work or not, but using swiotlb on
nommu causes this build failure:

arm-linux-gnueabi-ld: kernel/dma/mapping.o: in function `dma_direct_sync_single_for_cpu':
mapping.c:(.text+0x1e2): undefined reference to `arch_sync_dma_for_cpu'
arm-linux-gnueabi-ld: kernel/dma/mapping.o: in function `dma_sync_single_for_device':
(.text+0x60e): undefined reference to `arch_sync_dma_for_device'
arm-linux-gnueabi-ld: kernel/dma/mapping.o: in function `dma_direct_map_page':
mapping.c:(.text+0x13e2): undefined reference to `arch_sync_dma_for_device'
arm-linux-gnueabi-ld: kernel/dma/direct.o: in function `dma_direct_map_page':
direct.c:(.text+0x47a): undefined reference to `arch_sync_dma_for_device'
arm-linux-gnueabi-ld: kernel/dma/direct.o: in function `dma_direct_alloc':
direct.c:(.text+0x824): undefined reference to `arch_dma_alloc'
arm-linux-gnueabi-ld: kernel/dma/direct.o: in function `dma_direct_free':
direct.c:(.text+0x920): undefined reference to `arch_dma_free'
arm-linux-gnueabi-ld: kernel/dma/direct.o: in function `dma_direct_sync_sg_for_device':
direct.c:(.text+0xa42): undefined reference to `arch_sync_dma_for_device'
arm-linux-gnueabi-ld: kernel/dma/direct.o: in function `dma_direct_sync_sg_for_cpu':
direct.c:(.text+0xaae): undefined reference to `arch_sync_dma_for_cpu'
arm-linux-gnueabi-ld: kernel/dma/direct.o: in function `dma_direct_unmap_sg':
direct.c:(.text+0xb66): undefined reference to `arch_sync_dma_for_cpu'
arm-linux-gnueabi-ld: kernel/dma/swiotlb.o: in function `swiotlb_map':

Signed-off-by: Arnd Bergmann <arnd@arndb.de>