[SUBMITTED 20210322] iwlwifi: fix old-style-declaration warning
The correct order is 'static const', not 'const static', as seen from
make W=1:

drivers/net/wireless/intel/iwlwifi/mvm/rfi.c:14:1: error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]

Fixes: 21254908cbe9 ("iwlwifi: mvm: add RFI-M support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>