pcmcia: badge4: avoid unused function warning
drivers/pcmcia/sa1111_badge4.c:153:122: error: 'pcmv_setup' defined but not used [-Werror=unused-function]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>