cpufreq: sc520: add switch fallthrough comment
gcc-8 warns about unannotated fallthrough statements:

In file included from include/linux/kernel.h:15,
                 from drivers/cpufreq/sc520_freq.c:14:
drivers/cpufreq/sc520_freq.c: In function 'sc520_freq_get_cpu_frequency':
include/linux/printk.h:304:2: error: this statement may fall through [-Werror=implicit-fallthrough=]
  printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/cpufreq/sc520_freq.c:43:3: note: in expansion of macro 'pr_err'
   pr_err("error: cpuctl register has unexpected value %02x\n",
   ^~~~~~
drivers/cpufreq/sc520_freq.c:45:2: note: here
  case 0x01:

I suppose this one fell through the global addition of the
comments because it only appears in rare configurations, found
during randconfig building.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>