Input: Apple SPI: don't imply MFD_INTEL_LPSS_PCI
The newly added driver causes a recursive Kconfig dependency
because of its 'imply MFD_INTEL_LPSS_PCI' statement.

arch/arm/Kconfig:1942:error: recursive dependency detected!
arch/arm/Kconfig:1942:	symbol XIP_KERNEL depends on KASAN
lib/Kconfig.kasan:15:	symbol KASAN depends on SYSFS
fs/sysfs/Kconfig:2:	symbol SYSFS is selected by CONFIGFS_FS
fs/configfs/Kconfig:2:	symbol CONFIGFS_FS is selected by USB_LIBCOMPOSITE
drivers/usb/gadget/Kconfig:145:	symbol USB_LIBCOMPOSITE is selected by USB_ZERO
drivers/usb/gadget/legacy/Kconfig:17:	symbol USB_ZERO is part of choice <choice>
drivers/usb/gadget/Kconfig:486:	choice <choice> contains symbol USB_G_WEBCAM
drivers/usb/gadget/legacy/Kconfig:479:	symbol USB_G_WEBCAM is part of choice VIDEO_V4L2
drivers/media/v4l2-core/Kconfig:7:	symbol VIDEO_V4L2 depends on I2C
drivers/i2c/Kconfig:8:	symbol I2C is selected by FB_DDC
drivers/video/fbdev/Kconfig:63:	symbol FB_DDC depends on FB
drivers/video/fbdev/Kconfig:12:	symbol FB is selected by DRM_KMS_FB_HELPER
drivers/gpu/drm/Kconfig:75:	symbol DRM_KMS_FB_HELPER depends on DRM_KMS_HELPER
drivers/gpu/drm/Kconfig:69:	symbol DRM_KMS_HELPER is selected by DRM_ARMADA
drivers/gpu/drm/armada/Kconfig:2:	symbol DRM_ARMADA depends on HAVE_CLK
arch/Kconfig:314:	symbol HAVE_CLK is selected by CLKDEV_LOOKUP
drivers/clk/Kconfig:3:	symbol CLKDEV_LOOKUP is selected by COMMON_CLK
drivers/clk/Kconfig:10:	symbol COMMON_CLK is selected by MFD_INTEL_LPSS
drivers/mfd/Kconfig:600:	symbol MFD_INTEL_LPSS is selected by MFD_INTEL_LPSS_PCI
drivers/mfd/Kconfig:614:	symbol MFD_INTEL_LPSS_PCI is implied by KEYBOARD_APPLESPI
drivers/input/keyboard/Kconfig:74:	symbol KEYBOARD_APPLESPI depends on EFI
arch/arm/Kconfig:2031:	symbol EFI depends on XIP_KERNEL

Since the driver can work without that, drop the statement to make it
build cleanly.

Fixes: b426ac045209 ("Input: add Apple SPI keyboard and trackpad driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>

fixup keyboard-applespi

/git/arm-soc/drivers/spi/spi-pxa2xx-pci.c:208:8: error: implicit declaration of function 'pcim_enable_device' [-Werror,-Wimplicit-function-declaration]
        ret = pcim_enable_device(dev);

Signed-off-by: Arnd Bergmann <arnd@arndb.de>

applespi again

Signed-off-by: Arnd Bergmann <arnd@arndb.de>