virtio: vdpa: fix possible string overflow
solidrun/snet_main.c:561:2: error: 'snprintf' size argument is too large; destination buffer has size 25, but size argument is 256 [-Werror,-Wfortify-source]
        snprintf(name, SNET_NAME_SIZE, "psnet[%s]-bars", pci_name(pdev));
        ^
solidrun/snet_main.c:581:2: error: 'snprintf' size argument is too large; destination buffer has size 20, but size argument is 256 [-Werror,-Wfortify-source]
        snprintf(name, SNET_NAME_SIZE, "snet[%s]-bar", pci_name(pdev));
        ^

Fixes: 73a720b16fa1 ("virtio: vdpa: new SolidNET DPU driver.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>