[SUBMITTED 20251204] drm/imx: select DRM_DISPLAY_HELPER as needed
CONFIG_DRM_BRIDGE_CONNECTOR is a bool option that turns on features of
the display helpers, which are in a module controlled by the (tristate)
CONFIG_DRM_DISPLAY_HELPER. If the display helpers are in a loadable
module, a built-in driver trying to use the bridge connectors fails
to link:

x86_64-linux-ld: drivers/gpu/drm/imx/ipuv3/parallel-display.o: in function `imx_pd_bind':
parallel-display.c:(.text+0xcd): undefined reference to `drm_bridge_connector_init'
x86_64-linux-ld: drivers/gpu/drm/imx/ipuv3/imx-ldb.o: in function `imx_ldb_bind':
imx-ldb.c:(.text+0x224): undefined reference to `drm_bridge_connector_init'

Select the DRM_BRIDGE_CONNECTOR symbol as well, to ensure it's built-in
if anything needs it.

Fixes: f94b9707a1c9 ("drm/imx: parallel-display: switch to imx_legacy_bridge / drm_bridge_connector")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>