x86: kvm: use BUG() instead of BUG_ON(1)
clang warns about an impossible uninitialized variable access after a
BUG_ON(1), as it cannot prove at compile time that this won't happen:

arch/x86/kvm/vmx/nested.c:5239:3: error: variable 'roots_to_free' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
                BUG_ON(1);
                ^~~~~~~~~

Use the simple BUG() here, will tells clang that anything afterwards
is unreachable.

Fixes: 55d2375e58a6 ("KVM: nVMX: Move nested code to dedicated files")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>