[SUBMITTED] kprobes: make wait_for_kprobe_optimizer as __maybe_unused
wait_for_kprobe_optimizer is only used when CONFIG_SYSCTL or CONFIG_DEBUG_FS
is enabled, otherwise we get a build warning

kernel/kprobes.c:566:13: error: 'wait_for_kprobe_optimizer' defined but not used [-Werror=unused-function]

This marks the function as __maybe_unused to shut up that warning.
We could do also add more #ifdef, but that would be a little more
ugly in this case.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>