ia64: fix sal default handler prototype
gcc warns about a broken cast when building with 'make W=1':

arch/ia64/kernel/sal.c:43:29: error: cast between incompatible function types from 'long int (*)(void)' to 'struct ia64_sal_retval (*)(u64, ...)' {aka 'struct ia64_sal_retval (*)(long long unsigned int, ...)'} [-Werror=cast-function-type]
   43 | ia64_sal_handler ia64_sal = (ia64_sal_handler) default_handler;

The calling conventions are indeed completely different between the
two, because of varargs and a struct return.

Change the dummy function to have the same prototype as the real
function.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>