[SUBMITTED 20190909] smack: include linux/watch_queue.h
In some randconfig builds, the lack of an explicit #include
in smack_lsm.c causes a build failure:

security/smack/smack_lsm.c:4384:7: error: incomplete definition of type 'struct watch_notification'
        if (n->type == WATCH_TYPE_META)
            ~^
include/linux/device.h:46:8: note: forward declaration of 'struct watch_notification'
struct watch_notification;
       ^
security/smack/smack_lsm.c:4384:17: error: use of undeclared identifier 'WATCH_TYPE_META'
        if (n->type == WATCH_TYPE_META)

Fixes: 5301fef8ca60 ("smack: Implement the watch_key and post_notification hooks [untested]")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>