[SUBMITTED 20210721] x86: boot: add a missing fallthrough statement
This instance seems to have slipped through the mass
conversions to the fallthrough keyword:

arch/x86/boot/printf.c:248:31: error: this statement may fall through [-Werror=implicit-fallthrough=]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>