drm/panel: simple panel depends on BACKLIGHT_CLASS_DEVICE
The of_find_backlight_by_node helper is provided by the
BACKLIGHT_CLASS_DEVICE code, so the simple panel code using
that must have a Kconfig dependency to avoid this build
error:

drivers/built-in.o: In function `panel_simple_probe':
:(.text+0x8ccac): undefined reference to `of_find_backlight_by_node'

We also require a dependency on the DRM_PANEL code, which is
used by this driver, and a dependency on DRM itself, to ensure
that the simple panel driver can only be built-in if DRM is
also built-in rather than a loadable module.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>