[SUBMITTED 20260216] smb: smbdirect: select CONFIG_SG_POOL
The smbdirect code now uses the scatter/gather pool interface. This
causes a build failure when the interface is disabled:

In file included from fs/smb/client/../common/smbdirect/smbdirect_all_c_files.c:21,
                 from fs/smb/client/smbdirect.c:176:
fs/smb/client/../common/smbdirect/smbdirect_rw.c: In function 'smbdirect_connection_rw_io_free':
fs/smb/client/../common/smbdirect/smbdirect_rw.c:76:9: error: implicit declaration of function 'sg_free_table_chained' [-Wimplicit-function-declaration]
   76 |         sg_free_table_chained(&msg->sgt, SG_CHUNK_SIZE);
      |         ^~~~~~~~~~~~~~~~~~~~~

The other users of this interface all 'select SG_POOL', so so the same
here.

Fixes: 5ab0987c492e ("smb: smbdirect: introduce smbdirect_rw.c with server rw code")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>