[SUBMITTED 20180328] amdkfd: always select MMU_NOTIFIER
Building amdkfd without MMU notifiers is broken:

In file included from drivers/gpu/drm/amd/amdkfd/kfd_mqd_manager_vi.c:28:
drivers/gpu/drm/amd/amdkfd/kfd_priv.h:584:22: error: field 'mmu_notifier' has incomplete type

This adds the missing 'select MMU_NOTIFIER' line to make it build
cleanly all the time.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>