Input: ixp4xx-beeper: shut up type cast warnings
The ixp4xx-beeper driver casts between int and void* in a few
places. This is all safe because it is never used as a pointer,
but it causes warnings on 64-bit targets when compile testing:

drivers/input/misc/ixp4xx-beeper.c:109:31: error: cast to 'void *' from smaller integer type 'int' [-Werror,-Wint-to-void-pointer-cast]
        input_set_drvdata(input_dev, (void *) dev->id);

Cast through uintptr_t to shut up these warnings.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>