x86: kdump: include newly added header file
Without this, we can get a warning about missing prototypes,
as the global function is now included in a header that is not
seen here:

arch/x86/kernel/setup.c:476:15: error: no previous prototype for 'crash_low_size_default' [-Werror=missing-prototypes]
  476 | unsigned long crash_low_size_default(void)
      |               ^~~~~~~~~~~~~~~~~~~~~~

Fixes: 6439d602ea1a7 ("x86: kdump: use generic interface to simplify crashkernel reservation code")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>