shmem: fix missing shmem_parse_huge
mm/shmem.c:3435:11: error: implicit declaration of function 'shmem_parse_huge' [-Werror,-Wimplicit-function-declaration]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>