[SUBMITTED 20160615] mm: compaction: fix dummy declarations
We get a build error in several test builds after a recent code rework:

In file included from include/linux/balloon_compaction.h:48:0,
                 from mm/balloon_compaction.c:11:
include/linux/compaction.h:237:122: error: 'struct node' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]

The patch that likely introduced the problem added a forward declaration
for 'struct node' in linux/compaction.h, but only in one of two instances.

This moves the declaration out of the #ifdef so we always get it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: akpm-current ("mm: migrate: support non-lru movable page migration")