[SUBMITTED 20190322] tty: serial: msm_geni_serial: set default baud rate to 115200
clang points out that without user specified options, we pass an
uninitialized variable as the baud rate, but have defaults for
the other settings (bits, parity, flow):

drivers/tty/serial/qcom_geni_serial.c:1079:6: error: variable 'baud' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        if (options)
            ^~~~~~~
drivers/tty/serial/qcom_geni_serial.c:1082:37: note: uninitialized use occurs here
        return uart_set_options(uport, co, baud, parity, bits, flow);
                                           ^~~~
drivers/tty/serial/qcom_geni_serial.c:1079:2: note: remove the 'if' if its condition is always true
        if (options)
        ^~~~~~~~~~~~
drivers/tty/serial/qcom_geni_serial.c:1053:10: note: initialize the variable 'baud' to silence this warning
        int baud;
                ^
                 = 0
1 error generated.

Picking an arbitrary sensible baud rate is clearly better than
using uninitialized memory. I'm picking 115200 here as that
is the default when the rate is set to zero.

Fixes: c4f528795d1a ("tty: serial: msm_geni_serial: Add serial driver support for GENI based QUP")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>