parisc: firmware: shut up unused function warnings
Two unused functions cause a warning in the defconfig build:

arch/parisc/boot/compressed/firmware.c:143:13: error: 'convert_to_wide' defined but not used [-Werror=unused-function]
  143 | static void convert_to_wide(unsigned long *addr)
      |             ^~~~~~~~~~~~~~~
arch/parisc/boot/compressed/firmware.c:121:22: error: 'f_extend' defined but not used [-Werror=unused-function]
  121 | static unsigned long f_extend(unsigned long address)
      |                      ^~~~~~~~

There are already enough #ifdef checks in this file, so instead of
adding even more, just mark these as __maybe_unused.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>