[SUBMITTED 20210125] bitfield: build kunit tests without structleak plugin
The structleak plugin causes the stack frame size to grow immensely:

lib/bitfield_kunit.c: In function 'test_bitfields_constants':
lib/bitfield_kunit.c:93:1: error: the frame size of 7440 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]

Turn it off in this file.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>

[SUBMITTED 20210125] thunderbolt: build kunit tests without structleak plugin

The structleak plugin causes the stack frame size to grow immensely:

drivers/thunderbolt/test.c:1529:1: error: the frame size of 1176 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Turn it off in this file.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>

mmc: aspeed: build kunit tests without structleak plugin

The structleak plugin causes the stack frame size to grow immensely:

drivers/mmc/host/sdhci-of-aspeed-test.c: In function 'aspeed_sdhci_phase_ddr52':
drivers/mmc/host/sdhci-of-aspeed-test.c:47:1: error: the frame size of 1152 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Turn it off in this file.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>

fix up struct leak disable

Signed-off-by: Arnd Bergmann <arnd@arndb.de>

fixup! fix up struct leak disable

Signed-off-by: Arnd Bergmann <arnd@arndb.de>