[SUBMITTED 20230622] drm/amdgpu: fix building without DEBUG_FS
The debugfs file is defined unconditionally, but the registration is hidden
in an #ifdef, which causes a warning:

drivers/gpu/drm/amd/amdgpu/amdgpu_rap.c:110:37: error: unused variable 'amdgpu_rap_debugfs_ops' [-Werror,-Wunused-const-variable]
static const struct file_operations amdgpu_rap_debugfs_ops = {
                                    ^

in amdgpu_pm.c, the same thing happens with the clocks[] variable:

drivers/gpu/drm/amd/pm/amdgpu_pm.c:38:34: error: unused variable 'clocks' [-Werror,-Wunused-const-variable]
static const struct cg_flag_name clocks[] = {
                                 ^

Since debugfs_create_file() does nothing when debugfs is disabled, removing
the ifdefs makes the code more readable and also avoids both warnings.

Fixes: a4322e1881bed ("drm/amdgpu: add debugfs interface for RAP test")
Fixes: e098bc9612c2b ("drm/amd/pm: optimize the power related source code layout")
Reported-by: kernel test robot <lkp@intel.com>
Link: https://lore.kernel.org/oe-kbuild-all/202302200339.Whql7Emr-lkp@intel.com/
Signed-off-by: Arnd Bergmann <arnd@arndb.de>