[SUBMITTED 20180328] nvme: use upper_32_bits() instead of bit shift
On 32-bit architectures, we cannot shift a size_t by 32 bits to the right
without a compiler warning:

drivers/nvme/host/core.c: In function 'nvme_get_log_ext':
drivers/nvme/host/core.c:2237:43: error: right shift count >= width of type [-Werror=shift-count-overflow]
  c.get_log_page.lpou = cpu_to_le32(offset >> 32ULL);
                                           ^~
include/uapi/linux/byteorder/little_endian.h:33:51: note: in definition of macro '__cpu_to_le32'
 #define __cpu_to_le32(x) ((__force __le32)(__u32)(x))
                                                   ^
drivers/nvme/host/core.c:2237:24: note: in expansion of macro 'cpu_to_le32'
  c.get_log_page.lpou = cpu_to_le32(offset >> 32ULL);

The code is correct, but using the upper_32_bits() and lower_32_bits()
macros that were introduced for this operation makes it easier to read
and avoids the warning.

Fixes: 70da6094a646 ("nvme: implement log page low/high offset and dwords")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>