drm/amd/display: move mod_info_packet.h to amdgpu_dm/
In file included from drivers/gpu/drm/amd/amdgpu/../amdgpu/amdgpu.h:90,
                 from drivers/gpu/drm/amd/amdgpu/../pm/amdgpu_dpm_internal.c:24:
drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.h:62:10: fatal error: mod_info_packet.h: No such file or directory

Fixes: e95afc1cf7c6 ("drm/amd/display: Enable AdaptiveSync in DC interface")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>