[SUBMITTED 20201204] firmware: tegra: bpmp: fix T234 build failure
When only Tegra 234 is enabled, the bpmp driver fails
to build:

drivers/firmware/tegra/bpmp.c:861:51: error: 'tegra186_soc' undeclared here (not in a function)
  861 |  { .compatible = "nvidia,tegra186-bpmp", .data = &tegra186_soc },
      |                                                   ^~~~~~~~~~~~

Fix the #ifdef statement to match the location in which this
symbol is used.

Fixes: 0ebdf11699d0 ("firmware: tegra: Enable BPMP support on Tegra234")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>