[SUBMITTED 20180328] crypto: chelsio: move chcr_ahash_continue declation out of header
static function declarations don't belong in a header file, as shown
by this compiler warning:

In file included from /git/arm-soc/drivers/crypto/chelsio/chcr_ipsec.c:66:
drivers/crypto/chelsio/chcr_crypto.h:343:12: error: 'chcr_ahash_continue' declared 'static' but never defined [-Werror=unused-function]

This moves the declaration into the file that actually needs it.

Fixes: 5110e65536f3 ("crypto: chelsio -Split Hash requests for large scatter gather list")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>