Input: imagis - remove incorrect ifdef checks
When CONFIG_OF is disabled, three variables become unused:

drivers/input/touchscreen/imagis.c:391:39: error: unused variable 'imagis_3032c_data' [-Werror,-Wunused-const-variable]
drivers/input/touchscreen/imagis.c:399:39: error: unused variable 'imagis_3038b_data' [-Werror,-Wunused-const-variable]
drivers/input/touchscreen/imagis.c:407:39: error: unused variable 'imagis_3038c_data' [-Werror,-Wunused-const-variable]

There is no real point in building this driver without CONFIG_OF,
so just remove the #ifdef checks and just always build this to avoids
the warnings.

Fixes: 10ad7d7a428f ("input/touchscreen: imagis: Add support for Imagis IST3038B")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>