ASoC: amd: yc: add ACPI dependency
The acp6x driver now fails to build when ACPI is disabled:

sound/soc/amd/yc/acp6x-mach.c: In function 'acp6x_probe':
sound/soc/amd/yc/acp6x-mach.c:580:15: error: implicit declaration of function 'acpi_evaluate_integer'; did you mean 'acpi_evaluate_object'? [-Wimplicit-function-declaration]

Add a Kconfig dependency to ensure it can always be compiled in
all configurations.

Fixes: 4095cf872084 ("ASoC: amd: yc: Fix for enabling DMIC on acp6x via _DSD entry")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>