[SUBMITTED] serial: fsl-lpuart: move SERIAL_EARLYCON dependency to console
The newly added earlycon support for lpuart adds a
'select SERIAL_EARLYCON' statement for the tty driver, but that
only uses earlycon when console support is present, and otherwise
results in a pointless build error:

drivers/built-in.o: In function `setup_earlycon':
:(.init.text+0x2c4c): undefined reference to `uart_parse_earlycon'

This changes the Kconfig statement to only select the earlycon
code if the console is also enabled, like all the other drivers
do already.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 1d59b382f1c4 ("serial: fsl_lpuart: add earlycon support")