usb: gadget: omap_udc: remove unused variable
The driver_desc variable is only used in some configurations:

drivers/usb/gadget/udc/omap_udc.c:113:19: error: unused variable 'driver_desc' [-Werror,-Wunused-const-variable]

Since there is only ever one user of it, just open-code the string in place
and remove the global variable and the macro behind it. This also helps
grep for the MODULE_DESCRIPTION string.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>