lightnvm: provide a proper struct nvm_dev_ops structure
clang refuses to build the lightnvm / null_blk code when CONFIG_NVM
is disabled:

drivers/block/null_blk.c:568:27: error: tentative definition has type 'struct nvm_dev_ops' that is never completed
static struct nvm_dev_ops null_lnvm_dev_ops;
../include/linux/lightnvm.h:432:8: note: forward declaration of 'struct nvm_dev_ops'
struct nvm_dev_ops;

This changes the forward declaration of struct nvm_dev_ops
to an empty definition so the code becomes valid but does not
consume any space in .data.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>