ARM: futex: use TUSERCOND() instead of TUSER() macro
Clang's integrated assembler rejects the 'streqt' opcode that
the GNU assembler sees as valid:

arch/arm/include/asm/futex.h:117:3: error: invalid instruction, did you mean: strt?
"2: " TUSER(streq) " %4, [%2]\n"
:6:4: note: instantiated into assembly here
      2: streqt r8, [r7]

This happens on configurations with CONFIG_CPU_USE_DOMAINS.

The TUSERCOND() macro was designed to handle that, so use it in
place of TUSER() on this instruction.

Link: https://github.com/ClangBuiltLinux/linux/issues/1273
Signed-off-by: Arnd Bergmann <arnd@arndb.de>