[SUBMITTED 20201204] PCI: dwc: exynos: add back MSI dependency
While the exynos driver does not always need MSI, the generic
deisgnware host code it uses fails to build without it:

WARNING: unmet direct dependencies detected for PCIE_DW_HOST
  Depends on [n]: PCI [=y] && PCI_MSI_IRQ_DOMAIN [=n]
  Selected by [y]:
  - PCI_EXYNOS [=y] && PCI [=y] && (ARCH_EXYNOS [=n] || COMPILE_TEST [=y])
drivers/pci/controller/dwc/pcie-designware-host.c:247:19: error: implicit declaration of function 'pci_msi_create_irq_domain' [-Werror,-Wimplicit-function-declaration]
        pp->msi_domain = pci_msi_create_irq_domain(fwnode,
                         ^

Add back the dependency that all other designware controllers have.

Fixes: f0a6743028f9 ("PCI: dwc: exynos: Rework the driver to support Exynos5433 variant")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
merge conflict: check before resending