[SUBMITTED 20190708] btrfs: add back libcrc32c Kconfig dependency
While part of btrfs now uses the crypto shash interfaces
for crc32c, we still get a build time dependency in other
places:

fs/btrfs/super.o: In function `btrfs_mount_root':
super.c:(.text+0xc0d4): undefined reference to `crc32c_impl'
fs/btrfs/super.o: In function `btrfs_print_mod_info':
super.c:(.init.text+0x3e28): undefined reference to `crc32c_impl'
fs/btrfs/extent-tree.o: In function `lookup_inline_extent_backref':
extent-tree.c:(.text+0x17750): undefined reference to `crc32c'
fs/btrfs/extent-tree.o:extent-tree.c:(.text+0x177f4): more undefined references to `crc32c' follow

Change Kconfig to depend on both.

Fixes: d5178578bcd4 ("btrfs: directly call into crypto framework for checksumming")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>