[SUBMITTED] usb: xhci: fix build error for USB_SPEED_SUPER_PLUS
A recent patch introduced support for superspeed plus (USB3.1), but that
caused a new gcc warning in the XHCI code:

usb/host/xhci.c: In function 'xhci_drop_ep_from_interval_table':
usb/host/xhci.c:2440:2: error: enumeration value 'USB_SPEED_SUPER_PLUS' not handled in switch [-Werror=switch]

This changes the XHCI driver to handle USB_SPEED_SUPER_PLUS the
same way as USB_SPEED_SUPER in the xhci_drop_ep_from_interval_table
and xhci_add_ep_to_interval_table functions, explicitly ignoring
it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 8a1b2725a60d ("usb: define USB_SPEED_SUPER_PLUS speed for SuperSpeedPlus USB3.1 devices")