ARM: rpc: ecard: fix unused-function warning
When CONFIG_PROC_FS is disabled, gcc warns about an
unused function:

arch/arm/mach-rpc/ecard.c:650:12: error: unused function 'ecard_devices_proc_show' [-Werror,-Wunused-function]

Mark it as __maybe_unused to avoid adding an extra #ifdef.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>