x86: uaccess: void '=q' constraint in inline asm
clang produces a warning when a 64-bit variable is passed into
__get_user:

arch/x86/kernel/signal.c:642:6: error: invalid output size for constraint '=q'
        if (__get_user(*(__u64 *)&set, (__u64 __user *)&frame->uc.uc_sigmask))
            ^
arch/x86/include/asm/uaccess.h:419:2: note: expanded from macro '__get_user'
        __get_user_nocheck((x), (ptr), sizeof(*(ptr)))
        ^
arch/x86/include/asm/uaccess.h:374:18: note: expanded from macro '__get_user_nocheck'
        __get_user_size(__gu_val, __gu_ptr, __gu_size, __gu_err);       \
                        ^

The problem is that clang evaluates the asm constraints for all
code paths, while gcc discards unused ones first and then does
not warn about this case.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>