[SUBMITTED 20230214] media: imx-jpeg: avoid array overflow
gcc-9 (unlike newer versions) reports a possible array overflow
in mxc_jpeg_dec_irq():

drivers/media/platform/nxp/imx-jpeg/mxc-jpeg.c: In function 'mxc_jpeg_dec_irq':
drivers/media/platform/nxp/imx-jpeg/mxc-jpeg.c:641:28: error: array subscript 2 is above array bounds of 'u32[2]' {aka 'unsigned int[2]'} [-Werror=array-bounds]
  641 |   size += q_data->sizeimage[i];
      |           ~~~~~~~~~~~~~~~~~^~~
drivers/media/platform/nxp/imx-jpeg/mxc-jpeg.c:641:28: error: array subscript 3 is above array bounds of 'u32[2]' {aka 'unsigned int[2]'} [-Werror=array-bounds]

The compiler clearly deduces that fmt->mem_planes is at least '2' if
this code line is reached, and that fmt->comp_planes must be at least
one more for the loop to make sense. However, this does not actually
seem to be the case in the initialized values, so I would guess that
this part of the function is never reached in practice.

As a workaround, add a compile-time condition that skips any out-of-range
array indices.

Fixes: ccc9f1db9c6b ("media: imx-jpeg: Support contiguous and non contiguous format")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>