ARM: add missing arch_irqs_disabled function
When building with CONFIG_DEBUG_LOCK_ALLOC and CONFIG_PREEMPT_COUNT,
the generic rcu_read_lock_sched_held function requires a definition
of arch_irqs_disabled. All other architectures provide this, so
this patch adds the trivial wrapper around arch_irqs_disabled_flags()
that a lot of the others use as well.

include/linux/rcupdate.h: In function 'rcu_read_lock_sched_held':
include/linux/rcupdate.h:516:2: error: implicit declaration of function 'arch_irqs_disabled'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>