ARM: davinci: dm365_evm_snd_data was removed
arch/arm/mach-davinci/board-dm365-evm.c: In function 'dm365_evm_init':
arch/arm/mach-davinci/board-dm365-evm.c:764:17: error: 'dm365_evm_snd_data' undeclared (first use in this function)

Signed-off-by: Arnd Bergmann <arnd@arndb.de>