alsa: define non-empty lock dummy
seq/seq_clientmgr.c: In function 'snd_seq_deliver_single_event':
seq/seq_clientmgr.c:646:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_port_unlock(dest_port);
   ^
seq/seq_clientmgr.c:648:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_client_unlock(dest);
   ^
seq/seq_clientmgr.c: In function 'snd_seq_ioctl_subscribe_port':
seq/seq_clientmgr.c:1486:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_port_unlock(sport);
   ^
seq/seq_clientmgr.c:1488:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_port_unlock(dport);
   ^
seq/seq_clientmgr.c:1490:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_client_unlock(sender);
   ^
seq/seq_clientmgr.c:1492:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_client_unlock(receiver);
   ^
seq/seq_clientmgr.c: In function 'snd_seq_ioctl_unsubscribe_port':
seq/seq_clientmgr.c:1530:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_port_unlock(sport);
   ^
seq/seq_clientmgr.c:1532:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_port_unlock(dport);
   ^
seq/seq_clientmgr.c:1534:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_client_unlock(sender);
   ^
seq/seq_clientmgr.c:1536:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_client_unlock(receiver);
   ^
seq/seq_clientmgr.c: In function 'snd_seq_ioctl_get_subscription':
seq/seq_clientmgr.c:2021:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_port_unlock(sport);
   ^
seq/seq_clientmgr.c:2023:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_client_unlock(sender);
   ^
seq/seq_clientmgr.c: In function 'snd_seq_ioctl_query_subs':
seq/seq_clientmgr.c:2091:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_port_unlock(port);
   ^
seq/seq_clientmgr.c:2093:3: error: suggest braces around empty body in an 'if' statement
   snd_seq_client_unlock(cptr);
   ^
cc1: all warnings being treated as errors
/git/arm-soc/scripts/Makefile.build:289: recipe for target 'sound/core/seq/seq_clientmgr.o' failed
make[5]: *** [sound/core/seq/seq_clientmgr.o] Error 1
seq/seq_queue.c: In function 'queueptr':
seq/seq_queue.c:230:3: error: suggest braces around empty body in an 'if' statement
   snd_use_lock_use(&q->use_lock);
   ^
cc1: all warnings being treated as errors
/git/arm-soc/scripts/Makefile.build:289: recipe for target 'sound/core/seq/seq_queue.o' failed
make[5]: *** [sound/core/seq/seq_queue.o] Error 1
seq/seq_ports.c: In function 'snd_seq_port_query_nearest':
seq/seq_ports.c:105:4: error: suggest braces around empty body in an 'else' statement
    snd_use_lock_use(&found->use_lock);
    ^
cc1: all warnings being treated as errors
/git/arm-soc/scripts/Makefile.build:289: recipe for target 'sound/core/seq/seq_ports.o' failed
make[5]: *** [sound/core/seq/seq_ports.o] Error 1
seq/oss/seq_oss_synth.c: In function 'get_sdev':
seq/oss/seq_oss_synth.c:201:3: error: suggest braces around empty body in an 'if' statement
   snd_use_lock_use(&rec->use_lock);
   ^
cc1: all warnings being treated as errors
/git/arm-soc/scripts/Makefile.build:289: recipe for target 'sound/core/seq/oss/seq_oss_synth.o' failed
make[6]: *** [sound/core/seq/oss/seq_oss_synth.o] Error 1
seq/oss/seq_oss_midi.c: In function 'get_mdev':
seq/oss/seq_oss_midi.c:114:3: error: suggest braces around empty body in an 'if' statement
   snd_use_lock_use(&mdev->use_lock);
   ^
cc1: all warnings being treated as errors
/git/arm-soc/scripts/Makefile.build:289: recipe for target 'sound/core/seq/oss/seq_oss_midi.o' failed
make[6]: *** [sound/core/seq/oss/seq_oss_midi.o] Error 1
make[6]: Target '__build' not remade because of errors.
/git/arm-soc/scripts/Makefile.build:440: recipe for target 'sound/core/seq/oss' failed
make[5]: *** [sound/core/seq/oss] Error 2
make[5]: Target '__build' not remade because of errors.
/git/arm-soc/scripts/Makefile.build:440: recipe for target 'sound/core/seq' failed
make[4]: *** [sound/core/seq] Error 2
make[4]: Target '__build' not remade because of errors.
/git/arm-soc/scripts/Makefile.build:440: recipe for target 'sound/core' failed
make[3]: *** [sound/core] Error 2
make[3]: Target '__build' not remade because of errors.
/git/arm-soc/Makefile:994: recipe for target 'sound' failed
make[2]: *** [sound] Error 2

Signed-off-by: Arnd Bergmann <arnd@arndb.de>