[SUBMITTED 20211026] mt76: mt7663s: fix link error with CONFIG_PM=n
The generic register access functions are compiled conditionally,
causing a link failure in some randconfig builds:

ERROR: modpost: "mt76_connac_mcu_reg_wr" [drivers/net/wireless/mediatek/mt76/mt7615/mt7663s.ko] undefined!
ERROR: modpost: "mt76_connac_mcu_reg_rr" [drivers/net/wireless/mediatek/mt76/mt7615/mt7663s.ko] undefined!

Move them out of the #ifdef block.

Fixes: 02fbf8199f6e ("mt76: mt7663s: rely on mcu reg access utility")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>