amdgpu: avoid gcc-7 warning
gcc-7 warns about the return code of amdgpu_dpm_read_sensor() macro
being used as a boolean, since this can be a number literal:

drivers/gpu/drm/amd/amdgpu/amdgpu_pm.c: In function 'amdgpu_debugfs_pm_info_pp':
drivers/gpu/drm/amd/amdgpu/amdgpu_pm.c:1286:135: error: ?: using integer constants in boolean context [-Werror=int-in-bool-context]

Ideally we'd convert the macro into an inline function, as that would
avoid the problem and make it more readable, however I couldn't figure
out how to do that because of circular header file dependencies around
struct amdgpu_device.

Comparing the result against zero is not as nice, but manages to shut
up the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>