[SUBMITTED 20211027] firmware: qcom: scm: fix non-SMP build
A check was added for non-arm platforms, but the same code
is still broken on Arm non-SMP:

ERROR: modpost: "__cpu_logical_map" [drivers/firmware/qcom-scm.ko] undefined!

Fixes: c50031f03dfe ("firmware: qcom: scm: Don't break compile test on non-ARM platforms")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>