tty: hvc_xen: hide xen_console_remove when unused
hvc/hvc_xen.c:350:12: error: 'xen_console_remove' defined but not used [-Werror=unused-function]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>