[SUBMITTED 20170419] drm/omap: displays: panel-dpi: add backlight dependency
The panel driver gained support for backlight but fails to link now
when that is disabled:

drivers/gpu/drm/omapdrm/displays/panel-dpi.o: In function `panel_dpi_probe_of':
panel-dpi.c:(.text.panel_dpi_probe_of+0xe8): undefined reference to `of_find_backlight_by_node'

This adds a dependency like we have for the other panel drivers.

Fixes: 39135a305a0f ("drm/omap: displays: panel-dpi: Support for handling backlight devices")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>