[SUBMITTED 20190322] scsi: gdth: fix uninitialized variable use
clang -Wuninitialized finds a case in which we try to free
DMA memory without having allocated it first, i.e. when
both gen.data_len and gen.sense_len are zero:

drivers/scsi/gdth.c:3662:6: error: variable 'paddr' is used uninitialized whenever 'if' condition is false
      [-Werror,-Wsometimes-uninitialized]
        if (gen.data_len + gen.sense_len > 0) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/scsi/gdth.c:3701:4: note: uninitialized use occurs here
                        paddr);
                        ^~~~~
drivers/scsi/gdth.c:3662:2: note: remove the 'if' if its condition is always true
        if (gen.data_len + gen.sense_len > 0) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/scsi/gdth.c:3646:18: note: initialize the variable 'paddr' to silence this warning
        dma_addr_t paddr;
                        ^
                         = 0

Presumably this is harmless because a dma_free_coherent() with
buf=NULL and size=0 should not use the paddr argument but do
nothing, but it makes sense to explicitly skip the bogus free()
here.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>