[SUBMITTED 20170110] scsi: qedi: select UIO
The newly added qedi driver links against the UIO framework, but can
be built without that:

drivers/scsi/qedi/qedi_main.o: In function `qedi_free_uio':
qedi_main.c:(.text.qedi_free_uio+0x78): undefined reference to `uio_unregister_device'
drivers/scsi/qedi/qedi_main.o: In function `qedi_ll2_recv_thread':
qedi_main.c:(.text.qedi_ll2_recv_thread+0x18c): undefined reference to `uio_event_notify'
drivers/scsi/qedi/qedi_main.o: In function `__qedi_probe.constprop.1':
qedi_main.c:(.text.__qedi_probe.constprop.1+0x1368): undefined reference to `__uio_register_device'

This adds a compile-time dependency.

Fixes: ace7f46ba5fd ("scsi: qedi: Add QLogic FastLinQ offload iSCSI driver framework.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>