[SUBMITTED 20250225] rtc: fsl-ftm: remove incorrect ACPI_PTR annotation
Building with W=1 shows a warning about ftm_imx_acpi_ids being unused when
CONFIG_ACPI is disabled:

drivers/rtc/rtc-fsl-ftm-alarm.c:312:36: error: unused variable 'ftm_imx_acpi_ids' [-Werror,-Wunused-const-variable]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>