[SUBMITTED 20200408] drm/amdgpu/display: avoid unused-variable warning
Without CONFIG_DEBUG_FS, this newly added function causes a harmless
warning:

amdgpu_dm/amdgpu_dm.c: In function 'amdgpu_dm_connector_late_register':
amdgpu_dm/amdgpu_dm.c:4723:30: error: unused variable 'amdgpu_dm_connector' [-Werror=unused-variable]
 4723 |  struct amdgpu_dm_connector *amdgpu_dm_connector =
      |                              ^~~~~~~~~~~~~~~~~~~

Use an IS_ENABLED() check instead to let the compiler see what
is going on.

Fixes: 14f04fa4834a ("drm/amdgpu/display: add a late register connector callback")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>