mmc: aspeed: build kunit tests without structleak plugin
The structleak plugin causes the stack frame size to grow immensely:

drivers/mmc/host/sdhci-of-aspeed-test.c: In function 'aspeed_sdhci_phase_ddr52':
drivers/mmc/host/sdhci-of-aspeed-test.c:47:1: error: the frame size of 1152 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Turn it off in this file.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>