[SUBMITTED 20210920] PCI: rcar: add COMMON_CLK dependency
The __clk_is_enabled() interface is only available when building for
platforms using CONFIG_COMMON_CLK:

arm-linux-gnueabi-ld: drivers/pci/controller/pcie-rcar-host.o: in function `rcar_pcie_aarch32_abort_handler':
pcie-rcar-host.c:(.text+0x8fc): undefined reference to `__clk_is_enabled'

Add the necessary dependency to the COMPILE_TEST path.

Fixes: a115b1bd3af0 ("PCI: rcar: Add L1 link state fix into data abort hook")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>