arm64: KVM: shut up override-init warning
arm_exit_handlers[] now has a global default initializer for all members that
we override for the ones that have their own, which in turn causes a warning
with "make W=1":

arch/arm64/kvm/handle_exit.c:151:21: error: initialized field overwritten [-Werror=override-init]
  [ESR_ELx_EC_WFx] = kvm_handle_wfx,
arch/arm64/kvm/handle_exit.c:151:21: note: (near initialization for 'arm_exit_handlers[1]')
arch/arm64/kvm/handle_exit.c:152:25: error: initialized field overwritten [-Werror=override-init]
  [ESR_ELx_EC_CP15_32] = kvm_handle_cp15_32,
arch/arm64/kvm/handle_exit.c:152:25: note: (near initialization for 'arm_exit_handlers[3]')
arch/arm64/kvm/handle_exit.c:153:25: error: initialized field overwritten [-Werror=override-init]
  [ESR_ELx_EC_CP15_64] = kvm_handle_cp15_64,

This explicitly turns off the warning for the array.

Fixes: ba4dd156eabd ("arm64: KVM: Survive unknown traps from guests")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>