[SUBMITTED 20210421] habanalabs: fix enum type mismatch
The definition of these two arrays does not match the type of the
enums in them:

drivers/misc/habanalabs/goya/goya.c:136:21: error: implicit conversion from 'enum goya_pll_index' to 'enum pll_index' [-Werror=enum-conversion]
  136 |         [CPU_PLL] = GOYA_CPU_PLL,
drivers/misc/habanalabs/gaudi/gaudi.c:126:21: error: implicit conversion from 'enum gaudi_pll_index' to 'enum pll_index' [-Werror=enum-conversion]
  126 |         [CPU_PLL] = GAUDI_CPU_PLL,

Remove the enum and just use literal numbers, which avoids the
warning and is more concise without really losing any information.

Fixes: e8f9392a5c7f ("habanalabs: support legacy and new pll indexes")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>