ARM: rpc: ecard: use designated intializers
gcc-8 warns about the use of positional initializers:

arch/arm/mach-rpc/ecard.c:414:2: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
  ecard_def_irq_enable,

Change to the designated initializer used elsewhere in the kernel.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>