[SUBMITTED 20170201] Revert "staging: vc04_services: Make vchi_msg_queue static"
an alternative fix was proposed, this is my original patch

This reverts commit 203804300820c2c1ed28f9868c0fbd67b816cef3, the function that
was originally exported was previously unused, but is now needed by

drivers/staging/bcm2835-audio/bcm2835-vchiq.c: In function 'bcm2835_vchi_msg_queue':
drivers/staging/bcm2835-audio/bcm2835-vchiq.c:97:9: error: implicit declaration of function 'vchi_msg_queue';did you mean 'vchi_msg_dequeue'? [-Werror=implicit-function-declaration]
drivers/staging/media/platform/bcm2835/mmal-vchiq.c: In function 'buffer_from_host':
drivers/staging/media/platform/bcm2835/mmal-vchiq.c:453:8: error: implicit declaration of function 'vchi_msg_queue';did you mean 'vchi_msg_dequeue'? [-Werror=implicit-function-declaration]

It's possible that we want to get the patch back later, but we can't do it until
the users are changed to something else.

Fixes: 203804300820 ("staging: vc04_services: Make vchi_msg_queue static")
Fixes: 23b028c871e1 ("staging: bcm2835-audio: initial staging submission")
Fixes: 7b3ad5abf027 ("staging: Import the BCM2835 MMAL-based V4L2 camera driver.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>