[DONT APPLY] modify v7_exit_coherency_flush clobber list
clang points out a problem with the clobber list of the inline asm in
v7_exit_coherency_flush() when building with CONFIG_THUMB2_KERNEL:

arch/arm/mach-versatile/dcscb.c:95:2: error: inline asm clobber list contains reserved registers: R7 [-Werror,-Winline-asm]
        v7_exit_coherency_flush(louis);
        ^
arch/arm/include/asm/cacheflush.h:460:2: note: expanded from macro 'v7_exit_coherency_flush'
        ".arch  armv7-a \n\t" \
        ^
<inline asm>:1:1: note: instantiated into assembly here
        .arch   armv7-a

Changing the clobber list is clearly wrong but shuts up that error
message. If anyone has an idea how to fix it correctly, please send
a patch.

Fixes: 11b277eabe70 ("ARM: vexpress/TC2: basic PM support")
Fixes: e8f9bb1bd6bb ("ARM: vexpress/dcscb: fix cache disabling sequences")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>