net: pse-pd: fix regulator dependency
Building without regulator support causes a link error:

ld: drivers/net/pse-pd/pse_core.o: in function `pse_pi_is_enabled':
pse_core.c:(.text+0x54): undefined reference to `rdev_get_drvdata'
ld: pse_core.c:(.text+0x62): undefined reference to `rdev_get_id'
ld: drivers/net/pse-pd/pse_core.o: in function `pse_pi_disable':
pse_core.c:(.text+0x92): undefined reference to `rdev_get_drvdata'
ld: pse_core.c:(.text+0xa4): undefined reference to `rdev_get_id'
ld: drivers/net/pse-pd/pse_core.o: in function `pse_pi_enable':
pse_core.c:(.text+0xe4): undefined reference to `rdev_get_drvdata'
ld: pse_core.c:(.text+0xf6): undefined reference to `rdev_get_id'

An earlier patch added a dependency with an optional CONFIG_COMPILE_TEST
alternative, but this no longer works as it has become a hard dependency
now. This is not a big deal for build testing either since allmodconfig
and most randconfig builds still have regulators enabled anyway.

Fixes: d83e13761d5b ("net: pse-pd: Use regulator framework within PSE framework")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---