ARM: rpc: remove unused io-acorn.S
When CONFIG_PRINTK is disabled, this causes a link failure:

arm-linux-gnueabi-ld: arch/arm/mach-rpc/io-acorn.o: in function `outsl':
(.text+0x38): undefined reference to `_printk'

It appears like these functions have never actually had any
callers themselves and are not declared in a header, but were
copied from an early version of the ebsa110 platform.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>