irqchip: build IMX_MU_MSI only on ARM
compile-testing IMX_MU_MSI on x86 without PCI_MSI support results
in a build failure:

arch/x86/kernel/hpet.c:520:46: error: 'msi_alloc_info_t' {aka 'struct irq_alloc_info'} has no member named 'hwirq'
  520 |         irq_domain_set_info(domain, virq, arg->hwirq, info->chip, NULL,
      |                                              ^~
arch/x86/kernel/hpet.c:521:49: error: 'msi_alloc_info_t' {aka 'struct irq_alloc_info'} has no member named 'data'
  521 |                             handle_edge_irq, arg->data, "edge");
      |                                                 ^~
arch/x86/kernel/hpet.c: In function 'hpet_create_irq_domain':
arch/x86/kernel/hpet.c:550:13: error: 'x86_vector_domain' undeclared (first use in this function)
  550 |         if (x86_vector_domain == NULL)
      |             ^~~~~~~~~~~~~~~~~
arch/x86/kernel/hpet.c:550:13: note: each undeclared identifier is reported only once for each function it appears in
arch/x86/kernel/hpet.c: In function 'hpet_assign_irq':
arch/x86/kernel/hpet.c:600:9: error: implicit declaration of function 'init_irq_alloc_info' [-Werror=implicit-function-declaration]
  600 |         init_irq_alloc_info(&info, NULL);

Tighten the dependency further to only allow compile testing on Arm.
This could be refined further to allow certain x86 configs.

Fixes: 6c9f7434159b ("irqchip: IMX_MU_MSI should depend on ARCH_MXC")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>