[SUBMITTED 20210802] x86/asm: fix gcc-5 enqcmds() build failure
Building drivers/dma/idxd/submit.o with gcc-5.5 results in a cryptic
error messages:

arch/x86/include/asm/special_insns.h: Assembler messages:
arch/x86/include/asm/special_insns.h:286: Error: operand size mismatch for `setz'
make[5]: *** [scripts/Makefile.build:272: drivers/dma/idxd/submit.o] Error 1

It seems that this happens for 32-bit arguments when the instruction
expects an 8-bit argument. Change the type of the local variable
accordingly to get a clean build.

Fixes: 7f5933f81bd8 ("x86/asm: Add an enqcmds() wrapper for the ENQCMDS instruction")
Fixes: 8e50d392652f ("dmaengine: idxd: Add shared workqueue support") # guessed
Signed-off-by: Arnd Bergmann <arnd@arndb.de>