[SUBMITTED 20241021] Input: serio_raw - initialize serio_raw_write() the return code
The number of bytes returned from the write function is now
undefined:

drivers/input/serio/serio_raw.c:204:12: error: variable 'written' is uninitialized when used here [-Werror,-Wuninitialized]
  204 |                                 return written ?: -EIO;
      |                                        ^~~~~~~

Fixes: 5b53a9d40c4f ("Input: serio_raw - use guard notation for locks and other resources")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>