ARM: iop13xx: simplify comparison
clang warns about an unusual way to check for an error condition:

arch/arm/mach-iop13xx/pci.c:305:7: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
                if (!iop13xx_atux_pci_status(1) == 0)
                    ^                           ~~
arch/arm/mach-iop13xx/pci.c:305:7: note: add parentheses after the '!' to evaluate the comparison first
                if (!iop13xx_atux_pci_status(1) == 0)
                    ^
                     (                              )
arch/arm/mach-iop13xx/pci.c:305:7: note: add parentheses around left hand side expression to silence this warning
                if (!iop13xx_atux_pci_status(1) == 0)
                    ^

This is in fact the same as just 'if (iop13xx_atux_pci_status(1))',
which is much easier to understand and avoids the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>