remoteproc: qcom: pas: mark adsp_segment_dump() static
The function has no other callers and should not be globally defined.
Making it static avoids this warning:

drivers/remoteproc/qcom_q6v5_pas.c:108:6: error: no previous prototype for 'adsp_segment_dump'

Fixes: a376c10d45a8 ("remoteproc: qcom: pas: Adjust the phys addr wrt the mem region")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>