[SUBMITTED 20210514] ia64: mca_drv: fix incorrect array size calculation
gcc points out a mistake in the mca driver that goes back
to before the git history:

arch/ia64/kernel/mca_drv.c: In function 'init_record_index_pools':
arch/ia64/kernel/mca_drv.c:346:54: error: expression does not compute the number of elements in this array; element typ
e is 'int', not 'size_t' {aka 'long unsigned int'} [-Werror=sizeof-array-div]
  346 |         for (i = 1; i < sizeof sal_log_sect_min_sizes/sizeof(size_t); i++)
      |                                                      ^

This is the same as sizeof(size_t), which is two shorter than the
actual array. Use the ARRAY_SIZE() macro to get the correct
calculation instead.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>