[SUBMITTED 20180328] time: export nsec_to_clock_t
nsec_to_clock_t was traditionally used only in the core kernel, now we
have a sysfs file that needs it from a loadable module, causing a
link-time error:

ERROR: "nsec_to_clock_t" [drivers/thermal/thermal_sys.ko] undefined!

This exports the function the same way that we do for related interfaces.

Fixes: 96cea33badc5 ("thermal: Add cooling device's statistics in sysfs")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>