[SUBMITTED 20161122] usb: musb: mark PM functions as __maybe_unused
Building without CONFIG_PM causes a harmless warning:

drivers/usb/musb/musb_core.c:2041:12: error: ‘musb_run_resume_work’ defined but not used [-Werror=unused-function]

Removing the #ifdef around the PM code and instead marking the suspend/resume
functions as __maybe_unused will do the right thing without warning.

Fixes: ea2f35c01d5e ("usb: musb: Fix sleeping function called from invalid context for hdrc glue")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>