ASoC: tlv320aic23 needs I2C
The tlv320aic23 codec is selected by two platform specific drivers,
which are missing a dependency on I2C, and that can result in this
build error, as found during randconfig builds:

.../codecs/tlv320aic23-i2c.c: In function 'tlv320aic23_i2c_probe':
.../codecs/tlv320aic23-i2c.c:27:2: error: implicit declaration of function 'i2c_check_functionality' [-Werror=implicit-function-declaration]
  if (!i2c_check_functionality(i2c->adapter, I2C_FUNC_SMBUS_BYTE_DATA))
  ^

This adds the missing dependencies in at91 and ep93xx.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>