scsi: qlogicpti: mark qlogicpti_info() static
The qlogicpti_info() function is only used in this file and should
be static to avoid a warning:

drivers/scsi/qlogicpti.c:846:13: error: no previous prototype for 'qlogicpti_info' [-Werror=missing-prototypes]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>