sysctl: fix unused function warning
kernel/sysctl.c:205:12: error: unused function 'bpf_stats_handler' [-Werror,-Wunused-function]
static int bpf_stats_handler(struct ctl_table *table, int write,

Signed-off-by: Arnd Bergmann <arnd@arndb.de>