[SUBMITTED 20190304] netfilter: nf_conntrack_sip: fix IPV6 dependency
With CONFIG_IPV6=m and CONFIG_NF_CONNTRACK_SIP=y, we now get a link failure:

net/netfilter/nf_conntrack_sip.o: In function `process_sdp':
nf_conntrack_sip.c:(.text+0x4344): undefined reference to `ip6_route_output_flags'

Fix this by adding a dependency that forces CONFIG_NF_CONNTRACK_SIP to be =m
when CONFIG_IPV6=m, as we already do for several other drivers with a similar
requirement.

Fixes: a3419ce3356c ("netfilter: nf_conntrack_sip: add sip_external_media logic")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>