media: mb86a16: avoid excessive stack usage with kasan
kasan needs to guard stack variable that are passed by reference,
which leads to a significant stack usage in this driver passing
many local variables into the mb86a16_read() function:

drivers/media/dvb-frontends/mb86a16.c: In function 'mb86a16_set_fe':
drivers/media/dvb-frontends/mb86a16.c:1498:1: error: the frame size of 1296 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Rewrite the function in a way that lets gcc optimize it better,
with a new mb86a16_read_byte() function split out that does not
need to get inlined here.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>