drm/nouveau/bus/hwsq: reduce stack size with KASAN
A couple of functions use relatively large stack frames when CONFIG_KASAN
is enabled, which can potentially lead to a kernel stack overflow:

drivers/gpu/drm/nouveau/nvkm/subdev/fb/ramnv50.c: In function 'nv50_ram_calc':
drivers/gpu/drm/nouveau/nvkm/subdev/fb/ramnv50.c:478:1: error: the frame size of 1664 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
drivers/gpu/drm/nouveau/nvkm/subdev/fb/ramgf100.c: In function 'gf100_ram_calc':
drivers/gpu/drm/nouveau/nvkm/subdev/fb/ramgf100.c:405:1: error: the frame size of 1776 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]

Marking two functions as not inlined with KASAN reduces the frame size to around
1100 bytes on 64-bit architectures, which is a lot better already, though still
much worse than the 200 bytes without KASAN.

I could not find an easy way to reduce the frame size further.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>