[SUBMITTED 20210225] virt: acrn: add hotplug_cpu dependency
Without CPU hotplug, acrn fails to build:

drivers/virt/acrn/hsm.c:389:3: error: implicit declaration of function 'remove_cpu' [-Werror,-Wimplicit-function-declaration]
                remove_cpu(cpu);
                ^
drivers/virt/acrn/hsm.c:402:2: error: implicit declaration of function 'add_cpu' [-Werror,-Wimplicit-function-declaration]
        add_cpu(cpu);
        ^

Enforce the dependency through Kconfig to avoid the build failure.

Fixes: 666834c47d3b ("virt: acrn: Introduce ACRN HSM basic driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>