[SUBMITTED 20160616] mic: remove unused function arg
When building with W=1, the __scif_rma_destroy_tcw function
causes a harmless warning about an argument variable that is
modified but not used:

drivers/misc/mic/scif/scif_dma.c: In function ‘__scif_rma_destroy_tcw’:
drivers/misc/mic/scif/scif_dma.c:118:27: error: parameter ‘ep’ set but not used [-Werror=unused-but-set-parameter]

In this case, we can just remove the argument, since all callers
are in the same file.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>