[SUBMITTED 20250620] binfmt_elf: reduce stackusage in kunit test
Constructing arrays on the stack in the test case triggers a warning
in some configurations:

fs/tests/binfmt_elf_kunit.c: In function 'total_mapping_size_test':
fs/tests/binfmt_elf_kunit.c:52:1: error: the frame size of 1448 bytes is larger than 1408 bytes [-Werror=frame-larger-than=]

Change the arrays to 'static const' to not use any stack space at all.
This is possible since the contents are never modified.

Fixes: 9e1a3ce0a952 ("binfmt_elf: Introduce KUnit test")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>