[SUBMITTED] drm/nouveau/platform: add IOMMU dependency
The recently added iommu code in the nouveau driver fails to build
when the IOMMU support is disabled:

drivers/gpu/drm/nouveau/nouveau_platform.c: In function 'nouveau_platform_probe_iommu':
drivers/gpu/drm/nouveau/nouveau_platform.c:113:41: error: 'const struct iommu_ops' has no mem

To avoid the build error, this now adds an explicit dependency on the
IOMMU implementation.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 58fd9375c2c5 ("drm/nouveau/platform: probe IOMMU if present")