[SUBMITTED 20190918] sched/uclamp: fix building without cgroup
The css_task_iter interfaces are defined conditionally and
cause build failures when used in other configurations:

kernel/sched/core.c:1081:23: error: variable has incomplete type 'struct css_task_iter'
kernel/sched/core.c:1084:2: error: implicit declaration of function 'css_task_iter_start' [-Werror,-Wimplicit-function-declaration]
kernel/sched/core.c:1085:14: error: implicit declaration of function 'css_task_iter_next' [-Werror,-Wimplicit-function-declaration]
kernel/sched/core.c:1091:2: error: implicit declaration of function 'css_task_iter_end' [-Werror,-Wimplicit-function-declaration]

As this code is unused anyway in that configuration, just put
it into the same #ifdef. This also avoids possible warnings
about unused inline functions.

Fixes: babbe170e053 ("sched/uclamp: Update CPU's refcount on TG's clamp changes")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>