[SUBMITTED 20160914] usb: use of_usb_get_dr_mode_by_phy() inline helper without USB
We have had two new PHY drivers call of_usb_get_dr_mode_by_phy()
recently without having a dependency on CONFIG_USB_COMMON, resulting
in a link error:

ERROR: "of_usb_get_dr_mode_by_phy" [drivers/phy/phy-meson-usb2.ko] undefined!

I fixed up the first one (sun4i) by adding the dependency, but
if we get more of this, it's probably better to allow the PHY
drivers to build without the dependency.

This changes the guard around declarations so we only refer to
them when both CONFIG_OF and CONFIG_USB_COMMON are enabled,
which is the right thing for all of the first calls but not the
one that already has a correct check for USB_SUPPORT rather than
USB_COMMON.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 5ed935458519 ("phy: meson: add USB2 PHY support for Meson8b and GXBB")