[SUBMITTED 20200428] net: ena: fix gcc-4.8 missing-braces warning
Older compilers warn about initializers with incorrect curly
braces:

drivers/net/ethernet/amazon/ena/ena_netdev.c: In function 'ena_xdp_xmit_buff':
drivers/net/ethernet/amazon/ena/ena_netdev.c:311:2: error: expected ',' or ';' before 'struct'
  struct ena_tx_buffer *tx_info;
  ^~~~~~
drivers/net/ethernet/amazon/ena/ena_netdev.c:321:2: error: 'tx_info' undeclared (first use in this function)
  tx_info = &xdp_ring->tx_buffer_info[req_id];
  ^~~~~~~
drivers/net/ethernet/amazon/ena/ena_netdev.c:321:2: note: each undeclared identifier is reported only once for each function it appears in

Use the GNU empty initializer extension to avoid this.

Fixes: 31aa9857f173 ("net: ena: enable negotiating larger Rx ring size")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>