[SUBMITTED 20170710] binfmt_flat: fix format string for u32
The types have changed from 'unsigned long' to 'u32', so now the
format string is wrong, and produces a harmless warning on arm32:

arm-soc/fs/binfmt_flat.c: In function 'load_flat_file':
arm-soc/fs/binfmt_flat.c:577:25: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'u32 {aka unsigned int}' [-Werror=format=]

This changes it to '%d' instead, matching the 'u32' type.

Fixes: 468138d78510 ("binfmt_flat: flat_{get,put}_addr_from_rp() should be able to fail")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>