[SUBMITTED 20160623] partition/efi: use bdev_logical_block_count()
Enabling CONFIG_UBSAN_SANITIZE_ALL on ARM caused a link error:

last_lba.part.0':
:(.text+0xc3440): undefined reference to `____ilog2_NaN'
:(.text+0xc3538): undefined reference to `__aeabi_uldivmod'
:(.text+0xc38e8): undefined reference to `__aeabi_uldivmod'

This is caused by gcc not behaving in the expected ways with __builtin_constant_p(),
but it also points to somewhat inefficient code based on a 64-bit
division.

I have introduced a better bdev_logical_block_count() now, so we
can use that here.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>