[SUBMITTED 20160907] tracing/hwlat: select TRACER_MAX_TRACE
hwlat_trace cannot work without CONFIG_TRACER_MAX_TRACE:

kernel/trace/trace_hwlat.c: In function 'get_sample':
kernel/trace/trace_hwlat.c:258:18: error: 'struct trace_array' has no member named 'max_latency'; did you mean 'max_lock'?
   if (sample > tr->max_latency)
                  ^~
kernel/trace/trace_hwlat.c:259:6: error: 'struct trace_array' has no member named 'max_latency'; did you mean 'max_lock'?
    tr->max_latency = sample;
      ^~
kernel/trace/trace_hwlat.c: In function 'hwlat_tracer_init':
kernel/trace/trace_hwlat.c:583:4: error: 'struct trace_array' has no member named 'max_latency'; did you mean 'max_lock'?
  tr->max_latency = 0;

We also have to enable CONFIG_TRACER_SNAPSHOT, which in turn
is a dependency of CONFIG_TRACER_MAX_TRACE.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: e7c15cd8a113 ("tracing: Added hardware latency tracer")