[APPLIED] lib: dhry_run: avoid uninitialized variable warning
lib/dhry_run.c:61:6: error: variable 'ret' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]

Fixes: fb6bda44a1f0 ("lib: add Dhrystone benchmark test")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>