mwifiex: move local variables into c files
When building the mwifiex driver with extra warnings enabled (make W=1),
we get many warnings like:

mwifiex/sdio.h:571:41: error: 'mwifiex_sdio_sd8801' defined but not used [-Werror=unused-const-variable=]
mwifiex/sdio.h:556:41: error: 'mwifiex_sdio_sd8887' defined but not used [-Werror=unused-const-variable=]
mwifiex/sdio.h:540:41: error: 'mwifiex_sdio_sd8997' defined but not used [-Werror=unused-const-variable=]
mwifiex/sdio.h:525:41: error: 'mwifiex_sdio_sd8897' defined but not used [-Werror=unused-const-variable=]
mwifiex/sdio.h:510:41: error: 'mwifiex_sdio_sd8797' defined but not used [-Werror=unused-const-variable=]
mwifiex/sdio.h:495:41: error: 'mwifiex_sdio_sd8787' defined but not used [-Werror=unused-const-variable=]
mwifiex/sdio.h:480:41: error: 'mwifiex_sdio_sd8786' defined but not used [-Werror=unused-const-variable=]
mwifiex/pcie.h:307:41: error: 'mwifiex_pcie8997' defined but not used [-Werror=unused-const-variable=]
mwifiex/pcie.h:297:41: error: 'mwifiex_pcie8897' defined but not used [-Werror=unused-const-variable=]
mwifiex/pcie.h:289:41: error: 'mwifiex_pcie8766' defined but not used [-Werror=unused-const-variable=]

since we have the same few variables defined in header files that
are included from each other file.

This moves the contents of the header files that are only used by
one of the driver files into the place where they are used.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>