[SUBMITTED 20230612] net: ethernet: ti-cpsw: select CONFIG_GENERIC_ALLOCATOR
The dependency was lost for both cpsw and davinci-emac, but only
added back for the emac driver, so a cpsw-only build can still fail:

x86_64-linux-ld: vmlinux.o: in function `cpdma_desc_pool_destroy':
davinci_cpdma.c:(.text+0xd9fb97): undefined reference to `gen_pool_size'
x86_64-linux-ld: davinci_cpdma.c:(.text+0xd9fba8): undefined reference to `gen_pool_avail'
x86_64-linux-ld: vmlinux.o: in function `cpdma_desc_pool_create':
davinci_cpdma.c:(.text+0xd9fd21): undefined reference to `devm_gen_pool_create'
x86_64-linux-ld: davinci_cpdma.c:(.text+0xd9fe15): undefined reference to `gen_pool_add_owner'
x86_64-linux-ld: vmlinux.o: in function `__cpdma_chan_free':
davinci_cpdma.c:(.text+0xd9ffde): undefined reference to `gen_pool_free_owner'
x86_64-linux-ld: vmlinux.o: in function `cpdma_chan_submit_si':
davinci_cpdma.c:(.text+0xda039e): undefined reference to `gen_pool_alloc_algo_owner'
x86_64-linux-ld: davinci_cpdma.c:(.text+0xda064f): undefined reference to `gen_pool_free_owner'
x86_64-linux-ld: vmlinux.o: in function `cpdma_check_free_tx_desc':

Fixes: b2ef81dcdf383 ("net: ethernet: ti: Add dependency for TI_DAVINCI_EMAC")
Fixes: 99f6297182729 ("net: ethernet: ti: cpsw: drop TI_DAVINCI_CPDMA config option")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>