[SUBMITTED 20230501] pds_core: fix linking without CONFIG_DEBUG_FS
The debugfs.o file is only built when the fs is enabled:

main.c:(.text+0x47c): undefined reference to `pdsc_debugfs_del_dev'
main.c:(.text+0x8dc): undefined reference to `pdsc_debugfs_add_dev'
main.c:(.exit.text+0x14): undefined reference to `pdsc_debugfs_destroy'
main.c:(.init.text+0x8): undefined reference to `pdsc_debugfs_create'
dev.c:(.text+0x988): undefined reference to `pdsc_debugfs_add_ident'
core.c:(.text+0x6b0): undefined reference to `pdsc_debugfs_del_qcq'
core.c:(.text+0x998): undefined reference to `pdsc_debugfs_add_qcq'
core.c:(.text+0xf0c): undefined reference to `pdsc_debugfs_add_viftype'

Add dummy helper functions for these interfaces.

Fixes: 55435ea7729a ("pds_core: initial framework for pds_core PF driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>