watchdog: ixp4xx: use portable rev0 check
Compile-testing the driver on x86 shows that read_cpuid_id()
is unavailable there:

drivers/watchdog/ixp4xx_wdt.c:175:8: error: implicit declaration of function 'read_cpuid_id' [-Werror,-Wimplicit-function-declaration]
        if (!(read_cpuid_id() & 0xf) && !cpu_is_ixp46x()) {
              ^

The check can be replaced with the equivalent cpu_is_ixp42x_rev_a0()
that is defined in a global header now.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>