fixup! [SUBMITTED 20161122] ARM: fix kmemleak for XIP_KERNEL ARM: XIP: fix VMLINUX_SYMBOL definition:
Commit d79bf21e0e02 ("vmlinux.lds: add missing VMLINUX_SYMBOL macros)
did this for architectures using the generic RO_AFTER_INIT_DATA
definition, but XIP ARM has its own and caused another link error:

mm/kmemleak.o: In function `kmemleak_scan':
kmemleak.c:(.text.kmemleak_scan+0x2d8): undefined reference to `__end_ro_after_init'
kmemleak.c:(.text.kmemleak_scan+0x2dc): undefined reference to `__start_ro_after_init'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>