[SUBMITTED 20160616] fbmon: remove unused function argument
When building with "make W=1", we get a warning about an
empty stub function that does nothing but reassign its one
of its arguments:

drivers/video/fbdev/core/fbmon.c: In function 'fb_edid_to_monspecs':
drivers/video/fbdev/core/fbmon.c:1497:67: error: parameter 'specs' set but not used [-Werror=unused-but-set-parameter]

We can simply make that function completely empty to avoid
the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>