[SUBMITTED 20251204] drm/panel: visionox-rm69299: add backlight dependency
The recently added backlight support breaks when CONFIG_BACKLIGHT_CLASS_DEVICE
is turned off:

arm-linux-gnueabi-ld: drivers/gpu/drm/panel/panel-visionox-rm69299.o: in function `visionox_rm69299_probe':
panel-visionox-rm69299.c:(.text.visionox_rm69299_probe+0x92): undefined reference to `devm_backlight_device_register'
arm-linux-gnueabi-ld: (devm_backlight_device_register): Unknown destination type (ARM/Thumb) in drivers/gpu/drm/panel/panel-visionox-rm69299.o

Add the appropriate Kconfig dependency.

Fixes: 7911d8cab554 ("drm/panel: visionox-rm69299: Add backlight support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>