md: raid10: avoid VLAIS
clang fails to build the raid10 code because of a variable-length
array in a structure (VLAIS):

../drivers/md/raid10.c:4488:17: error: fields must have a constant size: 'variable length array in structure' extension will never be supported

Those constructs are usually a bad idea, and this patch replaces it
with an alloca() call that is not much better either but at least builds
with clang.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>