[SUBMITTED 20221215] pinctrl: nomadik: include linux/seq_file.h
In some randconfig builds, the missing #include causes a
build failure:

drivers/pinctrl/nomadik/pinctrl-nomadik.c: In function 'nmk_gpio_irq_print_chip':
drivers/pinctrl/nomadik/pinctrl-nomadik.c:1084:9: error: implicit declaration of function 'seq_printf'; did you mean 'bstr_printf'? [-Werror=implicit-function-declaration]
 1084 |         seq_printf(p, "nmk%u-%u-%u", nmk_chip->bank,
      |         ^~~~~~~~~~
      |         bstr_printf

Signed-off-by: Arnd Bergmann <arnd@arndb.de>