[SUBMITTED 20250520] crypto: qat - add missing header inclusion
Without this header, building the new driver fails with:

In file included from drivers/crypto/intel/qat/qat_common/adf_gen6_shared.c:7:
drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h: In function 'adf_gen4_init_pf_pfvf_ops':
drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h:13:34: error: 'adf_pfvf_comms_disabled' undeclared (first use in this function)
   13 |         pfvf_ops->enable_comms = adf_pfvf_comms_disabled;
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~

Fixes: 17fd7514ae68 ("crypto: qat - add qat_6xxx driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>