ARM: realview: hide unused 'pmu_device' object
The pmu_device is only accessed when CACHE_L2X0 is enabled,
and we get a warning otherwise:

mach-realview/realview_pbx.c:274:31: error: 'pmu_device' defined but not used [-Werror=unused-variable]

This adds another #ifdef for it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>