x86: percpu: fix clang 32-bit build
clang does not like an inline assembly with a "=q" contraint for
a 64-bit output:

arch/x86/events/perf_event.h:824:21: error: invalid output size for constraint '=q'
        u64 disable_mask = __this_cpu_read(cpu_hw_events.perf_ctr_virt_mask);
                           ^
include/linux/percpu-defs.h:447:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
include/linux/percpu-defs.h:421:28: note: expanded from macro 'raw_cpu_read'
 #define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
include/linux/percpu-defs.h:322:23: note: expanded from macro '__pcpu_size_call_return'
        case 1: pscr_ret__ = stem##1(variable); break;                  \
                             ^
<scratch space>:357:1: note: expanded from here
raw_cpu_read_1
^
arch/x86/include/asm/percpu.h:394:30: note: expanded from macro 'raw_cpu_read_1'
 #define raw_cpu_read_1(pcp)             percpu_from_op(, "mov", pcp)
                                        ^
arch/x86/include/asm/percpu.h:189:15: note: expanded from macro 'percpu_from_op'
                    : "=q" (pfo_ret__)                  \
                            ^

According to the commit that introduced the "q" constraint, this was
needed to fix miscompilation, but it gives no further detail.

Using the normal "=r" constraint seems to work.

Fixes: 3c598766a2ba ("x86: fix percpu_{to,from}_op()")
Cc: Jan Beulich <jbeulich@suse.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>