[SUBMITTED 20250304] mm/page_alloc: add dummy in_mem_hotplug() helper
The in_mem_hotplug() prototype was only added to the CONFIG_MEMORY_HOTPLUG
case but is missing from the alternative:

mm/page_alloc.c: In function 'set_pageblock_migratetype':
/home/arnd/arm-soc/mm/page_alloc.c:424:17: error: implicit declaration of function 'in_mem_hotplug' [-Wimplicit-function-declaration]
  424 |                 in_mem_hotplug() ||
      |                 ^~~~~~~~~~~~~~

Add an empty stub like we have for similar functions.

Fixes: b4cfcc26f507 ("mm/page_alloc: add lockdep assertion for pageblock type change")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>