[SUBMITTED 20190906] watch_queue: make locked_vm accessible
The locked_vm member of struct user_struct is guarded by an #ifdef,
which breaks building the new watch_queue driver when all the other
subsystems that need it are disabled:

drivers/misc/watch_queue.c:315:38: error: no member named 'locked_vm' in 'struct user_struct'; did you mean 'locked_shm'?

Add watch_queue to the list.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>