[SUBMITTED 20161122] overlayfs: fix ovl_get_redirect() error handling
The newly introduced ovl_get_redirect() function returns an unintialized
variable when kmalloc() fails:

fs/overlayfs/dir.c: In function ‘ovl_set_redirect’:
fs/overlayfs/overlayfs.h:92:6: error: ‘ret’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

This makes it return -ENOMEM instead.

Fixes: 496654b0792e ("ovl: redirect on rename-dir")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>