[SUBMITTED 20241015] wifi: ipw2x00/lib80211: select ARC4 helper
The lib80211 code uses arc4 crypto helpers that can be
disabled:

ERROR: modpost: "arc4_setkey" [drivers/net/wireless/intel/ipw2x00/libipw.ko] undefined!
ERROR: modpost: "arc4_crypt" [drivers/net/wireless/intel/ipw2x00/libipw.ko] undefined!

Select the library from Kconfig to ensure this can be called.

Fixes: 02f220b52670 ("wifi: ipw2x00/lib80211: move remaining lib80211 into libipw")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>