xdp: fix trace event compilation
I ran into a build error on linux-next-20171017:

In file included from include/trace/events/xdp.h:9:0,
                 from include/linux/bpf_trace.h:5,
                 from drivers/net/ethernet/intel/i40e/i40e_txrx.c:29:
include/trace/events/xdp.h:91:17: error: 'struct bpf_map' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
    const struct bpf_map *map, u32 map_index),
                 ^
include/linux/tracepoint.h:184:34: note: in definition of macro '__DECLARE_TRACE'
  static inline void trace_##name(proto)    \

I don't know what patch introduced the problem, but it seems that
the xdp.h header should include all other headers that are needed
for the structures it uses.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>