[HACK] efi: libstub: avoid ilog2(u64)
drivers/firmware/efi/libstub/random.stub.o: In function `efi_random_alloc':
random.c:(.text.efi_random_alloc+0x1c0): undefined reference to `__aeabi_llsr'

This change is safe because the alignment is always a small number

Signed-off-by: Arnd Bergmann <arnd@arndb.de>