drm/amd/dc: dce_calcs: reduce stack usage
With clang, chaining bw_fixed() operations leads to increased stack
usage, 8 bytes for each instance that add up to something beyond
the warning limit:

drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dce_calcs.c:2989:6: error: stack frame size of 1520 bytes in function 'bw_calcs' [-Werror,-Wframe-larger-than=]

Since a lot of lines just contain the same construct

	bw_fixed_to_int(bw_mul(data->foo, bw_int_to_fixed(1000)));

replace that with a simpler version that uses no intermediate
structures.

Link: https://bugs.llvm.org/show_bug.cgi?id=42551
Signed-off-by: Arnd Bergmann <arnd@arndb.de>