ARM: nommu: include asm/idmap.h
setup_mm_for_reboot() is declared in asm/idmap.h but that is not included
for the definition, causing a W=1 warning:

arch/arm/mm/nommu.c:178:6: error: no previous prototype for 'setup_mm_for_reboot' [-Werror=missing-prototypes]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>