[SUBMITTED 20211204] media: staging: max96712: add V4L2 dependencies
Without the extra dependencies, I run into randconfig build failures:

WARNING: unmet direct dependencies detected for VIDEO_V4L2_SUBDEV_API
  Depends on [n]: MEDIA_SUPPORT [=y] && VIDEO_DEV [=n] && MEDIA_CONTROLLER [=y]
  Selected by [y]:
  - VIDEO_MAX96712 [=y] && STAGING [=y] && STAGING_MEDIA [=y] && MEDIA_SUPPORT [=y] && I2C [=y] && OF_GPIO [=y]

aarch64-linux-ld: drivers/staging/media/max96712/max96712.o: in function `max96712_probe':
max96712.c:(.text+0x1b8): undefined reference to `v4l2_fwnode_endpoint_parse'
aarch64-linux-ld: max96712.c:(.text+0x374): undefined reference to `v4l2_ctrl_handler_init_class'
aarch64-linux-ld: max96712.c:(.text+0x3b0): undefined reference to `v4l2_ctrl_new_std'

Fixes: 5814f32fef13 ("media: staging: max96712: Add basic support for MAX96712 GMSL2 deserializer")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>