mfd: vexpress-config needs CONFIG_OF
Building this driver with CONFIG_OF disabled results in this
build error:

mfd/vexpress-config.c: In function '__vexpress_config_func_get':
mfd/vexpress-config.c:116:4: error: implicit declaration of function 'of_find_node_by_phandle' [-Werror=implicit-function-declaration]
    bridge_node = of_find_node_by_phandle(
    ^
mfd/vexpress-config.c:116:16: warning: assignment makes pointer from integer without a cast [enabled by default]
    bridge_node = of_find_node_by_phandle(
                ^

This adds an explcit dependency, which is fine since the only
platform using this driver already has CONFIG_OF enabled.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>