arm-cci: add cci_enable_port_for_self prototype
The cci_enable_port_for_self() is called from assembler, so
add the prototype only to shut up the W=1 warning:

drivers/bus/arm-cci.c:298:25: error: no previous prototype for 'cci_enable_port_for_self' [-Werror=missing-prototypes]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>