firmware: qcom_scm: mark qcom_scm_qseecom_allowlist as __maybe_unused
When CONFIG_OF is disabled, there is no reference to this variable:

drivers/firmware/qcom/qcom_scm.c:1655:34: error: unused variable 'qcom_scm_qseecom_allowlist' [-Werror,-Wunused-const-variable]
static const struct of_device_id qcom_scm_qseecom_allowlist[] = {

Mark it as __maybe_unused to hide this warning.

Fixes: 00b1248606ba ("firmware: qcom_scm: Add support for Qualcomm Secure Execution Environment SCM interface")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>