[SUBMITTED 20251204] x86/hyperv: fix build failure for CONFIG_SMP=n
The smp_ops structure is only defined for SMP builds:

arch/x86/hyperv/hv_crash.c: In function 'hv_root_crash_init':
arch/x86/hyperv/hv_crash.c:631:9: error: 'smp_ops' undeclared (first use in this function)
  631 |         smp_ops.crash_stop_other_cpus = hv_crash_stop_other_cpus;
      |         ^~~~~~~
arch/x86/hyperv/hv_crash.c:631:9: note: each undeclared identifier is reported only once for each function it appears in

Hide this in an #ifdef.

Fixes: 94212d34618c ("x86/hyperv: Implement hypervisor RAM collection into vmcore")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
Alternatively we could just make hyperv 'depends on SMP' to avoid the ugly #ifdef