[SUBMITTED 20241029] perf/arm_pmuv3: fix building on 32-bit
The write_pmuacr() function is only defined on arm64, so building the
driver on 32-bit arm now fails:

drivers/perf/arm_pmuv3.c: In function 'armv8pmu_enable_user_access':
drivers/perf/arm_pmuv3.c:784:17: error: implicit declaration of function 'write_pmuacr'; did you mean 'write_pmcr'? [-Wimplicit-function-declaration]

Add a compile-time check around the newly added code, as it is never
needed on arm32.

Fixes: 0bbff9ed8165 ("perf/arm_pmuv3: Add PMUv3.9 per counter EL0 access control")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>