i2c: icy: remove an unused variable
This was left over after a cleanup and should be removed as well.

drivers/i2c/busses/i2c-icy.c: In function 'icy_probe':
drivers/i2c/busses/i2c-icy.c:126:24: error: unused variable 'new_fwnode' [-Werror=unused-variable]

Fixes: dd7a37102b79 ("i2c: icy: Constify the software node")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>