crypto: ecrdsa - select default_rng
ecrdsa selects the ECC module, which in turn requires default_rng:

ld.lld: error: undefined symbol: crypto_get_default_rng
>>>               vmlinux.o:(ecc_gen_privkey)

ld.lld: error: undefined symbol: crypto_default_rng
>>>               vmlinux.o:(ecc_gen_privkey)

ERROR: modpost: "crypto_default_rng" [crypto/ecc.ko] undefined!
ERROR: modpost: "crypto_put_default_rng" [crypto/ecc.ko] undefined!
ERROR: modpost: "crypto_get_default_rng" [crypto/ecc.ko] undefined!

Fixes: 0d7a78643f69 ("crypto: ecrdsa - add EC-RDSA (GOST 34.10) algorithm")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>