[HACK] tracepoint: work around -Werror=alloc-size-larger-than= error
I have no idea why we get this warning:

In file included from include/linux/fs.h:45,
                 from arch/arm64/include/asm/elf.h:141,
                 from include/linux/elf.h:6,
                 from include/linux/module.h:19,
                 from kernel/tracepoint.c:5:
In function 'kmalloc',
    inlined from 'allocate_probes' at kernel/tracepoint.c:109:25,
    inlined from 'func_add' at kernel/tracepoint.c:205:8:
include/linux/slab.h:558:16: error: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
  558 |         return __kmalloc(size, flags);
      |                ^~~~~~~~~~~~~~~~~~~~~~
include/linux/slab.h: In function 'func_add':
include/linux/slab.h:443:7: note: in a call to allocation function '__kmalloc' declared here
  443 | void *__kmalloc(size_t size, gfp_t flags) __assume_kmalloc_alignment __alloc_size(1);
      |       ^~~~~~~~~

Using kcalloc() instead of kmalloc() shuts up the warning but is probably
wrong.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>