ARM: kasan: export __memcpy() etc
Disabling KASAN in a loadable module makes it call __memset()
instead of memset(), which leads to a link failure:

ERROR: modpost: "__memcpy" [drivers/input/joydev.ko] undefined!
ERROR: modpost: "__memset" [drivers/input/joydev.ko] undefined!

Export these symbols as well.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>