profile: hide unused functions when !CONFIG_PROC_FS
../kernel/profile.c:243:13: error: 'profile_flip_buffers' defined but not used [-Werror=unused-function]
 static void profile_flip_buffers(void)
             ^
../kernel/profile.c:266:13: error: 'profile_discard_flip_buffers' defined but not used [-Werror=unused-function]
 static void profile_discard_flip_buffers(void)
             ^
../kernel/profile.c:330:12: error: 'profile_cpu_callback' defined but not used [-Werror=unused-function]
 static int profile_cpu_callback(struct notifier_block *info,
            ^

Signed-off-by: Arnd Bergmann <arnd@arndb.de>