clk: use div_u64 instead of do_div
drivers/clk/built-in.o: In function `berlin2_avpll_channel_recalc_rate':
clk-zx296702.c:(.text+0x3e958): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x3e9a0): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x3e9f4): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x3eb14): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x3eb84): undefined reference to `__aeabi_uldivmod'
drivers/clk/built-in.o:clk-zx296702.c:(.text+0x3ebac): more undefined references to `__aeabi_uldivmod' follow
drivers/clk/built-in.o: In function `berlin2_avpll_channel_recalc_rate':
clk-zx296702.c:(.text+0x3f258): undefined reference to `____ilog2_NaN'
clk-zx296702.c:(.text+0x3f310): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x3f414): undefined reference to `__aeabi_uldivmod'
drivers/clk/built-in.o: In function `pll_clk_round_rate':
clk-zx296702.c:(.text+0x6aa9c): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x6aadc): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x6ab24): undefined reference to `__aeabi_uldivmod'
drivers/clk/built-in.o:clk-zx296702.c:(.text+0x6ac38): more undefined references to `__aeabi_uldivmod' follow
drivers/clk/built-in.o: In function `pll_clk_round_rate':
clk-zx296702.c:(.text+0x6b088): undefined reference to `____ilog2_NaN'
clk-zx296702.c:(.text+0x6b19c): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x6b28c): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x6d1cc): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x6d20c): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x6d254): undefined reference to `__aeabi_uldivmod'
drivers/clk/built-in.o:clk-zx296702.c:(.text+0x6d368): more undefined references to `__aeabi_uldivmod' follow
drivers/clk/built-in.o: In function `pll_clk_round_rate':
clk-zx296702.c:(.text+0x6d7b8): undefined reference to `____ilog2_NaN'
clk-zx296702.c:(.text+0x6d8cc): undefined reference to `__aeabi_uldivmod'
clk-zx296702.c:(.text+0x6d9bc): undefined reference to `__aeabi_uldivmod'

Signed-off-by: Arnd Bergmann <arnd@arndb.de>