i2c: ks0127: reduce stack frame size for KASAN
When CONFIG_KASAN is set, inlining of functions with local variables
causes excessive stack usage:

drivers/media/i2c/ks0127.c: In function 'ks0127_s_routing':
drivers/media/i2c/ks0127.c:541:1: error: the frame size of 3136 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]

Marking one functions as noinline_if_stackbloat solves the problem in this
driver.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>