[SUBMITTED 20260202] [v2] kunit: reduce stack usage in kunit_run_tests()
Some of the recent changes to the kunit framework caused the stack usage
for kunit_run_tests() to grow higher than most other kernel functions,
which triggers a warning when CONFIG_FRAME_WARN is set to a relatively
low value:

lib/kunit/test.c: In function 'kunit_run_tests':
lib/kunit/test.c:801:1: error: the frame size of 1312 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Split out the inner loop into a separate function to ensure that each
function remains under the limit, and pass the kunit_result_stats
structures by reference to avoid excessive copies.

Cc: Carlos Llamas <cmllamas@google.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
---
v2:
 - plit out two functions instead of one, as there were still
   stack size warnings with clang on the earlier version
 - use void return type suggested by Carlos

Carlos has successfully tested version 1, but after I rebased on
current linux-next, the build warnings came back due to some other
changes, and I had to rework the patch.