[HACK] ARM: fa526: avoid using missing cpu suspend function
Building a kernel with ARM_CPU_SUSPEND enabled but fa526 as the only
enabled CPU gives us this link error:

arch/arm/kernel/built-in.o: In function `__cpu_suspend':
:(.text+0x4260): undefined reference to `cpu_fa526_suspend_size'
arch/arm/kernel/built-in.o: In function `__cpu_suspend_save':
:(.text+0x43c0): undefined reference to `cpu_fa526_do_resume'
:(.text+0x43c4): undefined reference to `cpu_fa526_do_suspend'

This patch is probably not right, but it avoids the error.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>