dma: iop-adma: fix pointer type mismatch
Using the same variable for virtual and physical addresses
causes some warnings:

drivers/dma/iop-adma.c: In function 'iop_adma_alloc_chan_resources':
drivers/dma/iop-adma.c:448:13: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
   hw_desc = (char *) iop_chan->device->dma_desc_pool;
             ^
drivers/dma/iop-adma.c:450:4: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
    (dma_addr_t) &hw_desc[idx * IOP_ADMA_SLOT_SIZE];
    ^
In file included from include/linux/dma-mapping.h:7,
                 from drivers/dma/iop-adma.c:15:
drivers/dma/iop-adma.c: In function 'iop_adma_probe':
drivers/dma/iop-adma.c:1302:3: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
   (void *) adev->dma_desc_pool);
   ^
include/linux/device.h:1754:46: note: in definition of macro 'dev_dbg'
  dev_printk(KERN_DEBUG, dev, dev_fmt(fmt), ##__VA_ARGS__)
                                              ^~~~~~~~~~~

Simplify this code using direct assignments and the special
%pad format string for printing the address to avoid the type
conversions entirely.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>