alsa: vx: avoid gcc warning for missing braces
/git/arm-soc/sound/drivers/vx/vx_core.c: In function 'snd_vx_threaded_irq_handler':
/git/arm-soc/sound/drivers/vx/vx_core.c:528:3: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
   ; /* so far, nothing to do yet */

Signed-off-by: Arnd Bergmann <arnd@arndb.de>