[SUBMITTED 20190708] nvmem: fix nvmem_cell_write() prototype
The dummy declaration for nvmem_cell_write() has a different prototype
from the one that is normally used, and it causes a warning when
CONFIG_NVMEM is disabled:

drivers/power/reset/nvmem-reboot-mode.c:27:42: error: incompatible pointer types passing 'unsigned int *' to parameter
      of type 'const char *' [-Werror,-Wincompatible-pointer-types]
        ret = nvmem_cell_write(nvmem_rbm->cell, &magic, sizeof(magic));

Make the second argument a void pointer like the other prototype has.

Fixes: 69aba7948cbe ("nvmem: Add a simple NVMEM framework for consumers")
Fixes: 7a78a7f7695b ("power: reset: nvmem-reboot-mode: use NVMEM as reboot mode write interface")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>