tty: hvc: fix link error with CONFIG_SERIAL=m
There is still a link error when SERIAL_CORE_CONSOLE is enabled, but
SERIAL_CORE is a loadable module:

WARNING: unmet direct dependencies detected for SERIAL_CORE_CONSOLE
  Depends on [n]: TTY [=y] && HAS_IOMEM [=y] && SERIAL_CORE [=m]=y
  Selected by [y]:
  - HVC_DCC [=y] && TTY [=y] && (ARM [=y] || ARM64)
arm-linux-gnueabi-ld: drivers/tty/hvc/hvc_dcc.o: in function `dcc_early_write':
hvc_dcc.c:(.text+0xc): undefined reference to `uart_console_write'

Add a dependency to avoid this.

Fixes: 75fc65079d82 ("tty: hvc: fix link error with CONFIG_SERIAL_CORE_CONSOLE=n")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>